-- xuan-inventory initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS product_stock_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    warehouse_id bigint NOT NULL,
    warehouse_name_snapshot varchar(200),
    safety_stock numeric(18,4),
    min_stock numeric(18,4),
    max_stock numeric(18,4),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_stock_policy PRIMARY KEY (id)
);
COMMENT ON TABLE product_stock_policy IS '商品仓库级库存策略。';
COMMENT ON COLUMN product_stock_policy.id IS '主键';
COMMENT ON COLUMN product_stock_policy.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_stock_policy.product_id IS '商品 ID';
COMMENT ON COLUMN product_stock_policy.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN product_stock_policy.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN product_stock_policy.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN product_stock_policy.warehouse_name_snapshot IS '仓库名称快照';
COMMENT ON COLUMN product_stock_policy.safety_stock IS '安全库存';
COMMENT ON COLUMN product_stock_policy.min_stock IS '最低库存';
COMMENT ON COLUMN product_stock_policy.max_stock IS '最高库存';
COMMENT ON COLUMN product_stock_policy.created_by IS '创建人';
COMMENT ON COLUMN product_stock_policy.created_at IS '创建时间';
COMMENT ON COLUMN product_stock_policy.updated_by IS '更新人';
COMMENT ON COLUMN product_stock_policy.updated_at IS '更新时间';
COMMENT ON COLUMN product_stock_policy.deleted_by IS '删除人';
COMMENT ON COLUMN product_stock_policy.delete_reason IS '删除原因';
COMMENT ON COLUMN product_stock_policy.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_inventory_stock_policy_key_active
    ON product_stock_policy (tenant_id, product_id, warehouse_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_stock_policy_product
    ON product_stock_policy (tenant_id, product_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_policy_warehouse
    ON product_stock_policy (tenant_id, warehouse_id, deleted_at);

CREATE TABLE IF NOT EXISTS stock_balance (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    warehouse_name_snapshot varchar(200),
    location_id bigint,
    location_name_snapshot varchar(200),
    qty_on_hand numeric(18,4) DEFAULT 0 NOT NULL,
    qty_reserved numeric(18,4) DEFAULT 0 NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_stock_balance PRIMARY KEY (id)
);
COMMENT ON TABLE stock_balance IS '当前库存余额表。';
COMMENT ON COLUMN stock_balance.id IS '主键';
COMMENT ON COLUMN stock_balance.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_balance.product_id IS '商品 ID';
COMMENT ON COLUMN stock_balance.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN stock_balance.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN stock_balance.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN stock_balance.warehouse_name_snapshot IS '仓库名称快照';
COMMENT ON COLUMN stock_balance.location_id IS '库位 ID';
COMMENT ON COLUMN stock_balance.location_name_snapshot IS '库位名称快照';
COMMENT ON COLUMN stock_balance.qty_on_hand IS '当前库存';
COMMENT ON COLUMN stock_balance.qty_reserved IS '锁定库存';
COMMENT ON COLUMN stock_balance.updated_by IS '更新人';
COMMENT ON COLUMN stock_balance.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_inventory_stock_balance_key
    ON stock_balance (tenant_id, product_id, warehouse_id, COALESCE(location_id, -1));
CREATE INDEX IF NOT EXISTS idx_inventory_stock_balance_product
    ON stock_balance (tenant_id, product_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS stock_reservation (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    reservation_no varchar(100) NOT NULL,
    source_type varchar(50) NOT NULL,
    source_id bigint NOT NULL,
    source_item_id bigint,
    product_id bigint NOT NULL,
    warehouse_id bigint,
    location_id bigint,
    qty_reserved numeric(18,4) DEFAULT 0 NOT NULL,
    status varchar(20) DEFAULT 'ACTIVE' NOT NULL,
    expires_at timestamptz,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_reservation PRIMARY KEY (id)
);
COMMENT ON TABLE stock_reservation IS '库存占用表，承接销售草稿、采购退货等占用库存场景。';
COMMENT ON COLUMN stock_reservation.id IS '主键';
COMMENT ON COLUMN stock_reservation.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_reservation.reservation_no IS '占用编号';
COMMENT ON COLUMN stock_reservation.source_type IS '来源类型';
COMMENT ON COLUMN stock_reservation.source_id IS '来源单据 ID';
COMMENT ON COLUMN stock_reservation.source_item_id IS '来源明细 ID';
COMMENT ON COLUMN stock_reservation.product_id IS '商品 ID';
COMMENT ON COLUMN stock_reservation.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN stock_reservation.location_id IS '库位 ID';
COMMENT ON COLUMN stock_reservation.qty_reserved IS '占用数量';
COMMENT ON COLUMN stock_reservation.status IS '状态';
COMMENT ON COLUMN stock_reservation.expires_at IS '过期时间';
COMMENT ON COLUMN stock_reservation.created_by IS '创建人';
COMMENT ON COLUMN stock_reservation.created_at IS '创建时间';
COMMENT ON COLUMN stock_reservation.updated_by IS '更新人';
COMMENT ON COLUMN stock_reservation.updated_at IS '更新时间';
COMMENT ON COLUMN stock_reservation.deleted_by IS '删除人';
COMMENT ON COLUMN stock_reservation.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_reservation.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_no_active
    ON stock_reservation (tenant_id, reservation_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_source
    ON stock_reservation (tenant_id, source_type, source_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_product
    ON stock_reservation (tenant_id, product_id, warehouse_id, location_id, status);

CREATE TABLE IF NOT EXISTS stock_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    txn_no varchar(100) NOT NULL,
    biz_type varchar(50) NOT NULL,
    biz_id bigint,
    biz_item_id bigint,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    location_id bigint,
    qty_delta numeric(18,4) NOT NULL,
    qty_before numeric(18,4),
    qty_after numeric(18,4),
    unit_cost numeric(18,4) DEFAULT 0 NOT NULL,
    total_cost numeric(18,2) DEFAULT 0 NOT NULL,
    operator varchar(100),
    operator_id bigint,
    remark varchar(500),
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_stock_transaction PRIMARY KEY (id)
);
COMMENT ON TABLE stock_transaction IS '库存流水表。';
COMMENT ON COLUMN stock_transaction.id IS '主键';
COMMENT ON COLUMN stock_transaction.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_transaction.txn_no IS '流水号';
COMMENT ON COLUMN stock_transaction.biz_type IS '业务类型';
COMMENT ON COLUMN stock_transaction.biz_id IS '业务单据 ID';
COMMENT ON COLUMN stock_transaction.biz_item_id IS '业务明细 ID';
COMMENT ON COLUMN stock_transaction.product_id IS '商品 ID';
COMMENT ON COLUMN stock_transaction.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN stock_transaction.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN stock_transaction.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN stock_transaction.location_id IS '库位 ID';
COMMENT ON COLUMN stock_transaction.qty_delta IS '变更数量';
COMMENT ON COLUMN stock_transaction.qty_before IS '变更前数量';
COMMENT ON COLUMN stock_transaction.qty_after IS '变更后数量';
COMMENT ON COLUMN stock_transaction.unit_cost IS '单位成本';
COMMENT ON COLUMN stock_transaction.total_cost IS '成本金额';
COMMENT ON COLUMN stock_transaction.operator IS '操作者';
COMMENT ON COLUMN stock_transaction.operator_id IS '操作者 ID';
COMMENT ON COLUMN stock_transaction.remark IS '备注';
COMMENT ON COLUMN stock_transaction.created_at IS '创建时间';
CREATE INDEX IF NOT EXISTS idx_inventory_stock_txn_no
    ON stock_transaction (tenant_id, txn_no);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_txn_biz
    ON stock_transaction (tenant_id, biz_type, biz_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_txn_product
    ON stock_transaction (tenant_id, product_id, warehouse_id, location_id, created_at DESC);

CREATE TABLE IF NOT EXISTS stock_count (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    count_no varchar(64) NOT NULL,
    count_type varchar(20) DEFAULT 'COUNT' NOT NULL,
    status varchar(20) DEFAULT 'DRAFT' NOT NULL,
    warehouse_id bigint,
    location_id bigint,
    count_at timestamptz,
    adjustment_reason varchar(32),
    approved_by varchar(100),
    approved_at timestamptz,
    cancelled_by varchar(100),
    cancelled_at timestamptz,
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_count PRIMARY KEY (id)
);
COMMENT ON TABLE stock_count IS '库存盘点单表。';
COMMENT ON COLUMN stock_count.id IS '主键';
COMMENT ON COLUMN stock_count.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_count.count_no IS '盘点单号';
COMMENT ON COLUMN stock_count.count_type IS '盘点类型';
COMMENT ON COLUMN stock_count.status IS '状态';
COMMENT ON COLUMN stock_count.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN stock_count.location_id IS '库位 ID';
COMMENT ON COLUMN stock_count.count_at IS '盘点时间';
COMMENT ON COLUMN stock_count.adjustment_reason IS '调整原因';
COMMENT ON COLUMN stock_count.approved_by IS '审核人';
COMMENT ON COLUMN stock_count.approved_at IS '审核时间';
COMMENT ON COLUMN stock_count.cancelled_by IS '作废人';
COMMENT ON COLUMN stock_count.cancelled_at IS '作废时间';
COMMENT ON COLUMN stock_count.print_count IS '打印次数';
COMMENT ON COLUMN stock_count.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN stock_count.remark IS '备注';
COMMENT ON COLUMN stock_count.created_by IS '创建人';
COMMENT ON COLUMN stock_count.created_at IS '创建时间';
COMMENT ON COLUMN stock_count.updated_by IS '更新人';
COMMENT ON COLUMN stock_count.updated_at IS '更新时间';
COMMENT ON COLUMN stock_count.deleted_by IS '删除人';
COMMENT ON COLUMN stock_count.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_count.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_inventory_stock_count_no_active
    ON stock_count (tenant_id, count_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_one_init
    ON stock_count (tenant_id)
    WHERE count_type = 'INIT' AND status = 'APPROVED' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_stock_count_status
    ON stock_count (tenant_id, count_type, status, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS stock_count_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    count_id bigint NOT NULL,
    line_no integer DEFAULT 1 NOT NULL,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    location_id bigint,
    system_qty numeric(18,4) DEFAULT 0 NOT NULL,
    counted_qty numeric(18,4) DEFAULT 0 NOT NULL,
    diff_qty numeric(18,4) DEFAULT 0 NOT NULL,
    init_unit_cost numeric(18,4),
    init_total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_count_item PRIMARY KEY (id)
);
COMMENT ON TABLE stock_count_item IS '库存盘点明细表。';
COMMENT ON COLUMN stock_count_item.id IS '主键';
COMMENT ON COLUMN stock_count_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_count_item.count_id IS '盘点单 ID';
COMMENT ON COLUMN stock_count_item.line_no IS '行号';
COMMENT ON COLUMN stock_count_item.product_id IS '商品 ID';
COMMENT ON COLUMN stock_count_item.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN stock_count_item.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN stock_count_item.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN stock_count_item.location_id IS '库位 ID';
COMMENT ON COLUMN stock_count_item.system_qty IS '系统数量';
COMMENT ON COLUMN stock_count_item.counted_qty IS '盘点数量';
COMMENT ON COLUMN stock_count_item.diff_qty IS '差异数量';
COMMENT ON COLUMN stock_count_item.init_unit_cost IS '期初单价';
COMMENT ON COLUMN stock_count_item.init_total_amount IS '期初金额';
COMMENT ON COLUMN stock_count_item.remark IS '备注';
COMMENT ON COLUMN stock_count_item.created_by IS '创建人';
COMMENT ON COLUMN stock_count_item.created_at IS '创建时间';
COMMENT ON COLUMN stock_count_item.updated_by IS '更新人';
COMMENT ON COLUMN stock_count_item.updated_at IS '更新时间';
COMMENT ON COLUMN stock_count_item.deleted_by IS '删除人';
COMMENT ON COLUMN stock_count_item.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_count_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_inventory_count_item_count
    ON stock_count_item (tenant_id, count_id, line_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_count_item_product
    ON stock_count_item (tenant_id, product_id, warehouse_id, location_id);

CREATE TABLE IF NOT EXISTS stock_transfer (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    transfer_no varchar(64) NOT NULL,
    status varchar(20) DEFAULT 'APPROVED' NOT NULL,
    transfer_at timestamptz,
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_transfer PRIMARY KEY (id)
);
COMMENT ON TABLE stock_transfer IS '库存移库单。';
COMMENT ON COLUMN stock_transfer.id IS '主键';
COMMENT ON COLUMN stock_transfer.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_transfer.transfer_no IS '移库单号';
COMMENT ON COLUMN stock_transfer.status IS '状态';
COMMENT ON COLUMN stock_transfer.transfer_at IS '移库时间';
COMMENT ON COLUMN stock_transfer.print_count IS '打印次数';
COMMENT ON COLUMN stock_transfer.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN stock_transfer.remark IS '备注';
COMMENT ON COLUMN stock_transfer.created_by IS '创建人';
COMMENT ON COLUMN stock_transfer.created_at IS '创建时间';
COMMENT ON COLUMN stock_transfer.updated_by IS '更新人';
COMMENT ON COLUMN stock_transfer.updated_at IS '更新时间';
COMMENT ON COLUMN stock_transfer.deleted_by IS '删除人';
COMMENT ON COLUMN stock_transfer.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_transfer.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_inventory_stock_transfer_no_active
    ON stock_transfer (tenant_id, transfer_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_transfer_status
    ON stock_transfer (tenant_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_transfer_at
    ON stock_transfer (tenant_id, transfer_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS stock_transfer_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    transfer_id bigint NOT NULL,
    line_no integer DEFAULT 1 NOT NULL,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    from_warehouse_id bigint NOT NULL,
    from_location_id bigint,
    to_warehouse_id bigint NOT NULL,
    to_location_id bigint,
    qty numeric(18,4) DEFAULT 0 NOT NULL,
    unit_cost numeric(18,4) DEFAULT 0 NOT NULL,
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_transfer_item PRIMARY KEY (id)
);
COMMENT ON TABLE stock_transfer_item IS '库存移库明细。';
COMMENT ON COLUMN stock_transfer_item.id IS '主键';
COMMENT ON COLUMN stock_transfer_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_transfer_item.transfer_id IS '移库单 ID';
COMMENT ON COLUMN stock_transfer_item.line_no IS '行号';
COMMENT ON COLUMN stock_transfer_item.product_id IS '商品 ID';
COMMENT ON COLUMN stock_transfer_item.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN stock_transfer_item.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN stock_transfer_item.from_warehouse_id IS '来源仓库 ID';
COMMENT ON COLUMN stock_transfer_item.from_location_id IS '来源库位 ID';
COMMENT ON COLUMN stock_transfer_item.to_warehouse_id IS '目标仓库 ID';
COMMENT ON COLUMN stock_transfer_item.to_location_id IS '目标库位 ID';
COMMENT ON COLUMN stock_transfer_item.qty IS '移库数量';
COMMENT ON COLUMN stock_transfer_item.unit_cost IS '单位成本';
COMMENT ON COLUMN stock_transfer_item.amount IS '金额';
COMMENT ON COLUMN stock_transfer_item.remark IS '备注';
COMMENT ON COLUMN stock_transfer_item.created_by IS '创建人';
COMMENT ON COLUMN stock_transfer_item.created_at IS '创建时间';
COMMENT ON COLUMN stock_transfer_item.updated_by IS '更新人';
COMMENT ON COLUMN stock_transfer_item.updated_at IS '更新时间';
COMMENT ON COLUMN stock_transfer_item.deleted_by IS '删除人';
COMMENT ON COLUMN stock_transfer_item.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_transfer_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_inventory_transfer_item_transfer
    ON stock_transfer_item (tenant_id, transfer_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_transfer_item_product
    ON stock_transfer_item (tenant_id, product_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS stock_init_import_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_no varchar(64) NOT NULL,
    source_name varchar(255),
    import_mode varchar(32) DEFAULT 'EXCEL_UPLOAD' NOT NULL,
    total_count integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    warning_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    summary text,
    raw_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_init_import_batch PRIMARY KEY (id)
);
COMMENT ON TABLE stock_init_import_batch IS '期初库存导入批次。';
COMMENT ON COLUMN stock_init_import_batch.id IS '主键';
COMMENT ON COLUMN stock_init_import_batch.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_init_import_batch.batch_no IS '导入批次号';
COMMENT ON COLUMN stock_init_import_batch.source_name IS '来源文件名';
COMMENT ON COLUMN stock_init_import_batch.import_mode IS '导入模式';
COMMENT ON COLUMN stock_init_import_batch.total_count IS '总数';
COMMENT ON COLUMN stock_init_import_batch.success_count IS '成功数';
COMMENT ON COLUMN stock_init_import_batch.failed_count IS '失败数';
COMMENT ON COLUMN stock_init_import_batch.warning_count IS '警告数';
COMMENT ON COLUMN stock_init_import_batch.status IS '状态';
COMMENT ON COLUMN stock_init_import_batch.summary IS '导入摘要';
COMMENT ON COLUMN stock_init_import_batch.raw_payload IS '原始载荷';
COMMENT ON COLUMN stock_init_import_batch.created_by IS '创建人';
COMMENT ON COLUMN stock_init_import_batch.created_at IS '创建时间';
COMMENT ON COLUMN stock_init_import_batch.updated_by IS '更新人';
COMMENT ON COLUMN stock_init_import_batch.updated_at IS '更新时间';
COMMENT ON COLUMN stock_init_import_batch.deleted_by IS '删除人';
COMMENT ON COLUMN stock_init_import_batch.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_init_import_batch.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_stock_init_i_batch_no_active
    ON stock_init_import_batch (tenant_id, batch_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_stock_init_import_batch_status
    ON stock_init_import_batch (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS stock_init_import_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    row_no integer NOT NULL,
    source_code varchar(128),
    source_name varchar(255),
    matched_target_id bigint,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    error_field varchar(128),
    error_message text,
    warning_message text,
    raw_row jsonb NOT NULL,
    normalized_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_stock_init_import_item PRIMARY KEY (id)
);
COMMENT ON TABLE stock_init_import_item IS '期初库存导入明细。';
COMMENT ON COLUMN stock_init_import_item.id IS '主键';
COMMENT ON COLUMN stock_init_import_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN stock_init_import_item.batch_id IS '导入批次 ID';
COMMENT ON COLUMN stock_init_import_item.row_no IS '行号';
COMMENT ON COLUMN stock_init_import_item.source_code IS '来源编码';
COMMENT ON COLUMN stock_init_import_item.source_name IS '来源名称';
COMMENT ON COLUMN stock_init_import_item.matched_target_id IS '匹配目标 ID';
COMMENT ON COLUMN stock_init_import_item.status IS '状态';
COMMENT ON COLUMN stock_init_import_item.error_field IS '错误字段';
COMMENT ON COLUMN stock_init_import_item.error_message IS '错误信息';
COMMENT ON COLUMN stock_init_import_item.warning_message IS '警告信息';
COMMENT ON COLUMN stock_init_import_item.raw_row IS '原始行';
COMMENT ON COLUMN stock_init_import_item.normalized_payload IS '规范化数据';
COMMENT ON COLUMN stock_init_import_item.created_by IS '创建人';
COMMENT ON COLUMN stock_init_import_item.created_at IS '创建时间';
COMMENT ON COLUMN stock_init_import_item.updated_by IS '更新人';
COMMENT ON COLUMN stock_init_import_item.updated_at IS '更新时间';
COMMENT ON COLUMN stock_init_import_item.deleted_by IS '删除人';
COMMENT ON COLUMN stock_init_import_item.delete_reason IS '删除原因';
COMMENT ON COLUMN stock_init_import_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_stock_init_i_batch_row_active
    ON stock_init_import_item (tenant_id, batch_id, row_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_stock_init_import_item_status
    ON stock_init_import_item (tenant_id, status)
    WHERE deleted_at IS NULL;

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);
