-- xuan-warehouse initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS warehouse (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    address varchar(500),
    manager varchar(100),
    phone varchar(50),
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);
COMMENT ON TABLE warehouse IS '仓库表。';
COMMENT ON COLUMN warehouse.id IS '主键';
COMMENT ON COLUMN warehouse.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN warehouse.code IS '仓库编码';
COMMENT ON COLUMN warehouse.name IS '仓库名称';
COMMENT ON COLUMN warehouse.address IS '地址';
COMMENT ON COLUMN warehouse.manager IS '负责人';
COMMENT ON COLUMN warehouse.phone IS '联系电话';
COMMENT ON COLUMN warehouse.is_enabled IS '是否启用';
COMMENT ON COLUMN warehouse.is_default IS '是否默认仓库';
COMMENT ON COLUMN warehouse.remark IS '备注';
COMMENT ON COLUMN warehouse.created_by IS '创建人';
COMMENT ON COLUMN warehouse.created_at IS '创建时间';
COMMENT ON COLUMN warehouse.updated_by IS '更新人';
COMMENT ON COLUMN warehouse.updated_at IS '更新时间';
COMMENT ON COLUMN warehouse.deleted_by IS '删除人';
COMMENT ON COLUMN warehouse.delete_reason IS '删除原因';
COMMENT ON COLUMN warehouse.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_warehouse_warehouse_code_active
    ON warehouse (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_warehouse_default
    ON warehouse (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_warehouse_name
    ON warehouse (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_warehouse_warehouse_tenant_deleted
    ON warehouse (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS warehouse_location (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200),
    aisle varchar(50),
    rack varchar(50),
    bin varchar(50),
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_warehouse_location PRIMARY KEY (id)
);
COMMENT ON TABLE warehouse_location IS '库位表。';
COMMENT ON COLUMN warehouse_location.id IS '主键';
COMMENT ON COLUMN warehouse_location.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN warehouse_location.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN warehouse_location.code IS '库位编码';
COMMENT ON COLUMN warehouse_location.name IS '库位名称';
COMMENT ON COLUMN warehouse_location.aisle IS '巷道';
COMMENT ON COLUMN warehouse_location.rack IS '货架';
COMMENT ON COLUMN warehouse_location.bin IS '货位';
COMMENT ON COLUMN warehouse_location.is_enabled IS '是否启用';
COMMENT ON COLUMN warehouse_location.is_default IS '是否默认库位';
COMMENT ON COLUMN warehouse_location.remark IS '备注';
COMMENT ON COLUMN warehouse_location.created_by IS '创建人';
COMMENT ON COLUMN warehouse_location.created_at IS '创建时间';
COMMENT ON COLUMN warehouse_location.updated_by IS '更新人';
COMMENT ON COLUMN warehouse_location.updated_at IS '更新时间';
COMMENT ON COLUMN warehouse_location.deleted_by IS '删除人';
COMMENT ON COLUMN warehouse_location.delete_reason IS '删除原因';
COMMENT ON COLUMN warehouse_location.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_warehouse_location_code_active
    ON warehouse_location (tenant_id, warehouse_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_warehouse_location_default
    ON warehouse_location (tenant_id, warehouse_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_warehouse_location_warehouse
    ON warehouse_location (tenant_id, warehouse_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_location_tenant_deleted
    ON warehouse_location (tenant_id, deleted_at);

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- warehouse: 默认仓库。
INSERT INTO warehouse (tenant_id, code, name, address, manager, phone, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, 'DEFAULT', '默认仓库', NULL, NULL, NULL, true, true, 'V1 默认仓库。', 'system', 'system'
WHERE NOT EXISTS (
    SELECT 1
    FROM warehouse existing
    WHERE existing.tenant_id = 1
      AND existing.code = 'DEFAULT'
      AND existing.deleted_at IS NULL
);

-- warehouse_location: 默认仓库下的默认库位。
INSERT INTO warehouse_location (tenant_id, warehouse_id, code, name, aisle, rack, bin, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, warehouse.id, 'DEFAULT_BIN', '默认库位', NULL, NULL, NULL, true, true, 'V1 默认库位。', 'system', 'system'
FROM warehouse
WHERE warehouse.tenant_id = 1
  AND warehouse.code = 'DEFAULT'
  AND warehouse.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM warehouse_location existing
      WHERE existing.tenant_id = 1
        AND existing.warehouse_id = warehouse.id
        AND existing.code = 'DEFAULT_BIN'
        AND existing.deleted_at IS NULL
  );
