-- xuan-query initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS query_event_cursor (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_name varchar(120) NOT NULL,
    topic varchar(120) NOT NULL,
    partition_key varchar(120) DEFAULT 'default' NOT NULL,
    last_event_id varchar(128),
    last_event_at timestamptz,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_query_event_cursor PRIMARY KEY (id)
);
COMMENT ON TABLE query_event_cursor IS '读模型事件消费游标。';
COMMENT ON COLUMN query_event_cursor.id IS '主键';
COMMENT ON COLUMN query_event_cursor.consumer_name IS '消费者名称';
COMMENT ON COLUMN query_event_cursor.topic IS '主题';
COMMENT ON COLUMN query_event_cursor.partition_key IS '分区键';
COMMENT ON COLUMN query_event_cursor.last_event_id IS '最后事件 ID';
COMMENT ON COLUMN query_event_cursor.last_event_at IS '最后事件时间';
COMMENT ON COLUMN query_event_cursor.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_query_event_cursor
    ON query_event_cursor (consumer_name, topic, partition_key);

CREATE TABLE IF NOT EXISTS product_stock_read_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_code varchar(100) NOT NULL,
    product_name varchar(200) NOT NULL,
    category_id bigint,
    category_name varchar(200),
    warehouse_id bigint,
    warehouse_name varchar(200),
    location_id bigint,
    location_name varchar(200),
    qty_on_hand numeric(18,4) DEFAULT 0 NOT NULL,
    qty_reserved numeric(18,4) DEFAULT 0 NOT NULL,
    available_qty numeric(18,4) DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_product_stock_read_model PRIMARY KEY (id)
);
COMMENT ON TABLE product_stock_read_model IS '商品库存聚合读模型。';
COMMENT ON COLUMN product_stock_read_model.id IS '主键';
COMMENT ON COLUMN product_stock_read_model.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_stock_read_model.product_id IS '商品 ID';
COMMENT ON COLUMN product_stock_read_model.product_code IS '商品编码';
COMMENT ON COLUMN product_stock_read_model.product_name IS '商品名称';
COMMENT ON COLUMN product_stock_read_model.category_id IS '分类 ID';
COMMENT ON COLUMN product_stock_read_model.category_name IS '分类名称';
COMMENT ON COLUMN product_stock_read_model.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN product_stock_read_model.warehouse_name IS '仓库名称';
COMMENT ON COLUMN product_stock_read_model.location_id IS '库位 ID';
COMMENT ON COLUMN product_stock_read_model.location_name IS '库位名称';
COMMENT ON COLUMN product_stock_read_model.qty_on_hand IS '当前库存';
COMMENT ON COLUMN product_stock_read_model.qty_reserved IS '锁定库存';
COMMENT ON COLUMN product_stock_read_model.available_qty IS '可用库存';
COMMENT ON COLUMN product_stock_read_model.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_query_product_stock_key
    ON product_stock_read_model (tenant_id, product_id, warehouse_id, COALESCE(location_id, -1));
CREATE INDEX IF NOT EXISTS idx_query_product_stock_search
    ON product_stock_read_model (tenant_id, product_code, product_name);

CREATE TABLE IF NOT EXISTS sale_order_list_read_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_no varchar(64) NOT NULL,
    status varchar(20) NOT NULL,
    order_at timestamptz,
    customer_id bigint,
    customer_name varchar(200),
    total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    paid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    item_count integer DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_sale_order_list_read_model PRIMARY KEY (id)
);
COMMENT ON TABLE sale_order_list_read_model IS '销售单列表读模型。';
COMMENT ON COLUMN sale_order_list_read_model.id IS '主键';
COMMENT ON COLUMN sale_order_list_read_model.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN sale_order_list_read_model.order_id IS '单据 ID';
COMMENT ON COLUMN sale_order_list_read_model.order_no IS '单据号';
COMMENT ON COLUMN sale_order_list_read_model.status IS '状态';
COMMENT ON COLUMN sale_order_list_read_model.order_at IS '单据时间';
COMMENT ON COLUMN sale_order_list_read_model.customer_id IS '往来方 ID';
COMMENT ON COLUMN sale_order_list_read_model.customer_name IS '往来方名称';
COMMENT ON COLUMN sale_order_list_read_model.total_amount IS '总金额';
COMMENT ON COLUMN sale_order_list_read_model.paid_amount IS '已结算金额';
COMMENT ON COLUMN sale_order_list_read_model.discount_amount IS '优惠金额';
COMMENT ON COLUMN sale_order_list_read_model.item_count IS '明细行数';
COMMENT ON COLUMN sale_order_list_read_model.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_query_sale_order_list_read_model_order
    ON sale_order_list_read_model (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS idx_query_sale_order_list_read_model_page
    ON sale_order_list_read_model (tenant_id, status, customer_id, order_at DESC, order_id DESC);

CREATE TABLE IF NOT EXISTS purchase_order_list_read_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_no varchar(64) NOT NULL,
    status varchar(20) NOT NULL,
    order_at timestamptz,
    supplier_id bigint,
    supplier_name varchar(200),
    total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    paid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    item_count integer DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_purchase_order_list_read_model PRIMARY KEY (id)
);
COMMENT ON TABLE purchase_order_list_read_model IS '采购单列表读模型。';
COMMENT ON COLUMN purchase_order_list_read_model.id IS '主键';
COMMENT ON COLUMN purchase_order_list_read_model.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN purchase_order_list_read_model.order_id IS '单据 ID';
COMMENT ON COLUMN purchase_order_list_read_model.order_no IS '单据号';
COMMENT ON COLUMN purchase_order_list_read_model.status IS '状态';
COMMENT ON COLUMN purchase_order_list_read_model.order_at IS '单据时间';
COMMENT ON COLUMN purchase_order_list_read_model.supplier_id IS '往来方 ID';
COMMENT ON COLUMN purchase_order_list_read_model.supplier_name IS '往来方名称';
COMMENT ON COLUMN purchase_order_list_read_model.total_amount IS '总金额';
COMMENT ON COLUMN purchase_order_list_read_model.paid_amount IS '已结算金额';
COMMENT ON COLUMN purchase_order_list_read_model.discount_amount IS '优惠金额';
COMMENT ON COLUMN purchase_order_list_read_model.item_count IS '明细行数';
COMMENT ON COLUMN purchase_order_list_read_model.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_query_purchase_order_list_read_model_order
    ON purchase_order_list_read_model (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS idx_query_purchase_order_list_read_model_page
    ON purchase_order_list_read_model (tenant_id, status, supplier_id, order_at DESC, order_id DESC);

CREATE TABLE IF NOT EXISTS counterparty_finance_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    subject_name varchar(200) NOT NULL,
    receivable_total numeric(18,2) DEFAULT 0 NOT NULL,
    payable_total numeric(18,2) DEFAULT 0 NOT NULL,
    net_amount numeric(18,2) DEFAULT 0 NOT NULL,
    customer_count bigint DEFAULT 0 NOT NULL,
    supplier_count bigint DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_counterparty_finance_summary PRIMARY KEY (id)
);
COMMENT ON TABLE counterparty_finance_summary IS '往来主体财务汇总读模型。';
COMMENT ON COLUMN counterparty_finance_summary.id IS '主键';
COMMENT ON COLUMN counterparty_finance_summary.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN counterparty_finance_summary.subject_id IS '往来主体 ID';
COMMENT ON COLUMN counterparty_finance_summary.subject_name IS '往来主体名称';
COMMENT ON COLUMN counterparty_finance_summary.receivable_total IS '应收总额';
COMMENT ON COLUMN counterparty_finance_summary.payable_total IS '应付总额';
COMMENT ON COLUMN counterparty_finance_summary.net_amount IS '净额';
COMMENT ON COLUMN counterparty_finance_summary.customer_count IS '客户数量';
COMMENT ON COLUMN counterparty_finance_summary.supplier_count IS '供应商数量';
COMMENT ON COLUMN counterparty_finance_summary.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_query_counterparty_finance
    ON counterparty_finance_summary (tenant_id, subject_id);

CREATE TABLE IF NOT EXISTS inventory_summary_read_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    warehouse_id bigint,
    warehouse_name varchar(200),
    category_id bigint,
    category_name varchar(200),
    product_count bigint DEFAULT 0 NOT NULL,
    qty_on_hand numeric(18,4) DEFAULT 0 NOT NULL,
    qty_reserved numeric(18,4) DEFAULT 0 NOT NULL,
    available_qty numeric(18,4) DEFAULT 0 NOT NULL,
    stock_amount numeric(18,2) DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_inventory_summary_read_model PRIMARY KEY (id)
);
COMMENT ON TABLE inventory_summary_read_model IS '库存汇总报表读模型。';
COMMENT ON COLUMN inventory_summary_read_model.id IS '主键';
COMMENT ON COLUMN inventory_summary_read_model.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN inventory_summary_read_model.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN inventory_summary_read_model.warehouse_name IS '仓库名称';
COMMENT ON COLUMN inventory_summary_read_model.category_id IS '分类 ID';
COMMENT ON COLUMN inventory_summary_read_model.category_name IS '分类名称';
COMMENT ON COLUMN inventory_summary_read_model.product_count IS '商品数';
COMMENT ON COLUMN inventory_summary_read_model.qty_on_hand IS '当前库存';
COMMENT ON COLUMN inventory_summary_read_model.qty_reserved IS '锁定库存';
COMMENT ON COLUMN inventory_summary_read_model.available_qty IS '可用库存';
COMMENT ON COLUMN inventory_summary_read_model.stock_amount IS '库存金额';
COMMENT ON COLUMN inventory_summary_read_model.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_query_inventory_summary
    ON inventory_summary_read_model (tenant_id, COALESCE(warehouse_id, -1), COALESCE(category_id, -1));

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);
