-- xuan-procurement initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS purchase_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_no varchar(64) NOT NULL,
    status varchar(20) DEFAULT 'DRAFT' NOT NULL,
    order_at timestamptz,
    total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    total_amount_excl_tax numeric(18,2) DEFAULT 0 NOT NULL,
    total_tax_amount numeric(18,2) DEFAULT 0 NOT NULL,
    total_amount_incl_tax numeric(18,2) DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    approved_by varchar(100),
    approved_at timestamptz,
    cancelled_by varchar(100),
    cancelled_at timestamptz,
    red_flush_source_type varchar(50),
    red_flush_source_id bigint,
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    supplier_id bigint,
    supplier_code_snapshot varchar(100),
    supplier_name_snapshot varchar(200),
    paid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    settlement_method_code varchar(100),
    payment_method_code varchar(100),
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_purchase_order PRIMARY KEY (id)
);
COMMENT ON TABLE purchase_order IS '采购单头表。';
COMMENT ON COLUMN purchase_order.id IS '主键';
COMMENT ON COLUMN purchase_order.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN purchase_order.order_no IS '采购单号';
COMMENT ON COLUMN purchase_order.status IS '状态';
COMMENT ON COLUMN purchase_order.order_at IS '单据时间';
COMMENT ON COLUMN purchase_order.total_amount IS '总金额';
COMMENT ON COLUMN purchase_order.total_amount_excl_tax IS '未税总金额';
COMMENT ON COLUMN purchase_order.total_tax_amount IS '税额合计';
COMMENT ON COLUMN purchase_order.total_amount_incl_tax IS '含税总金额';
COMMENT ON COLUMN purchase_order.version IS '乐观锁版本';
COMMENT ON COLUMN purchase_order.approved_by IS '审核人';
COMMENT ON COLUMN purchase_order.approved_at IS '审核时间';
COMMENT ON COLUMN purchase_order.cancelled_by IS '作废人';
COMMENT ON COLUMN purchase_order.cancelled_at IS '作废时间';
COMMENT ON COLUMN purchase_order.red_flush_source_type IS '红冲来源类型';
COMMENT ON COLUMN purchase_order.red_flush_source_id IS '红冲来源单据 ID';
COMMENT ON COLUMN purchase_order.print_count IS '打印次数';
COMMENT ON COLUMN purchase_order.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN purchase_order.supplier_id IS '供应商 ID';
COMMENT ON COLUMN purchase_order.supplier_code_snapshot IS '供应商编码快照';
COMMENT ON COLUMN purchase_order.supplier_name_snapshot IS '供应商名称快照';
COMMENT ON COLUMN purchase_order.paid_amount IS '已付金额';
COMMENT ON COLUMN purchase_order.discount_amount IS '优惠金额';
COMMENT ON COLUMN purchase_order.settlement_method_code IS '结算方式编码';
COMMENT ON COLUMN purchase_order.payment_method_code IS '付款方式编码';
COMMENT ON COLUMN purchase_order.remark IS '备注';
COMMENT ON COLUMN purchase_order.created_by IS '创建人';
COMMENT ON COLUMN purchase_order.created_at IS '创建时间';
COMMENT ON COLUMN purchase_order.updated_by IS '更新人';
COMMENT ON COLUMN purchase_order.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_order.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_order.delete_reason IS '删除原因';
COMMENT ON COLUMN purchase_order.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_purchase_ord_purchase_order_no_active
    ON purchase_order (tenant_id, order_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_order_status
    ON purchase_order (tenant_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_ord_purchase_order_tenant_deleted
    ON purchase_order (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS purchase_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_id bigint NOT NULL,
    line_no integer DEFAULT 1 NOT NULL,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    warehouse_name_snapshot varchar(200),
    location_id bigint,
    location_name_snapshot varchar(200),
    qty numeric(18,4) NOT NULL,
    price numeric(18,4) DEFAULT 0 NOT NULL,
    price_incl_tax numeric(18,4) DEFAULT 0 NOT NULL,
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    amount_incl_tax numeric(18,2) DEFAULT 0 NOT NULL,
    tax_rate numeric(10,4) DEFAULT 0 NOT NULL,
    tax_amount numeric(18,2) DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_purchase_order_item PRIMARY KEY (id)
);
COMMENT ON TABLE purchase_order_item IS '采购单明细表。';
COMMENT ON COLUMN purchase_order_item.id IS '主键';
COMMENT ON COLUMN purchase_order_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN purchase_order_item.order_id IS '主单 ID';
COMMENT ON COLUMN purchase_order_item.line_no IS '行号';
COMMENT ON COLUMN purchase_order_item.product_id IS '商品 ID';
COMMENT ON COLUMN purchase_order_item.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN purchase_order_item.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN purchase_order_item.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN purchase_order_item.warehouse_name_snapshot IS '仓库名称快照';
COMMENT ON COLUMN purchase_order_item.location_id IS '库位 ID';
COMMENT ON COLUMN purchase_order_item.location_name_snapshot IS '库位名称快照';
COMMENT ON COLUMN purchase_order_item.qty IS '数量';
COMMENT ON COLUMN purchase_order_item.price IS '单价';
COMMENT ON COLUMN purchase_order_item.price_incl_tax IS '含税单价';
COMMENT ON COLUMN purchase_order_item.amount IS '金额';
COMMENT ON COLUMN purchase_order_item.amount_incl_tax IS '含税金额';
COMMENT ON COLUMN purchase_order_item.tax_rate IS '税率';
COMMENT ON COLUMN purchase_order_item.tax_amount IS '税额';
COMMENT ON COLUMN purchase_order_item.remark IS '备注';
COMMENT ON COLUMN purchase_order_item.created_by IS '创建人';
COMMENT ON COLUMN purchase_order_item.created_at IS '创建时间';
COMMENT ON COLUMN purchase_order_item.updated_by IS '更新人';
COMMENT ON COLUMN purchase_order_item.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_order_item.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_order_item.delete_reason IS '删除原因';
COMMENT ON COLUMN purchase_order_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_parent
    ON purchase_order_item (tenant_id, order_id, line_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_product
    ON purchase_order_item (tenant_id, product_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS purchase_return (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_no varchar(64) NOT NULL,
    status varchar(20) DEFAULT 'DRAFT' NOT NULL,
    order_at timestamptz,
    total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    total_amount_excl_tax numeric(18,2) DEFAULT 0 NOT NULL,
    total_tax_amount numeric(18,2) DEFAULT 0 NOT NULL,
    total_amount_incl_tax numeric(18,2) DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    approved_by varchar(100),
    approved_at timestamptz,
    cancelled_by varchar(100),
    cancelled_at timestamptz,
    red_flush_source_type varchar(50),
    red_flush_source_id bigint,
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    return_type varchar(20) DEFAULT 'RETURN' NOT NULL,
    supplier_id bigint,
    supplier_name_snapshot varchar(200),
    purchase_order_id bigint,
    paid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    inventory_reserved boolean DEFAULT false NOT NULL,
    settlement_method_code varchar(100),
    payment_method_code varchar(100),
    refund_action varchar(20) DEFAULT 'OFFSET_AP' NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_purchase_return PRIMARY KEY (id)
);
COMMENT ON TABLE purchase_return IS '采购退货单。';
COMMENT ON COLUMN purchase_return.id IS '主键';
COMMENT ON COLUMN purchase_return.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN purchase_return.order_no IS '退货单号';
COMMENT ON COLUMN purchase_return.status IS '状态';
COMMENT ON COLUMN purchase_return.order_at IS '单据时间';
COMMENT ON COLUMN purchase_return.total_amount IS '总金额';
COMMENT ON COLUMN purchase_return.total_amount_excl_tax IS '未税总金额';
COMMENT ON COLUMN purchase_return.total_tax_amount IS '税额合计';
COMMENT ON COLUMN purchase_return.total_amount_incl_tax IS '含税总金额';
COMMENT ON COLUMN purchase_return.version IS '乐观锁版本';
COMMENT ON COLUMN purchase_return.approved_by IS '审核人';
COMMENT ON COLUMN purchase_return.approved_at IS '审核时间';
COMMENT ON COLUMN purchase_return.cancelled_by IS '作废人';
COMMENT ON COLUMN purchase_return.cancelled_at IS '作废时间';
COMMENT ON COLUMN purchase_return.red_flush_source_type IS '红冲来源类型';
COMMENT ON COLUMN purchase_return.red_flush_source_id IS '红冲来源单据 ID';
COMMENT ON COLUMN purchase_return.print_count IS '打印次数';
COMMENT ON COLUMN purchase_return.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN purchase_return.return_type IS '退货处理方式';
COMMENT ON COLUMN purchase_return.supplier_id IS '供应商 ID';
COMMENT ON COLUMN purchase_return.supplier_name_snapshot IS '供应商名称快照';
COMMENT ON COLUMN purchase_return.purchase_order_id IS '来源采购单 ID';
COMMENT ON COLUMN purchase_return.paid_amount IS '已付金额';
COMMENT ON COLUMN purchase_return.discount_amount IS '优惠金额';
COMMENT ON COLUMN purchase_return.inventory_reserved IS '草稿是否已占用库存';
COMMENT ON COLUMN purchase_return.settlement_method_code IS '结算方式编码';
COMMENT ON COLUMN purchase_return.payment_method_code IS '付款方式编码';
COMMENT ON COLUMN purchase_return.refund_action IS '退款处理方式';
COMMENT ON COLUMN purchase_return.remark IS '备注';
COMMENT ON COLUMN purchase_return.created_by IS '创建人';
COMMENT ON COLUMN purchase_return.created_at IS '创建时间';
COMMENT ON COLUMN purchase_return.updated_by IS '更新人';
COMMENT ON COLUMN purchase_return.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_return.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_return.delete_reason IS '删除原因';
COMMENT ON COLUMN purchase_return.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_purchase_ret_purchase_return_no_active
    ON purchase_return (tenant_id, order_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_return_status
    ON purchase_return (tenant_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_ret_purchase_return_tenant_deleted
    ON purchase_return (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS purchase_return_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    return_id bigint NOT NULL,
    line_no integer DEFAULT 1 NOT NULL,
    product_id bigint NOT NULL,
    product_code_snapshot varchar(100),
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    warehouse_name_snapshot varchar(200),
    location_id bigint,
    location_name_snapshot varchar(200),
    qty numeric(18,4) NOT NULL,
    price numeric(18,4) DEFAULT 0 NOT NULL,
    price_incl_tax numeric(18,4) DEFAULT 0 NOT NULL,
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    amount_incl_tax numeric(18,2) DEFAULT 0 NOT NULL,
    tax_rate numeric(10,4) DEFAULT 0 NOT NULL,
    tax_amount numeric(18,2) DEFAULT 0 NOT NULL,
    source_purchase_order_item_id bigint,
    source_purchase_order_id bigint,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_purchase_return_item PRIMARY KEY (id)
);
COMMENT ON TABLE purchase_return_item IS '采购退货明细表。';
COMMENT ON COLUMN purchase_return_item.id IS '主键';
COMMENT ON COLUMN purchase_return_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN purchase_return_item.return_id IS '主单 ID';
COMMENT ON COLUMN purchase_return_item.line_no IS '行号';
COMMENT ON COLUMN purchase_return_item.product_id IS '商品 ID';
COMMENT ON COLUMN purchase_return_item.product_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN purchase_return_item.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN purchase_return_item.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN purchase_return_item.warehouse_name_snapshot IS '仓库名称快照';
COMMENT ON COLUMN purchase_return_item.location_id IS '库位 ID';
COMMENT ON COLUMN purchase_return_item.location_name_snapshot IS '库位名称快照';
COMMENT ON COLUMN purchase_return_item.qty IS '数量';
COMMENT ON COLUMN purchase_return_item.price IS '单价';
COMMENT ON COLUMN purchase_return_item.price_incl_tax IS '含税单价';
COMMENT ON COLUMN purchase_return_item.amount IS '金额';
COMMENT ON COLUMN purchase_return_item.amount_incl_tax IS '含税金额';
COMMENT ON COLUMN purchase_return_item.tax_rate IS '税率';
COMMENT ON COLUMN purchase_return_item.tax_amount IS '税额';
COMMENT ON COLUMN purchase_return_item.source_purchase_order_item_id IS '来源采购单明细 ID';
COMMENT ON COLUMN purchase_return_item.source_purchase_order_id IS '来源采购单 ID';
COMMENT ON COLUMN purchase_return_item.remark IS '备注';
COMMENT ON COLUMN purchase_return_item.created_by IS '创建人';
COMMENT ON COLUMN purchase_return_item.created_at IS '创建时间';
COMMENT ON COLUMN purchase_return_item.updated_by IS '更新人';
COMMENT ON COLUMN purchase_return_item.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_return_item.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_return_item.delete_reason IS '删除原因';
COMMENT ON COLUMN purchase_return_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_purchase_return_item_parent
    ON purchase_return_item (tenant_id, return_id, line_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_return_item_product
    ON purchase_return_item (tenant_id, product_id)
    WHERE deleted_at IS NULL;

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);
