-- xuan-document initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS print_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(64) NOT NULL,
    name varchar(100) NOT NULL,
    doc_type varchar(50) NOT NULL,
    header_title varchar(120),
    sub_title varchar(120),
    footer_note varchar(500),
    field_config jsonb,
    sort_no integer DEFAULT 0 NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_print_template PRIMARY KEY (id)
);
COMMENT ON TABLE print_template IS '打印模板配置表。';
COMMENT ON COLUMN print_template.id IS '主键';
COMMENT ON COLUMN print_template.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN print_template.code IS '模板编码';
COMMENT ON COLUMN print_template.name IS '模板名称';
COMMENT ON COLUMN print_template.doc_type IS '单据类型';
COMMENT ON COLUMN print_template.header_title IS '标题';
COMMENT ON COLUMN print_template.sub_title IS '副标题';
COMMENT ON COLUMN print_template.footer_note IS '页脚备注';
COMMENT ON COLUMN print_template.field_config IS '字段配置';
COMMENT ON COLUMN print_template.sort_no IS '排序';
COMMENT ON COLUMN print_template.is_default IS '是否默认';
COMMENT ON COLUMN print_template.is_enabled IS '是否启用';
COMMENT ON COLUMN print_template.remark IS '备注';
COMMENT ON COLUMN print_template.created_by IS '创建人';
COMMENT ON COLUMN print_template.created_at IS '创建时间';
COMMENT ON COLUMN print_template.updated_by IS '更新人';
COMMENT ON COLUMN print_template.updated_at IS '更新时间';
COMMENT ON COLUMN print_template.deleted_by IS '删除人';
COMMENT ON COLUMN print_template.delete_reason IS '删除原因';
COMMENT ON COLUMN print_template.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_document_template_code_active
    ON print_template (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_document_template_default
    ON print_template (tenant_id, doc_type)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_document_template_doc
    ON print_template (tenant_id, doc_type, is_enabled, sort_no);

CREATE TABLE IF NOT EXISTS print_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    doc_type varchar(50) NOT NULL,
    doc_id bigint NOT NULL,
    doc_no varchar(64),
    template_id bigint,
    printed_by varchar(100),
    printed_at timestamptz DEFAULT now() NOT NULL,
    client_ip varchar(64),
    user_agent varchar(255),
    CONSTRAINT pk_print_log PRIMARY KEY (id)
);
COMMENT ON TABLE print_log IS '打印日志表。';
COMMENT ON COLUMN print_log.id IS '主键';
COMMENT ON COLUMN print_log.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN print_log.doc_type IS '单据类型';
COMMENT ON COLUMN print_log.doc_id IS '单据 ID';
COMMENT ON COLUMN print_log.doc_no IS '单据编号';
COMMENT ON COLUMN print_log.template_id IS '模板 ID';
COMMENT ON COLUMN print_log.printed_by IS '打印人';
COMMENT ON COLUMN print_log.printed_at IS '打印时间';
COMMENT ON COLUMN print_log.client_ip IS '客户端 IP';
COMMENT ON COLUMN print_log.user_agent IS '客户端 UA';
CREATE INDEX IF NOT EXISTS idx_document_print_log_doc
    ON print_log (tenant_id, doc_type, doc_id);
CREATE INDEX IF NOT EXISTS idx_document_print_log_time
    ON print_log (tenant_id, printed_at DESC);

CREATE TABLE IF NOT EXISTS print_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    doc_type varchar(50) NOT NULL,
    doc_id bigint NOT NULL,
    doc_no varchar(64),
    template_id bigint,
    snapshot_json jsonb NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_print_snapshot PRIMARY KEY (id)
);
COMMENT ON TABLE print_snapshot IS '打印快照表，保存打印时的单据数据。';
COMMENT ON COLUMN print_snapshot.id IS '主键';
COMMENT ON COLUMN print_snapshot.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN print_snapshot.doc_type IS '单据类型';
COMMENT ON COLUMN print_snapshot.doc_id IS '单据 ID';
COMMENT ON COLUMN print_snapshot.doc_no IS '单据编号';
COMMENT ON COLUMN print_snapshot.template_id IS '模板 ID';
COMMENT ON COLUMN print_snapshot.snapshot_json IS '打印快照 JSON';
COMMENT ON COLUMN print_snapshot.created_by IS '创建人';
COMMENT ON COLUMN print_snapshot.created_at IS '创建时间';
CREATE INDEX IF NOT EXISTS idx_document_print_snapshot_doc
    ON print_snapshot (tenant_id, doc_type, doc_id, created_at DESC);

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- print_template: 常用单据默认打印模板，字段配置先保持空 JSON，由后续模板设计补充。
INSERT INTO print_template (tenant_id, code, name, doc_type, header_title, sub_title, footer_note, field_config, sort_no, is_default, is_enabled, remark, created_by, updated_by)
SELECT 1, seed.code, seed.name, seed.doc_type, seed.header_title, seed.sub_title, seed.footer_note, seed.field_config, seed.sort_no, seed.is_default, seed.is_enabled, seed.remark, 'system', 'system'
FROM (
    VALUES
        ('TPL_SALE_ORDER', '销售单默认模板', 'SALE_ORDER', '销售单', NULL, '请核对商品、数量和金额。', '{}'::jsonb, 10, true, true, 'V1 默认模板。'),
        ('TPL_PURCHASE_ORDER', '采购单默认模板', 'PURCHASE_ORDER', '采购单', NULL, '请核对商品、数量和金额。', '{}'::jsonb, 20, true, true, 'V1 默认模板。'),
        ('TPL_SALE_RETURN', '销售退货默认模板', 'SALE_RETURN', '销售退货单', NULL, '请核对退货商品和金额。', '{}'::jsonb, 30, true, true, 'V1 默认模板。'),
        ('TPL_PURCHASE_RETURN', '采购退货默认模板', 'PURCHASE_RETURN', '采购退货单', NULL, '请核对退货商品和金额。', '{}'::jsonb, 40, true, true, 'V1 默认模板。'),
        ('TPL_RECEIPT', '收款单默认模板', 'RECEIPT', '收款单', NULL, '请核对收款金额。', '{}'::jsonb, 50, true, true, 'V1 默认模板。'),
        ('TPL_PAYMENT', '付款单默认模板', 'PAYMENT', '付款单', NULL, '请核对付款金额。', '{}'::jsonb, 60, true, true, 'V1 默认模板。'),
        ('TPL_STOCK_COUNT', '盘点单默认模板', 'STOCK_COUNT', '库存盘点单', NULL, '请核对盘点数量。', '{}'::jsonb, 70, true, true, 'V1 默认模板。'),
        ('TPL_STOCK_TRANSFER', '移库单默认模板', 'STOCK_TRANSFER', '库存移库单', NULL, '请核对移出和移入库位。', '{}'::jsonb, 80, true, true, 'V1 默认模板。'),
        ('TPL_ASSEMBLY_ORDER', '组装拆分单默认模板', 'ASSEMBLY_ORDER', '组装/拆分单', NULL, '请核对子件和成品数量。', '{}'::jsonb, 90, true, true, 'V1 默认模板。')
) AS seed(code, name, doc_type, header_title, sub_title, footer_note, field_config, sort_no, is_default, is_enabled, remark)
WHERE NOT EXISTS (
    SELECT 1
    FROM print_template existing
    WHERE existing.tenant_id = 1
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);
