server:
  port: 8112

spring:
  profiles:
    default: dev
  application:
    name: xuan-audit

management:
  endpoints:
    web:
      exposure:
        include: health,info

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

xuan:
  audit:
    observability:
      skywalking-oap-http-url: http://duaoyunxuan.top:9051
      postgresql-jdbc-url-template: jdbc:postgresql://duaoyunxuan.top:9042/%s
      postgresql-username: ${XUAN_OBSERVABILITY_PG_USERNAME:}
      postgresql-password: ${XUAN_OBSERVABILITY_PG_PASSWORD:}
