-- xuan-manufacturing initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS assembly_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    template_type varchar(20) DEFAULT 'ASSEMBLY' NOT NULL,
    finished_product_id bigint NOT NULL,
    finished_product_name_snapshot varchar(200),
    warehouse_id bigint,
    location_id bigint,
    qty numeric(18,4) DEFAULT 1 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_assembly_template PRIMARY KEY (id)
);
COMMENT ON TABLE assembly_template IS '组装/拆分业务模板。';
COMMENT ON COLUMN assembly_template.id IS '主键';
COMMENT ON COLUMN assembly_template.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN assembly_template.code IS '模板编码';
COMMENT ON COLUMN assembly_template.name IS '模板名称';
COMMENT ON COLUMN assembly_template.template_type IS '模板类型';
COMMENT ON COLUMN assembly_template.finished_product_id IS '成品商品 ID';
COMMENT ON COLUMN assembly_template.finished_product_name_snapshot IS '成品商品名称快照';
COMMENT ON COLUMN assembly_template.warehouse_id IS '默认仓库 ID';
COMMENT ON COLUMN assembly_template.location_id IS '默认库位 ID';
COMMENT ON COLUMN assembly_template.qty IS '成品数量';
COMMENT ON COLUMN assembly_template.is_enabled IS '是否启用';
COMMENT ON COLUMN assembly_template.remark IS '备注';
COMMENT ON COLUMN assembly_template.created_by IS '创建人';
COMMENT ON COLUMN assembly_template.created_at IS '创建时间';
COMMENT ON COLUMN assembly_template.updated_by IS '更新人';
COMMENT ON COLUMN assembly_template.updated_at IS '更新时间';
COMMENT ON COLUMN assembly_template.deleted_by IS '删除人';
COMMENT ON COLUMN assembly_template.delete_reason IS '删除原因';
COMMENT ON COLUMN assembly_template.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_manufacturing_template_code_active
    ON assembly_template (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_manufacturing_template_tenant_deleted
    ON assembly_template (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS assembly_template_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    template_id bigint NOT NULL,
    line_no integer DEFAULT 1 NOT NULL,
    product_id bigint NOT NULL,
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    location_id bigint,
    qty numeric(18,4) DEFAULT 1 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_assembly_template_item PRIMARY KEY (id)
);
COMMENT ON TABLE assembly_template_item IS '组装/拆分模板明细。';
COMMENT ON COLUMN assembly_template_item.id IS '主键';
COMMENT ON COLUMN assembly_template_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN assembly_template_item.template_id IS '模板 ID';
COMMENT ON COLUMN assembly_template_item.line_no IS '行号';
COMMENT ON COLUMN assembly_template_item.product_id IS '子件商品 ID';
COMMENT ON COLUMN assembly_template_item.product_name_snapshot IS '子件商品名称快照';
COMMENT ON COLUMN assembly_template_item.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN assembly_template_item.location_id IS '库位 ID';
COMMENT ON COLUMN assembly_template_item.qty IS '数量';
COMMENT ON COLUMN assembly_template_item.remark IS '备注';
COMMENT ON COLUMN assembly_template_item.created_by IS '创建人';
COMMENT ON COLUMN assembly_template_item.created_at IS '创建时间';
COMMENT ON COLUMN assembly_template_item.updated_by IS '更新人';
COMMENT ON COLUMN assembly_template_item.updated_at IS '更新时间';
COMMENT ON COLUMN assembly_template_item.deleted_by IS '删除人';
COMMENT ON COLUMN assembly_template_item.delete_reason IS '删除原因';
COMMENT ON COLUMN assembly_template_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_mfg_template_item_template
    ON assembly_template_item (tenant_id, template_id, line_no)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS assembly_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_no varchar(64) NOT NULL,
    order_type varchar(20) DEFAULT 'ASSEMBLY' NOT NULL,
    status varchar(20) DEFAULT 'DRAFT' NOT NULL,
    template_id bigint,
    finished_product_id bigint NOT NULL,
    finished_product_name_snapshot varchar(200),
    warehouse_id bigint,
    location_id bigint,
    qty numeric(18,4) DEFAULT 0 NOT NULL,
    approved_by varchar(100),
    approved_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_assembly_order PRIMARY KEY (id)
);
COMMENT ON TABLE assembly_order IS '商品组装/拆分单。';
COMMENT ON COLUMN assembly_order.id IS '主键';
COMMENT ON COLUMN assembly_order.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN assembly_order.order_no IS '单号';
COMMENT ON COLUMN assembly_order.order_type IS '单据类型';
COMMENT ON COLUMN assembly_order.status IS '状态';
COMMENT ON COLUMN assembly_order.template_id IS '模板 ID';
COMMENT ON COLUMN assembly_order.finished_product_id IS '成品商品 ID';
COMMENT ON COLUMN assembly_order.finished_product_name_snapshot IS '成品商品名称快照';
COMMENT ON COLUMN assembly_order.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN assembly_order.location_id IS '库位 ID';
COMMENT ON COLUMN assembly_order.qty IS '成品数量';
COMMENT ON COLUMN assembly_order.approved_by IS '审核人';
COMMENT ON COLUMN assembly_order.approved_at IS '审核时间';
COMMENT ON COLUMN assembly_order.remark IS '备注';
COMMENT ON COLUMN assembly_order.created_by IS '创建人';
COMMENT ON COLUMN assembly_order.created_at IS '创建时间';
COMMENT ON COLUMN assembly_order.updated_by IS '更新人';
COMMENT ON COLUMN assembly_order.updated_at IS '更新时间';
COMMENT ON COLUMN assembly_order.deleted_by IS '删除人';
COMMENT ON COLUMN assembly_order.delete_reason IS '删除原因';
COMMENT ON COLUMN assembly_order.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_manufacturing_order_no_active
    ON assembly_order (tenant_id, order_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_mfg_order_status
    ON assembly_order (tenant_id, status, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS assembly_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    order_id bigint NOT NULL,
    line_no integer DEFAULT 1 NOT NULL,
    product_id bigint NOT NULL,
    product_name_snapshot varchar(200),
    warehouse_id bigint,
    location_id bigint,
    qty numeric(18,4) DEFAULT 0 NOT NULL,
    unit_cost numeric(18,4) DEFAULT 0 NOT NULL,
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_assembly_order_item PRIMARY KEY (id)
);
COMMENT ON TABLE assembly_order_item IS '商品组装/拆分明细。';
COMMENT ON COLUMN assembly_order_item.id IS '主键';
COMMENT ON COLUMN assembly_order_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN assembly_order_item.order_id IS '组装/拆分单 ID';
COMMENT ON COLUMN assembly_order_item.line_no IS '行号';
COMMENT ON COLUMN assembly_order_item.product_id IS '商品 ID';
COMMENT ON COLUMN assembly_order_item.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN assembly_order_item.warehouse_id IS '仓库 ID';
COMMENT ON COLUMN assembly_order_item.location_id IS '库位 ID';
COMMENT ON COLUMN assembly_order_item.qty IS '数量';
COMMENT ON COLUMN assembly_order_item.unit_cost IS '单位成本';
COMMENT ON COLUMN assembly_order_item.amount IS '金额';
COMMENT ON COLUMN assembly_order_item.remark IS '备注';
COMMENT ON COLUMN assembly_order_item.created_by IS '创建人';
COMMENT ON COLUMN assembly_order_item.created_at IS '创建时间';
COMMENT ON COLUMN assembly_order_item.updated_by IS '更新人';
COMMENT ON COLUMN assembly_order_item.updated_at IS '更新时间';
COMMENT ON COLUMN assembly_order_item.deleted_by IS '删除人';
COMMENT ON COLUMN assembly_order_item.delete_reason IS '删除原因';
COMMENT ON COLUMN assembly_order_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_mfg_order_item_order
    ON assembly_order_item (tenant_id, order_id, line_no)
    WHERE deleted_at IS NULL;

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);
