-- xuan-iam initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS iam_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    username varchar(100) NOT NULL,
    password_hash varchar(255) NOT NULL,
    display_name varchar(200),
    email varchar(200),
    phone varchar(50),
    avatar_url varchar(500),
    is_enabled boolean DEFAULT true NOT NULL,
    account_non_expired boolean DEFAULT true NOT NULL,
    account_non_locked boolean DEFAULT true NOT NULL,
    credentials_non_expired boolean DEFAULT true NOT NULL,
    last_login_at timestamptz,
    password_changed_at timestamptz,
    failed_login_count integer DEFAULT 0 NOT NULL,
    last_failed_login_at timestamptz,
    locked_until timestamptz,
    mfa_enabled boolean DEFAULT false NOT NULL,
    auth_version bigint DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_user PRIMARY KEY (id)
);
COMMENT ON TABLE iam_user IS '用户账号表。';
COMMENT ON COLUMN iam_user.id IS '主键';
COMMENT ON COLUMN iam_user.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_user.username IS '用户名';
COMMENT ON COLUMN iam_user.password_hash IS '密码哈希';
COMMENT ON COLUMN iam_user.display_name IS '显示名';
COMMENT ON COLUMN iam_user.email IS '邮箱';
COMMENT ON COLUMN iam_user.phone IS '手机号';
COMMENT ON COLUMN iam_user.avatar_url IS '头像 URL';
COMMENT ON COLUMN iam_user.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_user.account_non_expired IS '账号是否未过期';
COMMENT ON COLUMN iam_user.account_non_locked IS '账号是否未锁定';
COMMENT ON COLUMN iam_user.credentials_non_expired IS '凭证是否未过期';
COMMENT ON COLUMN iam_user.last_login_at IS '最近登录时间';
COMMENT ON COLUMN iam_user.password_changed_at IS '最近密码修改时间';
COMMENT ON COLUMN iam_user.failed_login_count IS '连续登录失败次数';
COMMENT ON COLUMN iam_user.last_failed_login_at IS '最近登录失败时间';
COMMENT ON COLUMN iam_user.locked_until IS '锁定截止时间';
COMMENT ON COLUMN iam_user.mfa_enabled IS '是否启用多因素认证';
COMMENT ON COLUMN iam_user.auth_version IS '权限版本';
COMMENT ON COLUMN iam_user.remark IS '备注';
COMMENT ON COLUMN iam_user.created_by IS '创建人';
COMMENT ON COLUMN iam_user.created_at IS '创建时间';
COMMENT ON COLUMN iam_user.updated_by IS '更新人';
COMMENT ON COLUMN iam_user.updated_at IS '更新时间';
COMMENT ON COLUMN iam_user.deleted_by IS '删除人';
COMMENT ON COLUMN iam_user.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_user.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_username_active
    ON iam_user (tenant_id, username)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_user_tenant_deleted
    ON iam_user (tenant_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_iam_user_phone
    ON iam_user (tenant_id, phone);

CREATE TABLE IF NOT EXISTS iam_user_tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    user_type varchar(40) DEFAULT 'TENANT_USER' NOT NULL,
    membership_status varchar(30) DEFAULT 'ACTIVE' NOT NULL,
    is_tenant_admin boolean DEFAULT false NOT NULL,
    joined_at timestamptz DEFAULT now() NOT NULL,
    last_selected_at timestamptz,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_user_tenant PRIMARY KEY (id)
);
COMMENT ON TABLE iam_user_tenant IS '用户租户关系表，租户内账号模型下记录账号在当前租户内的成员身份。';
COMMENT ON COLUMN iam_user_tenant.id IS '主键';
COMMENT ON COLUMN iam_user_tenant.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_user_tenant.user_id IS '用户 ID';
COMMENT ON COLUMN iam_user_tenant.user_type IS '用户类型：TENANT_USER/PLATFORM_ADMIN';
COMMENT ON COLUMN iam_user_tenant.membership_status IS '成员状态：ACTIVE/SUSPENDED/LEFT';
COMMENT ON COLUMN iam_user_tenant.is_tenant_admin IS '是否租户管理员';
COMMENT ON COLUMN iam_user_tenant.joined_at IS '加入租户时间';
COMMENT ON COLUMN iam_user_tenant.last_selected_at IS '最近选择该租户时间';
COMMENT ON COLUMN iam_user_tenant.created_by IS '创建人';
COMMENT ON COLUMN iam_user_tenant.created_at IS '创建时间';
COMMENT ON COLUMN iam_user_tenant.updated_by IS '更新人';
COMMENT ON COLUMN iam_user_tenant.updated_at IS '更新时间';
COMMENT ON COLUMN iam_user_tenant.deleted_by IS '删除人';
COMMENT ON COLUMN iam_user_tenant.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_user_tenant.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_tenant_user_active
    ON iam_user_tenant (tenant_id, user_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_user_tenant_user
    ON iam_user_tenant (user_id, deleted_at);

CREATE TABLE IF NOT EXISTS iam_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    description varchar(500),
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_role PRIMARY KEY (id)
);
COMMENT ON TABLE iam_role IS '角色表。';
COMMENT ON COLUMN iam_role.id IS '主键';
COMMENT ON COLUMN iam_role.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_role.code IS '角色编码';
COMMENT ON COLUMN iam_role.name IS '角色名称';
COMMENT ON COLUMN iam_role.description IS '角色描述';
COMMENT ON COLUMN iam_role.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_role.created_by IS '创建人';
COMMENT ON COLUMN iam_role.created_at IS '创建时间';
COMMENT ON COLUMN iam_role.updated_by IS '更新人';
COMMENT ON COLUMN iam_role.updated_at IS '更新时间';
COMMENT ON COLUMN iam_role.deleted_by IS '删除人';
COMMENT ON COLUMN iam_role.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_role.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_role_code_active
    ON iam_role (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_role_tenant_deleted
    ON iam_role (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS iam_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(150) NOT NULL,
    name varchar(200) NOT NULL,
    service_name varchar(80) NOT NULL,
    menu_code varchar(100),
    description varchar(500),
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_permission PRIMARY KEY (id)
);
COMMENT ON TABLE iam_permission IS '权限定义表，业务服务权限清单最终同步到本表。';
COMMENT ON COLUMN iam_permission.id IS '主键';
COMMENT ON COLUMN iam_permission.code IS '权限编码';
COMMENT ON COLUMN iam_permission.name IS '权限名称';
COMMENT ON COLUMN iam_permission.service_name IS '来源服务';
COMMENT ON COLUMN iam_permission.menu_code IS '所属菜单编码';
COMMENT ON COLUMN iam_permission.description IS '权限描述';
COMMENT ON COLUMN iam_permission.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_permission.created_by IS '创建人';
COMMENT ON COLUMN iam_permission.created_at IS '创建时间';
COMMENT ON COLUMN iam_permission.updated_by IS '更新人';
COMMENT ON COLUMN iam_permission.updated_at IS '更新时间';
COMMENT ON COLUMN iam_permission.deleted_by IS '删除人';
COMMENT ON COLUMN iam_permission.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_permission.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_permission_code_active
    ON iam_permission (code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_permission_service
    ON iam_permission (service_name, deleted_at);

CREATE TABLE IF NOT EXISTS iam_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(100) NOT NULL,
    parent_id bigint,
    title varchar(200) NOT NULL,
    i18n_key varchar(120),
    path varchar(200),
    icon varchar(100),
    permission_code varchar(150),
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_menu PRIMARY KEY (id)
);
COMMENT ON TABLE iam_menu IS '菜单表。';
COMMENT ON COLUMN iam_menu.id IS '主键';
COMMENT ON COLUMN iam_menu.code IS '菜单编码';
COMMENT ON COLUMN iam_menu.parent_id IS '父菜单 ID';
COMMENT ON COLUMN iam_menu.title IS '菜单标题';
COMMENT ON COLUMN iam_menu.i18n_key IS '国际化键';
COMMENT ON COLUMN iam_menu.path IS '前端路由路径';
COMMENT ON COLUMN iam_menu.icon IS '图标';
COMMENT ON COLUMN iam_menu.permission_code IS '进入菜单所需权限';
COMMENT ON COLUMN iam_menu.sort_no IS '排序';
COMMENT ON COLUMN iam_menu.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_menu.created_by IS '创建人';
COMMENT ON COLUMN iam_menu.created_at IS '创建时间';
COMMENT ON COLUMN iam_menu.updated_by IS '更新人';
COMMENT ON COLUMN iam_menu.updated_at IS '更新时间';
COMMENT ON COLUMN iam_menu.deleted_by IS '删除人';
COMMENT ON COLUMN iam_menu.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_menu.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_menu_code_active
    ON iam_menu (code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_menu_parent
    ON iam_menu (parent_id, sort_no);

CREATE TABLE IF NOT EXISTS iam_user_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_user_role PRIMARY KEY (id)
);
COMMENT ON TABLE iam_user_role IS '用户角色关联表。';
COMMENT ON COLUMN iam_user_role.id IS '主键';
COMMENT ON COLUMN iam_user_role.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_user_role.user_id IS '用户 ID';
COMMENT ON COLUMN iam_user_role.role_id IS '角色 ID';
COMMENT ON COLUMN iam_user_role.created_by IS '创建人';
COMMENT ON COLUMN iam_user_role.created_at IS '创建时间';
COMMENT ON COLUMN iam_user_role.updated_by IS '更新人';
COMMENT ON COLUMN iam_user_role.updated_at IS '更新时间';
COMMENT ON COLUMN iam_user_role.deleted_by IS '删除人';
COMMENT ON COLUMN iam_user_role.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_user_role.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_role_key_active
    ON iam_user_role (tenant_id, user_id, role_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_user_role_user
    ON iam_user_role (tenant_id, user_id, deleted_at);

CREATE TABLE IF NOT EXISTS iam_role_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_role_permission PRIMARY KEY (id)
);
COMMENT ON TABLE iam_role_permission IS '角色权限关联表。';
COMMENT ON COLUMN iam_role_permission.id IS '主键';
COMMENT ON COLUMN iam_role_permission.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_role_permission.role_id IS '角色 ID';
COMMENT ON COLUMN iam_role_permission.permission_id IS '权限 ID';
COMMENT ON COLUMN iam_role_permission.created_by IS '创建人';
COMMENT ON COLUMN iam_role_permission.created_at IS '创建时间';
COMMENT ON COLUMN iam_role_permission.updated_by IS '更新人';
COMMENT ON COLUMN iam_role_permission.updated_at IS '更新时间';
COMMENT ON COLUMN iam_role_permission.deleted_by IS '删除人';
COMMENT ON COLUMN iam_role_permission.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_role_permission.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_role_permission_key_active
    ON iam_role_permission (tenant_id, role_id, permission_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_role_permission_role
    ON iam_role_permission (tenant_id, role_id, deleted_at);

CREATE TABLE IF NOT EXISTS iam_authorization_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    auth_version bigint DEFAULT 0 NOT NULL,
    role_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    permission_codes jsonb DEFAULT '[]'::jsonb NOT NULL,
    menu_codes jsonb DEFAULT '[]'::jsonb NOT NULL,
    column_settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    snapshot_hash varchar(128),
    expires_at timestamptz,
    built_at timestamptz DEFAULT now() NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_authorization_snapshot PRIMARY KEY (id)
);
COMMENT ON TABLE iam_authorization_snapshot IS '用户授权快照表，保存 Gateway 和业务服务可缓存使用的权限、菜单和列权限快照。';
COMMENT ON COLUMN iam_authorization_snapshot.id IS '主键';
COMMENT ON COLUMN iam_authorization_snapshot.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_authorization_snapshot.user_id IS '用户 ID';
COMMENT ON COLUMN iam_authorization_snapshot.auth_version IS '权限版本';
COMMENT ON COLUMN iam_authorization_snapshot.role_ids IS '角色 ID 列表';
COMMENT ON COLUMN iam_authorization_snapshot.permission_codes IS '权限编码列表';
COMMENT ON COLUMN iam_authorization_snapshot.menu_codes IS '菜单编码列表';
COMMENT ON COLUMN iam_authorization_snapshot.column_settings IS '列权限配置快照';
COMMENT ON COLUMN iam_authorization_snapshot.snapshot_hash IS '快照哈希';
COMMENT ON COLUMN iam_authorization_snapshot.expires_at IS '快照过期时间';
COMMENT ON COLUMN iam_authorization_snapshot.built_at IS '快照生成时间';
COMMENT ON COLUMN iam_authorization_snapshot.created_by IS '创建人';
COMMENT ON COLUMN iam_authorization_snapshot.created_at IS '创建时间';
COMMENT ON COLUMN iam_authorization_snapshot.updated_by IS '更新人';
COMMENT ON COLUMN iam_authorization_snapshot.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_authorization_snapshot_user
    ON iam_authorization_snapshot (tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_iam_authorization_snapshot_expires
    ON iam_authorization_snapshot (expires_at);

CREATE TABLE IF NOT EXISTS iam_tenant_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_tenant_menu PRIMARY KEY (id)
);
COMMENT ON TABLE iam_tenant_menu IS '租户菜单授权表。';
COMMENT ON COLUMN iam_tenant_menu.id IS '主键';
COMMENT ON COLUMN iam_tenant_menu.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_tenant_menu.menu_id IS '菜单 ID';
COMMENT ON COLUMN iam_tenant_menu.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_tenant_menu.created_by IS '创建人';
COMMENT ON COLUMN iam_tenant_menu.created_at IS '创建时间';
COMMENT ON COLUMN iam_tenant_menu.updated_by IS '更新人';
COMMENT ON COLUMN iam_tenant_menu.updated_at IS '更新时间';
COMMENT ON COLUMN iam_tenant_menu.deleted_by IS '删除人';
COMMENT ON COLUMN iam_tenant_menu.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_tenant_menu.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_tenant_menu_key_active
    ON iam_tenant_menu (tenant_id, menu_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_tenant_menu_tenant
    ON iam_tenant_menu (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS iam_tenant_column_setting (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    page_key varchar(120) NOT NULL,
    visible_columns jsonb NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_tenant_column_setting PRIMARY KEY (id)
);
COMMENT ON TABLE iam_tenant_column_setting IS '租户列权限默认配置。';
COMMENT ON COLUMN iam_tenant_column_setting.id IS '主键';
COMMENT ON COLUMN iam_tenant_column_setting.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_tenant_column_setting.page_key IS '页面标识';
COMMENT ON COLUMN iam_tenant_column_setting.visible_columns IS '可见列清单';
COMMENT ON COLUMN iam_tenant_column_setting.created_by IS '创建人';
COMMENT ON COLUMN iam_tenant_column_setting.created_at IS '创建时间';
COMMENT ON COLUMN iam_tenant_column_setting.updated_by IS '更新人';
COMMENT ON COLUMN iam_tenant_column_setting.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_tenant_column_page
    ON iam_tenant_column_setting (tenant_id, page_key);

CREATE TABLE IF NOT EXISTS iam_role_column_setting (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    role_id bigint NOT NULL,
    page_key varchar(120) NOT NULL,
    visible_columns jsonb NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_role_column_setting PRIMARY KEY (id)
);
COMMENT ON TABLE iam_role_column_setting IS '角色列权限配置。';
COMMENT ON COLUMN iam_role_column_setting.id IS '主键';
COMMENT ON COLUMN iam_role_column_setting.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_role_column_setting.role_id IS '角色 ID';
COMMENT ON COLUMN iam_role_column_setting.page_key IS '页面标识';
COMMENT ON COLUMN iam_role_column_setting.visible_columns IS '可见列清单';
COMMENT ON COLUMN iam_role_column_setting.created_by IS '创建人';
COMMENT ON COLUMN iam_role_column_setting.created_at IS '创建时间';
COMMENT ON COLUMN iam_role_column_setting.updated_by IS '更新人';
COMMENT ON COLUMN iam_role_column_setting.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_role_column_page
    ON iam_role_column_setting (tenant_id, role_id, page_key);

CREATE TABLE IF NOT EXISTS iam_user_table_setting (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    page_key varchar(120) NOT NULL,
    config_json jsonb NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_user_table_setting PRIMARY KEY (id)
);
COMMENT ON TABLE iam_user_table_setting IS '用户表格个性化配置。';
COMMENT ON COLUMN iam_user_table_setting.id IS '主键';
COMMENT ON COLUMN iam_user_table_setting.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_user_table_setting.user_id IS '用户 ID';
COMMENT ON COLUMN iam_user_table_setting.page_key IS '页面标识';
COMMENT ON COLUMN iam_user_table_setting.config_json IS '表格配置 JSON';
COMMENT ON COLUMN iam_user_table_setting.created_by IS '创建人';
COMMENT ON COLUMN iam_user_table_setting.created_at IS '创建时间';
COMMENT ON COLUMN iam_user_table_setting.updated_by IS '更新人';
COMMENT ON COLUMN iam_user_table_setting.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_user_table_page
    ON iam_user_table_setting (tenant_id, user_id, page_key);

CREATE TABLE IF NOT EXISTS iam_refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    token_family_id varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    replaced_by_token_hash varchar(64),
    last_used_at timestamptz,
    audience_tenant_id bigint,
    device_id varchar(100),
    ip_address varchar(64),
    user_agent varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_refresh_token PRIMARY KEY (id)
);
COMMENT ON TABLE iam_refresh_token IS '刷新令牌表。';
COMMENT ON COLUMN iam_refresh_token.id IS '主键';
COMMENT ON COLUMN iam_refresh_token.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_refresh_token.user_id IS '用户 ID';
COMMENT ON COLUMN iam_refresh_token.token_hash IS '令牌哈希';
COMMENT ON COLUMN iam_refresh_token.token_family_id IS '令牌族 ID，用于 refresh token 轮换追踪';
COMMENT ON COLUMN iam_refresh_token.expires_at IS '过期时间';
COMMENT ON COLUMN iam_refresh_token.revoked_at IS '撤销时间';
COMMENT ON COLUMN iam_refresh_token.replaced_by_token_hash IS '被轮换后的新令牌哈希';
COMMENT ON COLUMN iam_refresh_token.last_used_at IS '最近使用时间';
COMMENT ON COLUMN iam_refresh_token.audience_tenant_id IS '目标租户 ID';
COMMENT ON COLUMN iam_refresh_token.device_id IS '设备 ID';
COMMENT ON COLUMN iam_refresh_token.ip_address IS '最近使用 IP';
COMMENT ON COLUMN iam_refresh_token.user_agent IS '最近使用 User-Agent';
COMMENT ON COLUMN iam_refresh_token.created_by IS '创建人';
COMMENT ON COLUMN iam_refresh_token.created_at IS '创建时间';
COMMENT ON COLUMN iam_refresh_token.updated_by IS '更新人';
COMMENT ON COLUMN iam_refresh_token.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_refresh_token_hash
    ON iam_refresh_token (token_hash);
CREATE INDEX IF NOT EXISTS idx_iam_refresh_token_user
    ON iam_refresh_token (tenant_id, user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_iam_refresh_token_family
    ON iam_refresh_token (token_family_id, user_id);

CREATE TABLE IF NOT EXISTS iam_tenant_bootstrap_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    task_key varchar(160) NOT NULL,
    status varchar(30) DEFAULT 'SUCCEEDED' NOT NULL,
    idempotency_key varchar(200) NOT NULL,
    requested_by varchar(100),
    menu_grant_count integer DEFAULT 0 NOT NULL,
    started_at timestamptz DEFAULT now() NOT NULL,
    finished_at timestamptz,
    last_error_message text,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_tenant_bootstrap_task PRIMARY KEY (id)
);
COMMENT ON TABLE iam_tenant_bootstrap_task IS '租户 IAM 初始化任务记录，记录 xuan-tenant 开通流程传入真实 tenantId 后的菜单授权初始化结果。';
COMMENT ON COLUMN iam_tenant_bootstrap_task.id IS '主键';
COMMENT ON COLUMN iam_tenant_bootstrap_task.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_tenant_bootstrap_task.task_key IS '初始化任务键';
COMMENT ON COLUMN iam_tenant_bootstrap_task.status IS '任务状态：SUCCEEDED/FAILED';
COMMENT ON COLUMN iam_tenant_bootstrap_task.idempotency_key IS '幂等键';
COMMENT ON COLUMN iam_tenant_bootstrap_task.requested_by IS '触发人或来源服务';
COMMENT ON COLUMN iam_tenant_bootstrap_task.menu_grant_count IS '本次新增菜单授权数量';
COMMENT ON COLUMN iam_tenant_bootstrap_task.started_at IS '开始时间';
COMMENT ON COLUMN iam_tenant_bootstrap_task.finished_at IS '完成时间';
COMMENT ON COLUMN iam_tenant_bootstrap_task.last_error_message IS '最近错误信息';
COMMENT ON COLUMN iam_tenant_bootstrap_task.created_by IS '创建人';
COMMENT ON COLUMN iam_tenant_bootstrap_task.created_at IS '创建时间';
COMMENT ON COLUMN iam_tenant_bootstrap_task.updated_by IS '更新人';
COMMENT ON COLUMN iam_tenant_bootstrap_task.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_tenant_bootstrap_task_key
    ON iam_tenant_bootstrap_task (tenant_id, task_key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_tenant_bootstrap_idempotency
    ON iam_tenant_bootstrap_task (idempotency_key);

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- iam_permission: 全局权限清单，业务服务后续可通过同步机制继续补充。
INSERT INTO iam_permission (code, name, service_name, menu_code, description, is_enabled, created_by, updated_by)
SELECT seed.code, seed.name, seed.service_name, seed.menu_code, seed.description, seed.is_enabled, 'system', 'system'
FROM (
    VALUES
    ('tenant:read', '租户查看', 'xuan-tenant', 'system', '查看租户与租户配置', true, 'system', 'system'),
    ('tenant:manage', '租户管理', 'xuan-tenant', 'system', '维护租户与租户配置', true, 'system', 'system'),
    ('iam:view', '权限查看', 'xuan-iam', 'system', '查看用户、角色、权限、菜单', true, 'system', 'system'),
    ('iam:create', '权限新增', 'xuan-iam', 'system', '新增用户、角色、权限、菜单', true, 'system', 'system'),
    ('iam:update', '权限修改', 'xuan-iam', 'system', '修改用户、角色、权限、菜单', true, 'system', 'system'),
    ('iam:delete', '权限删除', 'xuan-iam', 'system', '删除或停用用户、角色、权限、菜单', true, 'system', 'system'),
    ('product:read', '商品查看', 'xuan-product', 'product', '查看商品、分类、单位和车型适配', true, 'system', 'system'),
    ('product:manage', '商品管理', 'xuan-product', 'product', '维护商品、分类、单位和车型适配', true, 'system', 'system'),
    ('party:read', '往来查看', 'xuan-party', 'party', '查看客户、供应商和往来主体', true, 'system', 'system'),
    ('party:manage', '往来管理', 'xuan-party', 'party', '维护客户、供应商和往来主体', true, 'system', 'system'),
    ('warehouse:read', '仓库查看', 'xuan-warehouse', 'warehouse', '查看仓库和库位', true, 'system', 'system'),
    ('warehouse:manage', '仓库管理', 'xuan-warehouse', 'warehouse', '维护仓库和库位', true, 'system', 'system'),
    ('inventory:read', '库存查看', 'xuan-inventory', 'inventory', '查看库存、盘点和移库', true, 'system', 'system'),
    ('inventory:manage', '库存管理', 'xuan-inventory', 'inventory', '维护库存、盘点和移库', true, 'system', 'system'),
    ('sales:read', '销售查看', 'xuan-sales', 'sales', '查看销售单和销售退货', true, 'system', 'system'),
    ('sales:manage', '销售管理', 'xuan-sales', 'sales', '维护销售单和销售退货', true, 'system', 'system'),
    ('procurement:read', '采购查看', 'xuan-procurement', 'procurement', '查看采购单和采购退货', true, 'system', 'system'),
    ('procurement:manage', '采购管理', 'xuan-procurement', 'procurement', '维护采购单和采购退货', true, 'system', 'system'),
    ('finance:read', '财务查看', 'xuan-finance', 'finance', '查看应收、应付、收款和付款', true, 'system', 'system'),
    ('finance:manage', '财务管理', 'xuan-finance', 'finance', '维护应收、应付、收款和付款', true, 'system', 'system'),
    ('document:read', '打印查看', 'xuan-document', 'document', '查看打印模板、日志和快照', true, 'system', 'system'),
    ('document:manage', '打印管理', 'xuan-document', 'document', '维护打印模板', true, 'system', 'system'),
    ('manufacturing:read', '组装查看', 'xuan-manufacturing', 'manufacturing', '查看组装/拆分模板和单据', true, 'system', 'system'),
    ('manufacturing:manage', '组装管理', 'xuan-manufacturing', 'manufacturing', '维护组装/拆分模板和单据', true, 'system', 'system'),
    ('query:read', '报表查看', 'xuan-query', 'report', '查看报表和读模型', true, 'system', 'system'),
    ('audit:read', '审计查看', 'xuan-audit', 'system', '查看审计日志和 SQL trace', true, 'system', 'system')
) AS seed(code, name, service_name, menu_code, description, is_enabled, created_by, updated_by)
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_permission existing
    WHERE existing.code = seed.code
      AND existing.deleted_at IS NULL
);

-- iam_menu: 全局一级菜单，权限和租户授权可在此基础上扩展。
INSERT INTO iam_menu (code, parent_id, title, i18n_key, path, icon, permission_code, sort_no, is_enabled, created_by, updated_by)
SELECT seed.code, seed.parent_id, seed.title, seed.i18n_key, seed.path, seed.icon, seed.permission_code, seed.sort_no, seed.is_enabled, 'system', 'system'
FROM (
    VALUES
    ('workbench', NULL::bigint, '工作台', 'menu.workbench', '/workbench', 'LayoutDashboard', NULL, 10, true, 'system', 'system'),
    ('product', NULL::bigint, '商品', 'menu.product', '/product', 'Package', 'product:read', 20, true, 'system', 'system'),
    ('party', NULL::bigint, '往来', 'menu.party', '/party', 'ContactRound', 'party:read', 30, true, 'system', 'system'),
    ('warehouse', NULL::bigint, '仓库', 'menu.warehouse', '/warehouse', 'Warehouse', 'warehouse:read', 40, true, 'system', 'system'),
    ('inventory', NULL::bigint, '库存', 'menu.inventory', '/inventory', 'Boxes', 'inventory:read', 50, true, 'system', 'system'),
    ('sales', NULL::bigint, '销售', 'menu.sales', '/sales', 'ShoppingCart', 'sales:read', 60, true, 'system', 'system'),
    ('procurement', NULL::bigint, '采购', 'menu.procurement', '/procurement', 'Truck', 'procurement:read', 70, true, 'system', 'system'),
    ('finance', NULL::bigint, '财务', 'menu.finance', '/finance', 'ReceiptText', 'finance:read', 80, true, 'system', 'system'),
    ('document', NULL::bigint, '打印', 'menu.document', '/document', 'Printer', 'document:read', 90, true, 'system', 'system'),
    ('manufacturing', NULL::bigint, '组装拆分', 'menu.manufacturing', '/manufacturing', 'Workflow', 'manufacturing:read', 100, true, 'system', 'system'),
    ('report', NULL::bigint, '报表', 'menu.report', '/report', 'ChartNoAxesColumn', 'query:read', 110, true, 'system', 'system'),
    ('system', NULL::bigint, '系统', 'menu.system', '/system', 'Settings', 'iam:view', 120, true, 'system', 'system')
) AS seed(code, parent_id, title, i18n_key, path, icon, permission_code, sort_no, is_enabled, created_by, updated_by)
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_menu existing
    WHERE existing.code = seed.code
      AND existing.deleted_at IS NULL
);

-- iam_tenant_menu: 生产租户菜单授权由 `xuan-tenant` 开通流程传入真实 `tenantId` 后幂等初始化。
CREATE OR REPLACE FUNCTION bootstrap_iam_tenant(
    p_tenant_id bigint,
    p_requested_by varchar DEFAULT 'tenant-provision'
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_inserted_count integer := 0;
    v_task_key varchar(160);
    v_idempotency_key varchar(200);
BEGIN
    IF p_tenant_id IS NULL OR p_tenant_id <= 0 THEN
        RAISE EXCEPTION 'p_tenant_id must be a positive tenant id';
    END IF;

    v_task_key := 'IAM_TENANT_BOOTSTRAP';
    v_idempotency_key := 'iam:tenant:' || p_tenant_id || ':bootstrap:v1';

    INSERT INTO iam_tenant_menu (tenant_id, menu_id, is_enabled, created_by, updated_by)
    SELECT p_tenant_id, iam_menu.id, true, p_requested_by, p_requested_by
    FROM iam_menu
    WHERE iam_menu.code IN (
        'workbench', 'product', 'party', 'warehouse', 'inventory', 'sales',
        'procurement', 'finance', 'document', 'manufacturing', 'report', 'system'
    )
      AND iam_menu.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM iam_tenant_menu existing
          WHERE existing.tenant_id = p_tenant_id
            AND existing.menu_id = iam_menu.id
            AND existing.deleted_at IS NULL
      );

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

    INSERT INTO iam_tenant_bootstrap_task (
        tenant_id,
        task_key,
        status,
        idempotency_key,
        requested_by,
        menu_grant_count,
        started_at,
        finished_at,
        created_by,
        updated_by
    )
    SELECT
        p_tenant_id,
        v_task_key,
        'SUCCEEDED',
        v_idempotency_key,
        p_requested_by,
        v_inserted_count,
        now(),
        now(),
        p_requested_by,
        p_requested_by
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_tenant_bootstrap_task existing
        WHERE existing.idempotency_key = v_idempotency_key
    );

    RETURN v_inserted_count;
EXCEPTION WHEN OTHERS THEN
    INSERT INTO iam_tenant_bootstrap_task (
        tenant_id,
        task_key,
        status,
        idempotency_key,
        requested_by,
        menu_grant_count,
        started_at,
        finished_at,
        last_error_message,
        created_by,
        updated_by
    )
    VALUES (
        p_tenant_id,
        COALESCE(v_task_key, 'IAM_TENANT_BOOTSTRAP'),
        'FAILED',
        COALESCE(v_idempotency_key, 'iam:tenant:' || COALESCE(p_tenant_id::text, 'null') || ':bootstrap:v1'),
        p_requested_by,
        0,
        now(),
        now(),
        SQLERRM,
        p_requested_by,
        p_requested_by
    );
    RAISE;
END;
$$;
COMMENT ON FUNCTION bootstrap_iam_tenant(bigint, varchar) IS '按 xuan-tenant 传入的真实 tenantId 幂等初始化 IAM 租户菜单授权。';

-- iam_tenant_bootstrap_task: 记录租户 IAM 初始化结果，支持重复触发时按幂等键识别。
-- iam_tenant_bootstrap_task rows are written by bootstrap_iam_tenant when xuan-tenant provisions a real tenant.
