-- Add tenant permission entitlement pool as the authority boundary for tenant roles.

CREATE TABLE IF NOT EXISTS iam_tenant_permission_entitlement (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    init_template_code varchar(64),
    permission_id bigint NOT NULL,
    entitlement_version bigint DEFAULT 1 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_tenant_permission_entitlement PRIMARY KEY (id)
);

COMMENT ON TABLE iam_tenant_permission_entitlement IS 'IAM 租户权限池表，保存租户内角色可被分配权限的上限。';
COMMENT ON COLUMN iam_tenant_permission_entitlement.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_tenant_permission_entitlement.init_template_code IS '来源初始化模板编码';
COMMENT ON COLUMN iam_tenant_permission_entitlement.permission_id IS '权限 ID';
COMMENT ON COLUMN iam_tenant_permission_entitlement.entitlement_version IS '租户权限池版本';
COMMENT ON COLUMN iam_tenant_permission_entitlement.is_enabled IS '是否启用';

CREATE UNIQUE INDEX IF NOT EXISTS uk_iam_tenant_permission_entitlement_active
    ON iam_tenant_permission_entitlement (tenant_id, permission_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_tenant_permission_entitlement_template
    ON iam_tenant_permission_entitlement (init_template_code, tenant_id)
    WHERE deleted_at IS NULL;

WITH latest_bootstrap_template AS (
    SELECT DISTINCT ON (event.tenant_id)
           event.tenant_id,
           NULLIF(event.payload ->> 'iamInitTemplateCode', '') AS init_template_code
    FROM iam_outbox_event event
    WHERE event.event_type = 'IamTenantBootstrapped'
      AND event.tenant_id > 0
      AND event.payload ? 'iamInitTemplateCode'
    ORDER BY event.tenant_id, event.created_at DESC, event.id DESC
),
template_permission_seed AS (
    SELECT latest_bootstrap_template.tenant_id,
           latest_bootstrap_template.init_template_code,
           permission.id AS permission_id
    FROM latest_bootstrap_template
    JOIN iam_tenant_init_permission_template template
      ON template.code = latest_bootstrap_template.init_template_code
     AND template.deleted_at IS NULL
    JOIN LATERAL jsonb_array_elements_text(COALESCE(template.permission_codes, '[]'::jsonb)) AS permission_code(value) ON true
    JOIN iam_permission permission
      ON permission.code = permission_code.value
     AND permission.is_enabled = true
     AND permission.deleted_at IS NULL
    WHERE latest_bootstrap_template.init_template_code IS NOT NULL
),
role_permission_seed AS (
    SELECT DISTINCT role_permission.tenant_id,
           COALESCE(latest_bootstrap_template.init_template_code, 'legacy-current-role-permissions') AS init_template_code,
           role_permission.permission_id
    FROM iam_role_permission role_permission
    JOIN iam_permission permission ON permission.id = role_permission.permission_id
    LEFT JOIN latest_bootstrap_template ON latest_bootstrap_template.tenant_id = role_permission.tenant_id
    WHERE role_permission.tenant_id > 0
      AND role_permission.deleted_at IS NULL
      AND permission.deleted_at IS NULL
      AND permission.is_enabled = true
),
entitlement_seed AS (
    SELECT tenant_id, init_template_code, permission_id
    FROM template_permission_seed
    UNION
    SELECT tenant_id, init_template_code, permission_id
    FROM role_permission_seed
)
INSERT INTO iam_tenant_permission_entitlement (
    tenant_id, init_template_code, permission_id, entitlement_version, is_enabled, created_by, updated_by
)
SELECT entitlement_seed.tenant_id,
       entitlement_seed.init_template_code,
       entitlement_seed.permission_id,
       1,
       true,
       'system',
       'system'
FROM entitlement_seed
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_tenant_permission_entitlement existing
    WHERE existing.tenant_id = entitlement_seed.tenant_id
      AND existing.permission_id = entitlement_seed.permission_id
      AND existing.deleted_at IS NULL
);

CREATE OR REPLACE FUNCTION bootstrap_iam_tenant(
    p_tenant_id bigint,
    p_admin_username varchar,
    p_admin_password_hash varchar,
    p_admin_display_name varchar,
    p_admin_email varchar,
    p_admin_phone varchar,
    p_iam_init_template_code varchar,
    p_requested_by varchar
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_inserted_count integer := 0;
    v_task_key varchar(160);
    v_idempotency_key varchar(200);
    v_event_id varchar(160);
    v_admin_username varchar(100);
    v_admin_display_name varchar(200);
    v_admin_user_id bigint;
    v_template_lookup_code varchar(64);
    v_template_code varchar(64);
    v_permission_codes jsonb := '[]'::jsonb;
    v_entitlement_version bigint := 1;
BEGIN
    IF p_tenant_id IS NULL OR p_tenant_id <= 0 THEN
        RAISE EXCEPTION 'p_tenant_id must be a positive tenant id';
    END IF;
    IF p_admin_password_hash IS NULL OR btrim(p_admin_password_hash) = '' THEN
        RAISE EXCEPTION 'p_admin_password_hash must not be blank';
    END IF;

    v_task_key := 'IAM_TENANT_BOOTSTRAP';
    v_idempotency_key := 'iam:tenant:' || p_tenant_id || ':bootstrap:v1';
    v_event_id := v_idempotency_key || ':event';
    v_admin_username := COALESCE(NULLIF(btrim(p_admin_username), ''), 'admin');
    v_admin_display_name := COALESCE(NULLIF(btrim(p_admin_display_name), ''), '租户管理员');
    v_template_lookup_code := NULLIF(btrim(p_iam_init_template_code), '');

    SELECT template.code,
           template.permission_codes
    INTO v_template_code,
         v_permission_codes
    FROM iam_tenant_init_permission_template template
    WHERE template.deleted_at IS NULL
      AND template.is_enabled = true
      AND (
          (v_template_lookup_code IS NOT NULL AND template.code = v_template_lookup_code)
          OR (v_template_lookup_code IS NULL AND template.is_default = true)
      )
    ORDER BY template.id
    LIMIT 1;

    IF v_template_code IS NULL THEN
        RAISE EXCEPTION 'iam tenant init permission template not found or disabled: %',
            COALESCE(v_template_lookup_code, 'default');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM iam_tenant_init_role_template role_template
        WHERE role_template.init_template_code = v_template_code
          AND role_template.is_enabled = true
          AND role_template.deleted_at IS NULL
    ) THEN
        RAISE EXCEPTION 'iam tenant init role template not found or disabled: %', v_template_code;
    END IF;

    SELECT COALESCE(MAX(entitlement_version), 0) + 1
    INTO v_entitlement_version
    FROM iam_tenant_permission_entitlement
    WHERE tenant_id = p_tenant_id;

    UPDATE iam_tenant_permission_entitlement entitlement
    SET deleted_by = p_requested_by,
        delete_reason = 'sync by iam init template ' || v_template_code,
        deleted_at = now(),
        updated_by = p_requested_by,
        updated_at = now()
    WHERE entitlement.tenant_id = p_tenant_id
      AND entitlement.deleted_at IS NULL;

    WITH selected_permission(code) AS (
        SELECT DISTINCT value
        FROM jsonb_array_elements_text(COALESCE(v_permission_codes, '[]'::jsonb)) AS item(value)
    )
    INSERT INTO iam_tenant_permission_entitlement (
        tenant_id, init_template_code, permission_id, entitlement_version, is_enabled, created_by, updated_by
    )
    SELECT p_tenant_id, v_template_code, permission.id, v_entitlement_version, true, p_requested_by, p_requested_by
    FROM selected_permission
    JOIN iam_permission permission ON permission.code = selected_permission.code
                                  AND permission.is_enabled = true
                                  AND permission.deleted_at IS NULL
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_tenant_permission_entitlement existing
        WHERE existing.tenant_id = p_tenant_id
          AND existing.permission_id = permission.id
          AND existing.deleted_at IS NULL
    );

    WITH RECURSIVE selected_permission(code) AS (
        SELECT DISTINCT value
        FROM jsonb_array_elements_text(COALESCE(v_permission_codes, '[]'::jsonb)) AS item(value)
    ),
    direct_menu AS (
        SELECT menu.id,
               menu.parent_id
        FROM iam_menu menu
        WHERE menu.deleted_at IS NULL
          AND menu.is_enabled = true
          AND (
              menu.permission_code IS NULL
              OR EXISTS (
                  SELECT 1
                  FROM selected_permission
                  WHERE selected_permission.code = menu.permission_code
              )
          )
    ),
    menu_tree(id, parent_id) AS (
        SELECT direct_menu.id,
               direct_menu.parent_id
        FROM direct_menu
        UNION
        SELECT parent.id,
               parent.parent_id
        FROM iam_menu parent
        JOIN menu_tree child ON child.parent_id = parent.id
        WHERE parent.deleted_at IS NULL
          AND parent.is_enabled = true
    )
    UPDATE iam_tenant_menu tenant_menu
    SET deleted_by = p_requested_by,
        delete_reason = 'sync by iam init role template ' || v_template_code,
        deleted_at = now(),
        updated_by = p_requested_by,
        updated_at = now()
    WHERE tenant_menu.tenant_id = p_tenant_id
      AND tenant_menu.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM menu_tree
          WHERE menu_tree.id = tenant_menu.menu_id
      );

    WITH RECURSIVE selected_permission(code) AS (
        SELECT DISTINCT value
        FROM jsonb_array_elements_text(COALESCE(v_permission_codes, '[]'::jsonb)) AS item(value)
    ),
    direct_menu AS (
        SELECT menu.id,
               menu.parent_id
        FROM iam_menu menu
        WHERE menu.deleted_at IS NULL
          AND menu.is_enabled = true
          AND (
              menu.permission_code IS NULL
              OR EXISTS (
                  SELECT 1
                  FROM selected_permission
                  WHERE selected_permission.code = menu.permission_code
              )
          )
    ),
    menu_tree(id, parent_id) AS (
        SELECT direct_menu.id,
               direct_menu.parent_id
        FROM direct_menu
        UNION
        SELECT parent.id,
               parent.parent_id
        FROM iam_menu parent
        JOIN menu_tree child ON child.parent_id = parent.id
        WHERE parent.deleted_at IS NULL
          AND parent.is_enabled = true
    )
    INSERT INTO iam_tenant_menu (tenant_id, menu_id, is_enabled, created_by, updated_by)
    SELECT DISTINCT p_tenant_id, menu_tree.id, true, p_requested_by, p_requested_by
    FROM menu_tree
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_tenant_menu existing
        WHERE existing.tenant_id = p_tenant_id
          AND existing.menu_id = menu_tree.id
          AND existing.deleted_at IS NULL
    );

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

    INSERT INTO iam_user (
        tenant_id, username, password_hash, display_name, email, phone,
        is_enabled, account_non_expired, account_non_locked, credentials_non_expired,
        password_changed_at, auth_version, created_by, updated_by
    )
    SELECT
        p_tenant_id,
        v_admin_username,
        p_admin_password_hash,
        v_admin_display_name,
        NULLIF(btrim(p_admin_email), ''),
        NULLIF(btrim(p_admin_phone), ''),
        true,
        true,
        true,
        true,
        now(),
        1,
        p_requested_by,
        p_requested_by
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_user existing
        WHERE existing.tenant_id = p_tenant_id
          AND existing.username = v_admin_username
          AND existing.deleted_at IS NULL
    )
    RETURNING id INTO v_admin_user_id;

    IF v_admin_user_id IS NULL THEN
        SELECT id INTO v_admin_user_id
        FROM iam_user
        WHERE tenant_id = p_tenant_id
          AND username = v_admin_username
          AND deleted_at IS NULL
        ORDER BY id
        LIMIT 1;
    END IF;

    INSERT INTO iam_user_tenant (
        tenant_id, user_id, user_type, membership_status, is_tenant_admin, created_by, updated_by
    )
    SELECT p_tenant_id, v_admin_user_id, 'TENANT_USER', 'ACTIVE', true, p_requested_by, p_requested_by
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_user_tenant existing
        WHERE existing.tenant_id = p_tenant_id
          AND existing.user_id = v_admin_user_id
          AND existing.deleted_at IS NULL
    );

    UPDATE iam_role role
    SET name = role_template.role_name,
        description = role_template.role_description,
        is_enabled = true,
        updated_by = p_requested_by,
        updated_at = now()
    FROM iam_tenant_init_role_template role_template
    WHERE role.tenant_id = p_tenant_id
      AND role.code = role_template.role_code
      AND role.deleted_at IS NULL
      AND role_template.init_template_code = v_template_code
      AND role_template.is_enabled = true
      AND role_template.deleted_at IS NULL;

    INSERT INTO iam_role (tenant_id, code, name, description, is_enabled, created_by, updated_by)
    SELECT p_tenant_id,
           role_template.role_code,
           role_template.role_name,
           role_template.role_description,
           true,
           p_requested_by,
           p_requested_by
    FROM iam_tenant_init_role_template role_template
    WHERE role_template.init_template_code = v_template_code
      AND role_template.is_enabled = true
      AND role_template.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM iam_role existing
          WHERE existing.tenant_id = p_tenant_id
            AND existing.code = role_template.role_code
            AND existing.deleted_at IS NULL
      );

    WITH managed_role_code(role_code) AS (
        SELECT DISTINCT role_template.role_code
        FROM iam_tenant_init_role_template role_template
        WHERE role_template.deleted_at IS NULL
    ),
    assignable_role(role_id) AS (
        SELECT role.id
        FROM iam_tenant_init_role_template role_template
        JOIN iam_role role ON role.tenant_id = p_tenant_id
                          AND role.code = role_template.role_code
                          AND role.deleted_at IS NULL
        WHERE role_template.init_template_code = v_template_code
          AND role_template.is_enabled = true
          AND role_template.deleted_at IS NULL
          AND role_template.assign_to_admin = true
    )
    UPDATE iam_user_role user_role
    SET deleted_by = p_requested_by,
        delete_reason = 'sync by iam init role template ' || v_template_code,
        deleted_at = now(),
        updated_by = p_requested_by,
        updated_at = now()
    FROM iam_role role
    WHERE user_role.tenant_id = p_tenant_id
      AND user_role.user_id = v_admin_user_id
      AND user_role.role_id = role.id
      AND user_role.deleted_at IS NULL
      AND role.tenant_id = p_tenant_id
      AND role.deleted_at IS NULL
      AND role.code IN (SELECT role_code FROM managed_role_code)
      AND NOT EXISTS (
          SELECT 1
          FROM assignable_role
          WHERE assignable_role.role_id = user_role.role_id
      );

    INSERT INTO iam_user_role (tenant_id, user_id, role_id, created_by, updated_by)
    SELECT p_tenant_id, v_admin_user_id, role.id, p_requested_by, p_requested_by
    FROM iam_tenant_init_role_template role_template
    JOIN iam_role role ON role.tenant_id = p_tenant_id
                      AND role.code = role_template.role_code
                      AND role.deleted_at IS NULL
    WHERE role_template.init_template_code = v_template_code
      AND role_template.is_enabled = true
      AND role_template.deleted_at IS NULL
      AND role_template.assign_to_admin = true
      AND NOT EXISTS (
          SELECT 1
          FROM iam_user_role existing
          WHERE existing.tenant_id = p_tenant_id
            AND existing.user_id = v_admin_user_id
            AND existing.role_id = role.id
            AND existing.deleted_at IS NULL
      );

    WITH template_permission(code) AS (
        SELECT DISTINCT value
        FROM jsonb_array_elements_text(COALESCE(v_permission_codes, '[]'::jsonb)) AS item(value)
    ),
    current_role_permission(role_code, permission_code) AS (
        SELECT DISTINCT role_template.role_code,
               role_permission_code.value
        FROM iam_tenant_init_role_template role_template
        JOIN LATERAL jsonb_array_elements_text(COALESCE(role_template.permission_codes, '[]'::jsonb)) AS role_permission_code(value) ON true
        JOIN template_permission ON template_permission.code = role_permission_code.value
        WHERE role_template.init_template_code = v_template_code
          AND role_template.is_enabled = true
          AND role_template.deleted_at IS NULL
    ),
    managed_role_code(role_code) AS (
        SELECT DISTINCT role_template.role_code
        FROM iam_tenant_init_role_template role_template
        WHERE role_template.deleted_at IS NULL
    )
    UPDATE iam_role_permission role_permission
    SET deleted_by = p_requested_by,
        delete_reason = 'sync by iam init role template ' || v_template_code,
        deleted_at = now(),
        updated_by = p_requested_by,
        updated_at = now()
    FROM iam_role role,
         iam_permission permission
    WHERE role_permission.tenant_id = p_tenant_id
      AND role_permission.role_id = role.id
      AND role_permission.permission_id = permission.id
      AND role_permission.deleted_at IS NULL
      AND role.tenant_id = p_tenant_id
      AND role.deleted_at IS NULL
      AND role.code IN (SELECT role_code FROM managed_role_code)
      AND permission.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM current_role_permission
          WHERE current_role_permission.role_code = role.code
            AND current_role_permission.permission_code = permission.code
      );

    WITH template_permission(code) AS (
        SELECT DISTINCT value
        FROM jsonb_array_elements_text(COALESCE(v_permission_codes, '[]'::jsonb)) AS item(value)
    ),
    current_role_permission(role_code, permission_code) AS (
        SELECT DISTINCT role_template.role_code,
               role_permission_code.value
        FROM iam_tenant_init_role_template role_template
        JOIN LATERAL jsonb_array_elements_text(COALESCE(role_template.permission_codes, '[]'::jsonb)) AS role_permission_code(value) ON true
        JOIN template_permission ON template_permission.code = role_permission_code.value
        WHERE role_template.init_template_code = v_template_code
          AND role_template.is_enabled = true
          AND role_template.deleted_at IS NULL
    )
    INSERT INTO iam_role_permission (tenant_id, role_id, permission_id, created_by, updated_by)
    SELECT p_tenant_id, role.id, permission.id, p_requested_by, p_requested_by
    FROM current_role_permission
    JOIN iam_role role ON role.tenant_id = p_tenant_id
                      AND role.code = current_role_permission.role_code
                      AND role.deleted_at IS NULL
    JOIN iam_permission permission ON permission.code = current_role_permission.permission_code
                                  AND permission.is_enabled = true
                                  AND permission.deleted_at IS NULL
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_role_permission existing
        WHERE existing.tenant_id = p_tenant_id
          AND existing.role_id = role.id
          AND existing.permission_id = permission.id
          AND existing.deleted_at IS NULL
    );

    UPDATE iam_role_permission role_permission
    SET deleted_by = p_requested_by,
        delete_reason = 'tenant permission entitlement reduced',
        deleted_at = now(),
        updated_by = p_requested_by,
        updated_at = now()
    WHERE role_permission.tenant_id = p_tenant_id
      AND role_permission.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM iam_tenant_permission_entitlement entitlement
          WHERE entitlement.tenant_id = role_permission.tenant_id
            AND entitlement.permission_id = role_permission.permission_id
            AND entitlement.deleted_at IS NULL
            AND entitlement.is_enabled = true
      );

    INSERT INTO iam_authorization_snapshot (
        tenant_id, user_id, auth_version, role_ids, permission_codes, menu_codes, column_settings,
        snapshot_hash, built_at, created_by, updated_by
    )
    SELECT
        p_tenant_id,
        v_admin_user_id,
        1,
        COALESCE((
            SELECT jsonb_agg(role.id ORDER BY role.code)
            FROM iam_user_role user_role
            JOIN iam_role role ON role.id = user_role.role_id
            WHERE user_role.tenant_id = p_tenant_id
              AND user_role.user_id = v_admin_user_id
              AND user_role.deleted_at IS NULL
              AND role.deleted_at IS NULL
        ), '[]'::jsonb),
        COALESCE((
            SELECT jsonb_agg(code ORDER BY code)
            FROM (
                SELECT DISTINCT permission.code
                FROM iam_user_role user_role
                JOIN iam_role role ON role.id = user_role.role_id
                JOIN iam_role_permission role_permission ON role_permission.tenant_id = user_role.tenant_id
                                                        AND role_permission.role_id = role.id
                                                        AND role_permission.deleted_at IS NULL
                JOIN iam_permission permission ON permission.id = role_permission.permission_id
                                              AND permission.deleted_at IS NULL
                                              AND permission.is_enabled = true
                WHERE user_role.tenant_id = p_tenant_id
                  AND user_role.user_id = v_admin_user_id
                  AND user_role.deleted_at IS NULL
                  AND role.deleted_at IS NULL
            ) active_permission
        ), '[]'::jsonb),
        COALESCE((
            SELECT jsonb_agg(menu.code ORDER BY menu.sort_no, menu.code)
            FROM iam_tenant_menu tenant_menu
            JOIN iam_menu menu ON menu.id = tenant_menu.menu_id
            WHERE tenant_menu.tenant_id = p_tenant_id
              AND tenant_menu.deleted_at IS NULL
              AND menu.deleted_at IS NULL
        ), '[]'::jsonb),
        '{}'::jsonb,
        'tenant_permission_entitlement:' || v_template_code || ':' || p_tenant_id || ':' || v_admin_user_id,
        now(),
        p_requested_by,
        p_requested_by
    ON CONFLICT (tenant_id, user_id) DO UPDATE
    SET auth_version = EXCLUDED.auth_version,
        role_ids = EXCLUDED.role_ids,
        permission_codes = EXCLUDED.permission_codes,
        menu_codes = EXCLUDED.menu_codes,
        column_settings = EXCLUDED.column_settings,
        snapshot_hash = EXCLUDED.snapshot_hash,
        built_at = EXCLUDED.built_at,
        updated_by = EXCLUDED.updated_by,
        updated_at = now();

    INSERT INTO iam_tenant_bootstrap_task (
        tenant_id,
        task_key,
        status,
        idempotency_key,
        requested_by,
        menu_grant_count,
        started_at,
        finished_at,
        created_by,
        updated_by
    )
    SELECT
        p_tenant_id,
        v_task_key,
        'SUCCEEDED',
        v_idempotency_key,
        p_requested_by,
        v_inserted_count,
        now(),
        now(),
        p_requested_by,
        p_requested_by
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_tenant_bootstrap_task existing
        WHERE existing.idempotency_key = v_idempotency_key
    );

    INSERT INTO iam_outbox_event (
        tenant_id,
        event_id,
        aggregate_type,
        aggregate_id,
        event_type,
        topic,
        payload,
        headers,
        status,
        next_retry_at,
        created_by,
        updated_by
    )
    VALUES (
        p_tenant_id,
        v_event_id,
        'IAM_TENANT',
        p_tenant_id::text,
        'IamTenantBootstrapped',
        'iam.tenant.bootstrapped',
        jsonb_build_object(
            'tenantId', p_tenant_id,
            'menuGrantCount', v_inserted_count,
            'adminUsername', v_admin_username,
            'iamInitTemplateCode', v_template_code,
            'permissionCodes', v_permission_codes,
            'assignedRoleCodes', COALESCE((
                SELECT jsonb_agg(role_template.role_code ORDER BY role_template.sort_order, role_template.role_code)
                FROM iam_tenant_init_role_template role_template
                WHERE role_template.init_template_code = v_template_code
                  AND role_template.is_enabled = true
                  AND role_template.deleted_at IS NULL
                  AND role_template.assign_to_admin = true
            ), '[]'::jsonb),
            'idempotencyKey', v_idempotency_key,
            'requestedBy', p_requested_by
        ),
        jsonb_build_object(
            'eventName', 'IamTenantBootstrapped',
            'source', 'xuan-iam'
        ),
        'PENDING',
        now(),
        p_requested_by,
        p_requested_by
    )
    ON CONFLICT (event_id) DO NOTHING;

    RETURN v_inserted_count;
EXCEPTION WHEN OTHERS THEN
    INSERT INTO iam_tenant_bootstrap_task (
        tenant_id,
        task_key,
        status,
        idempotency_key,
        requested_by,
        menu_grant_count,
        started_at,
        finished_at,
        last_error_message,
        created_by,
        updated_by
    )
    VALUES (
        p_tenant_id,
        COALESCE(v_task_key, 'IAM_TENANT_BOOTSTRAP'),
        'FAILED',
        COALESCE(v_idempotency_key, 'iam:tenant:' || COALESCE(p_tenant_id::text, 'null') || ':bootstrap:v1'),
        p_requested_by,
        0,
        now(),
        now(),
        SQLERRM,
        p_requested_by,
        p_requested_by
    );
    RAISE;
END;
$$;

COMMENT ON FUNCTION bootstrap_iam_tenant(bigint, varchar, varchar, varchar, varchar, varchar, varchar, varchar)
    IS '按初始化模板同步 IAM 租户权限池、菜单、默认角色、角色权限、管理员角色绑定、授权快照和 outbox 事件；模板切换时会裁剪超出租户权限池的角色授权。';
