-- Add stable tenant-to-IAM-init-template binding.
-- The permission entitlement rows are details, not a reliable source for "which tenants belong to a template".

CREATE TABLE IF NOT EXISTS iam_tenant_init_template_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    init_template_code varchar(64) NOT NULL,
    last_entitlement_version bigint DEFAULT 1 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_tenant_init_template_binding PRIMARY KEY (id)
);

COMMENT ON TABLE iam_tenant_init_template_binding IS 'IAM 租户初始化模板绑定表，稳定记录租户当前归属哪个初始化模板。';
COMMENT ON COLUMN iam_tenant_init_template_binding.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_tenant_init_template_binding.init_template_code IS '当前绑定的 IAM 初始化模板编码';
COMMENT ON COLUMN iam_tenant_init_template_binding.last_entitlement_version IS '最近一次同步到租户权限池的版本号';
COMMENT ON COLUMN iam_tenant_init_template_binding.is_enabled IS '是否启用';

CREATE UNIQUE INDEX IF NOT EXISTS uk_iam_tenant_init_template_binding_tenant_active
    ON iam_tenant_init_template_binding (tenant_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_tenant_init_template_binding_template
    ON iam_tenant_init_template_binding (init_template_code, tenant_id)
    WHERE deleted_at IS NULL;

WITH latest_bootstrap_template AS (
    SELECT DISTINCT ON (event.tenant_id)
           event.tenant_id,
           NULLIF(event.payload ->> 'iamInitTemplateCode', '') AS init_template_code
    FROM iam_outbox_event event
    WHERE event.event_type = 'IamTenantBootstrapped'
      AND event.tenant_id > 0
      AND event.payload ? 'iamInitTemplateCode'
    ORDER BY event.tenant_id, event.updated_at DESC, event.created_at DESC, event.id DESC
),
active_entitlement_template AS (
    SELECT DISTINCT ON (entitlement.tenant_id)
           entitlement.tenant_id,
           entitlement.init_template_code,
           MAX(entitlement.entitlement_version) OVER (PARTITION BY entitlement.tenant_id) AS last_entitlement_version
    FROM iam_tenant_permission_entitlement entitlement
    WHERE entitlement.tenant_id > 0
      AND entitlement.deleted_at IS NULL
      AND entitlement.is_enabled = true
      AND entitlement.init_template_code IS NOT NULL
      AND btrim(entitlement.init_template_code) <> ''
      AND entitlement.init_template_code <> 'legacy-current-role-permissions'
    ORDER BY entitlement.tenant_id, entitlement.entitlement_version DESC, entitlement.id DESC
),
binding_seed AS (
    SELECT active_entitlement_template.tenant_id,
           active_entitlement_template.init_template_code,
           active_entitlement_template.last_entitlement_version
    FROM active_entitlement_template
    UNION
    SELECT latest_bootstrap_template.tenant_id,
           latest_bootstrap_template.init_template_code,
           1
    FROM latest_bootstrap_template
    WHERE latest_bootstrap_template.init_template_code IS NOT NULL
      AND NOT EXISTS (
          SELECT 1
          FROM active_entitlement_template
          WHERE active_entitlement_template.tenant_id = latest_bootstrap_template.tenant_id
      )
)
INSERT INTO iam_tenant_init_template_binding (
    tenant_id, init_template_code, last_entitlement_version, is_enabled, created_by, updated_by
)
SELECT binding_seed.tenant_id,
       binding_seed.init_template_code,
       binding_seed.last_entitlement_version,
       true,
       'system',
       'system'
FROM binding_seed
WHERE binding_seed.init_template_code IS NOT NULL
ON CONFLICT (tenant_id) WHERE deleted_at IS NULL DO UPDATE
SET init_template_code = EXCLUDED.init_template_code,
    last_entitlement_version = EXCLUDED.last_entitlement_version,
    is_enabled = true,
    updated_by = 'system',
    updated_at = now();

CREATE OR REPLACE FUNCTION upsert_iam_tenant_init_template_binding_from_entitlement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tenant_id IS NOT NULL
       AND NEW.tenant_id > 0
       AND NEW.deleted_at IS NULL
       AND NEW.is_enabled = true
       AND NEW.init_template_code IS NOT NULL
       AND btrim(NEW.init_template_code) <> ''
       AND NEW.init_template_code <> 'legacy-current-role-permissions' THEN
        INSERT INTO iam_tenant_init_template_binding (
            tenant_id, init_template_code, last_entitlement_version, is_enabled, created_by, updated_by
        )
        VALUES (
            NEW.tenant_id,
            NEW.init_template_code,
            COALESCE(NEW.entitlement_version, 1),
            true,
            COALESCE(NEW.updated_by, NEW.created_by, 'system'),
            COALESCE(NEW.updated_by, NEW.created_by, 'system')
        )
        ON CONFLICT (tenant_id) WHERE deleted_at IS NULL DO UPDATE
        SET init_template_code = EXCLUDED.init_template_code,
            last_entitlement_version = GREATEST(
                iam_tenant_init_template_binding.last_entitlement_version,
                EXCLUDED.last_entitlement_version
            ),
            is_enabled = true,
            updated_by = EXCLUDED.updated_by,
            updated_at = now();
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_iam_tenant_permission_entitlement_bind_template
    ON iam_tenant_permission_entitlement;

CREATE TRIGGER trg_iam_tenant_permission_entitlement_bind_template
AFTER INSERT OR UPDATE OF init_template_code, entitlement_version, deleted_at, is_enabled
ON iam_tenant_permission_entitlement
FOR EACH ROW
EXECUTE FUNCTION upsert_iam_tenant_init_template_binding_from_entitlement();

COMMENT ON FUNCTION upsert_iam_tenant_init_template_binding_from_entitlement()
    IS '维护租户初始化模板绑定；bootstrap_iam_tenant 写入权限池明细时同步刷新绑定，避免模板变更时查不到归属租户。';
