-- IAM tenant bootstrap outbox event
-- This migration extends the V1 bootstrap function without rewriting migration history.

CREATE TABLE IF NOT EXISTS iam_outbox_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    event_id varchar(160) NOT NULL,
    aggregate_type varchar(80) DEFAULT 'IAM_TENANT' NOT NULL,
    aggregate_id varchar(120) NOT NULL,
    event_type varchar(120) NOT NULL,
    topic varchar(160) NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    headers jsonb DEFAULT '{}'::jsonb NOT NULL,
    status varchar(30) DEFAULT 'PENDING' NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retry_count integer DEFAULT 10 NOT NULL,
    locked_by varchar(100),
    locked_at timestamptz,
    lock_expires_at timestamptz,
    next_retry_at timestamptz DEFAULT now() NOT NULL,
    published_at timestamptz,
    last_error_code varchar(120),
    last_error_message text,
    first_failed_at timestamptz,
    dead_letter_at timestamptz,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_iam_outbox_event PRIMARY KEY (id)
);
COMMENT ON TABLE iam_outbox_event IS 'IAM 服务 Outbox 事件表，在本地事务内记录待发布领域事件，避免业务写入成功但事件丢失。';
COMMENT ON COLUMN iam_outbox_event.id IS '主键';
COMMENT ON COLUMN iam_outbox_event.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN iam_outbox_event.event_id IS '事件 ID';
COMMENT ON COLUMN iam_outbox_event.aggregate_type IS '聚合类型';
COMMENT ON COLUMN iam_outbox_event.aggregate_id IS '聚合 ID';
COMMENT ON COLUMN iam_outbox_event.event_type IS '事件类型';
COMMENT ON COLUMN iam_outbox_event.topic IS '事件主题';
COMMENT ON COLUMN iam_outbox_event.payload IS '事件载荷';
COMMENT ON COLUMN iam_outbox_event.headers IS '事件头';
COMMENT ON COLUMN iam_outbox_event.status IS '发布状态';
COMMENT ON COLUMN iam_outbox_event.retry_count IS '已重试次数';
COMMENT ON COLUMN iam_outbox_event.max_retry_count IS '最大重试次数';
COMMENT ON COLUMN iam_outbox_event.locked_by IS '当前发布锁持有者';
COMMENT ON COLUMN iam_outbox_event.locked_at IS '锁定时间';
COMMENT ON COLUMN iam_outbox_event.lock_expires_at IS '锁过期时间';
COMMENT ON COLUMN iam_outbox_event.next_retry_at IS '下次重试时间';
COMMENT ON COLUMN iam_outbox_event.published_at IS '发布时间';
COMMENT ON COLUMN iam_outbox_event.last_error_code IS '最近错误码';
COMMENT ON COLUMN iam_outbox_event.last_error_message IS '最近错误信息';
COMMENT ON COLUMN iam_outbox_event.first_failed_at IS '首次失败时间';
COMMENT ON COLUMN iam_outbox_event.dead_letter_at IS '进入死信时间';
COMMENT ON COLUMN iam_outbox_event.created_by IS '创建人';
COMMENT ON COLUMN iam_outbox_event.created_at IS '创建时间';
COMMENT ON COLUMN iam_outbox_event.updated_by IS '更新人';
COMMENT ON COLUMN iam_outbox_event.updated_at IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_outbox_event_id
    ON iam_outbox_event (event_id);
CREATE INDEX IF NOT EXISTS idx_iam_outbox_event_pending
    ON iam_outbox_event (status, next_retry_at, id);
CREATE INDEX IF NOT EXISTS idx_iam_outbox_event_lock
    ON iam_outbox_event (status, lock_expires_at, id);
CREATE INDEX IF NOT EXISTS idx_iam_outbox_event_dead_letter
    ON iam_outbox_event (status, dead_letter_at, id);
CREATE INDEX IF NOT EXISTS idx_iam_outbox_event_aggregate
    ON iam_outbox_event (aggregate_type, aggregate_id, id);

CREATE OR REPLACE FUNCTION bootstrap_iam_tenant(
    p_tenant_id bigint,
    p_requested_by varchar DEFAULT 'tenant-provision'
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_inserted_count integer := 0;
    v_task_key varchar(160);
    v_idempotency_key varchar(200);
    v_event_id varchar(160);
BEGIN
    IF p_tenant_id IS NULL OR p_tenant_id <= 0 THEN
        RAISE EXCEPTION 'p_tenant_id must be a positive tenant id';
    END IF;

    v_task_key := 'IAM_TENANT_BOOTSTRAP';
    v_idempotency_key := 'iam:tenant:' || p_tenant_id || ':bootstrap:v1';
    v_event_id := v_idempotency_key || ':event';

    INSERT INTO iam_tenant_menu (tenant_id, menu_id, is_enabled, created_by, updated_by)
    SELECT p_tenant_id, iam_menu.id, true, p_requested_by, p_requested_by
    FROM iam_menu
    WHERE iam_menu.code IN (
        'workbench', 'product', 'party', 'warehouse', 'inventory', 'sales',
        'procurement', 'finance', 'document', 'manufacturing', 'report', 'system'
    )
      AND iam_menu.deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM iam_tenant_menu existing
          WHERE existing.tenant_id = p_tenant_id
            AND existing.menu_id = iam_menu.id
            AND existing.deleted_at IS NULL
      );

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

    INSERT INTO iam_tenant_bootstrap_task (
        tenant_id,
        task_key,
        status,
        idempotency_key,
        requested_by,
        menu_grant_count,
        started_at,
        finished_at,
        created_by,
        updated_by
    )
    SELECT
        p_tenant_id,
        v_task_key,
        'SUCCEEDED',
        v_idempotency_key,
        p_requested_by,
        v_inserted_count,
        now(),
        now(),
        p_requested_by,
        p_requested_by
    WHERE NOT EXISTS (
        SELECT 1
        FROM iam_tenant_bootstrap_task existing
        WHERE existing.idempotency_key = v_idempotency_key
    );

    INSERT INTO iam_outbox_event (
        tenant_id,
        event_id,
        aggregate_type,
        aggregate_id,
        event_type,
        topic,
        payload,
        headers,
        status,
        next_retry_at,
        created_by,
        updated_by
    )
    VALUES (
        p_tenant_id,
        v_event_id,
        'IAM_TENANT',
        p_tenant_id::text,
        'IamTenantBootstrapped',
        'iam.tenant.bootstrapped',
        jsonb_build_object(
            'tenantId', p_tenant_id,
            'menuGrantCount', v_inserted_count,
            'idempotencyKey', v_idempotency_key,
            'requestedBy', p_requested_by
        ),
        jsonb_build_object(
            'eventName', 'IamTenantBootstrapped',
            'source', 'xuan-iam'
        ),
        'PENDING',
        now(),
        p_requested_by,
        p_requested_by
    )
    ON CONFLICT (event_id) DO NOTHING;

    RETURN v_inserted_count;
EXCEPTION WHEN OTHERS THEN
    INSERT INTO iam_tenant_bootstrap_task (
        tenant_id,
        task_key,
        status,
        idempotency_key,
        requested_by,
        menu_grant_count,
        started_at,
        finished_at,
        last_error_message,
        created_by,
        updated_by
    )
    VALUES (
        p_tenant_id,
        COALESCE(v_task_key, 'IAM_TENANT_BOOTSTRAP'),
        'FAILED',
        COALESCE(v_idempotency_key, 'iam:tenant:' || COALESCE(p_tenant_id::text, 'null') || ':bootstrap:v1'),
        p_requested_by,
        0,
        now(),
        now(),
        SQLERRM,
        p_requested_by,
        p_requested_by
    );
    RAISE;
END;
$$;
COMMENT ON FUNCTION bootstrap_iam_tenant(bigint, varchar) IS '按 xuan-tenant 传入的真实 tenantId 幂等初始化 IAM 租户菜单授权，并写入 IamTenantBootstrapped outbox 事件。';
