-- Add consumable column permission templates.

CREATE TABLE IF NOT EXISTS iam_resource_column (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource_key varchar(120) NOT NULL,
    column_key varchar(120) NOT NULL,
    column_name varchar(200) NOT NULL,
    data_type varchar(60),
    mask_type varchar(60),
    is_enabled boolean DEFAULT true NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_resource_column PRIMARY KEY (id)
);
COMMENT ON TABLE iam_resource_column IS 'IAM 资源字段清单，定义业务资源可参与列权限控制的字段。';
COMMENT ON COLUMN iam_resource_column.id IS '主键';
COMMENT ON COLUMN iam_resource_column.resource_key IS '资源标识，例如 tenant 表示租户列表资源';
COMMENT ON COLUMN iam_resource_column.column_key IS '字段标识，对应业务接口 DTO 字段名';
COMMENT ON COLUMN iam_resource_column.column_name IS '字段中文名称';
COMMENT ON COLUMN iam_resource_column.data_type IS '字段数据类型，用于前端展示和后续规则扩展';
COMMENT ON COLUMN iam_resource_column.mask_type IS '脱敏类型，例如 PHONE 表示手机号脱敏';
COMMENT ON COLUMN iam_resource_column.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_resource_column.sort_no IS '排序';
COMMENT ON COLUMN iam_resource_column.created_by IS '创建人';
COMMENT ON COLUMN iam_resource_column.created_at IS '创建时间';
COMMENT ON COLUMN iam_resource_column.updated_by IS '更新人';
COMMENT ON COLUMN iam_resource_column.updated_at IS '更新时间';
COMMENT ON COLUMN iam_resource_column.deleted_by IS '删除人';
COMMENT ON COLUMN iam_resource_column.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_resource_column.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_resource_column_key_active
    ON iam_resource_column (resource_key, column_key)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_resource_column_resource
    ON iam_resource_column (resource_key, is_enabled, sort_no)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_column_permission_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(120) NOT NULL,
    name varchar(200) NOT NULL,
    description varchar(500),
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_column_permission_template PRIMARY KEY (id)
);
COMMENT ON TABLE iam_column_permission_template IS 'IAM 列权限模板，角色通过绑定模板获得字段可见、脱敏或隐藏规则。';
COMMENT ON COLUMN iam_column_permission_template.id IS '主键';
COMMENT ON COLUMN iam_column_permission_template.tenant_id IS '租户 ID，0 表示平台默认模板';
COMMENT ON COLUMN iam_column_permission_template.code IS '模板编码';
COMMENT ON COLUMN iam_column_permission_template.name IS '模板名称';
COMMENT ON COLUMN iam_column_permission_template.description IS '模板描述';
COMMENT ON COLUMN iam_column_permission_template.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_column_permission_template.created_by IS '创建人';
COMMENT ON COLUMN iam_column_permission_template.created_at IS '创建时间';
COMMENT ON COLUMN iam_column_permission_template.updated_by IS '更新人';
COMMENT ON COLUMN iam_column_permission_template.updated_at IS '更新时间';
COMMENT ON COLUMN iam_column_permission_template.deleted_by IS '删除人';
COMMENT ON COLUMN iam_column_permission_template.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_column_permission_template.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_column_permission_template_code_active
    ON iam_column_permission_template (tenant_id, code)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_column_permission_template_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id bigint NOT NULL,
    resource_column_id bigint NOT NULL,
    access_mode varchar(30) NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_column_permission_template_item PRIMARY KEY (id),
    CONSTRAINT ck_iam_column_permission_template_item_access
        CHECK (access_mode IN ('VISIBLE', 'MASKED', 'HIDDEN'))
);
COMMENT ON TABLE iam_column_permission_template_item IS 'IAM 列权限模板明细，定义模板中每个字段的访问级别。';
COMMENT ON COLUMN iam_column_permission_template_item.id IS '主键';
COMMENT ON COLUMN iam_column_permission_template_item.template_id IS '列权限模板 ID';
COMMENT ON COLUMN iam_column_permission_template_item.resource_column_id IS '资源字段 ID';
COMMENT ON COLUMN iam_column_permission_template_item.access_mode IS '访问级别：VISIBLE 明文可见，MASKED 脱敏可见，HIDDEN 隐藏不可见';
COMMENT ON COLUMN iam_column_permission_template_item.created_by IS '创建人';
COMMENT ON COLUMN iam_column_permission_template_item.created_at IS '创建时间';
COMMENT ON COLUMN iam_column_permission_template_item.updated_by IS '更新人';
COMMENT ON COLUMN iam_column_permission_template_item.updated_at IS '更新时间';
COMMENT ON COLUMN iam_column_permission_template_item.deleted_by IS '删除人';
COMMENT ON COLUMN iam_column_permission_template_item.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_column_permission_template_item.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_column_permission_template_item_active
    ON iam_column_permission_template_item (template_id, resource_column_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_column_permission_template_item_column
    ON iam_column_permission_template_item (resource_column_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_role_column_permission_template_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    role_id bigint NOT NULL,
    template_id bigint NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_role_column_permission_template_binding PRIMARY KEY (id)
);
COMMENT ON TABLE iam_role_column_permission_template_binding IS 'IAM 角色列权限模板绑定表，一个角色第一版绑定一个列权限模板。';
COMMENT ON COLUMN iam_role_column_permission_template_binding.id IS '主键';
COMMENT ON COLUMN iam_role_column_permission_template_binding.tenant_id IS '租户 ID，必须与角色租户一致';
COMMENT ON COLUMN iam_role_column_permission_template_binding.role_id IS '角色 ID';
COMMENT ON COLUMN iam_role_column_permission_template_binding.template_id IS '列权限模板 ID';
COMMENT ON COLUMN iam_role_column_permission_template_binding.created_by IS '创建人';
COMMENT ON COLUMN iam_role_column_permission_template_binding.created_at IS '创建时间';
COMMENT ON COLUMN iam_role_column_permission_template_binding.updated_by IS '更新人';
COMMENT ON COLUMN iam_role_column_permission_template_binding.updated_at IS '更新时间';
COMMENT ON COLUMN iam_role_column_permission_template_binding.deleted_by IS '删除人';
COMMENT ON COLUMN iam_role_column_permission_template_binding.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_role_column_permission_template_binding.deleted_at IS '逻辑删除时间';
CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_role_column_template_binding_role_active
    ON iam_role_column_permission_template_binding (tenant_id, role_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_iam_role_column_template_binding_template
    ON iam_role_column_permission_template_binding (template_id)
    WHERE deleted_at IS NULL;

INSERT INTO iam_resource_column (
    resource_key, column_key, column_name, data_type, mask_type, is_enabled, sort_no, created_by, updated_by
)
SELECT seed.resource_key, seed.column_key, seed.column_name, seed.data_type, seed.mask_type, true, seed.sort_no, 'system', 'system'
FROM (
    VALUES
    ('tenant', 'code', '租户编码', 'STRING', NULL, 10),
    ('tenant', 'name', '租户名称', 'STRING', NULL, 20),
    ('tenant', 'status', '租户状态', 'ENUM', NULL, 30),
    ('tenant', 'contactName', '联系人', 'STRING', NULL, 40),
    ('tenant', 'contactPhone', '联系电话', 'STRING', 'PHONE', 50),
    ('tenant', 'remark', '备注', 'STRING', NULL, 60),
    ('tenant', 'currentPlanName', '当前套餐名称', 'STRING', NULL, 70),
    ('tenant', 'primaryDomain', '主域名', 'STRING', NULL, 80)
) AS seed(resource_key, column_key, column_name, data_type, mask_type, sort_no)
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_resource_column existing
    WHERE existing.resource_key = seed.resource_key
      AND existing.column_key = seed.column_key
      AND existing.deleted_at IS NULL
);

INSERT INTO iam_column_permission_template (
    tenant_id, code, name, description, is_enabled, created_by, updated_by
)
SELECT seed.tenant_id, seed.code, seed.name, seed.description, true, 'system', 'system'
FROM (
    VALUES
    (0::bigint, 'tenant_admin_default', '租户管理列权限模板', '租户管理页面默认明文模板'),
    (0::bigint, 'tenant_readonly_masked', '租户只读列权限模板', '租户只读页面隐藏备注并脱敏联系电话')
) AS seed(tenant_id, code, name, description)
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_column_permission_template existing
    WHERE existing.tenant_id = seed.tenant_id
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);

WITH template_items(template_code, column_key, access_mode) AS (
    VALUES
    ('tenant_admin_default', 'code', 'VISIBLE'),
    ('tenant_admin_default', 'name', 'VISIBLE'),
    ('tenant_admin_default', 'status', 'VISIBLE'),
    ('tenant_admin_default', 'contactName', 'VISIBLE'),
    ('tenant_admin_default', 'contactPhone', 'VISIBLE'),
    ('tenant_admin_default', 'remark', 'VISIBLE'),
    ('tenant_admin_default', 'currentPlanName', 'VISIBLE'),
    ('tenant_admin_default', 'primaryDomain', 'VISIBLE'),
    ('tenant_readonly_masked', 'code', 'VISIBLE'),
    ('tenant_readonly_masked', 'name', 'VISIBLE'),
    ('tenant_readonly_masked', 'status', 'VISIBLE'),
    ('tenant_readonly_masked', 'contactName', 'HIDDEN'),
    ('tenant_readonly_masked', 'contactPhone', 'MASKED'),
    ('tenant_readonly_masked', 'remark', 'HIDDEN'),
    ('tenant_readonly_masked', 'currentPlanName', 'VISIBLE'),
    ('tenant_readonly_masked', 'primaryDomain', 'VISIBLE')
)
INSERT INTO iam_column_permission_template_item (
    template_id, resource_column_id, access_mode, created_by, updated_by
)
SELECT template.id, resource_column.id, template_items.access_mode, 'system', 'system'
FROM template_items
JOIN iam_column_permission_template template
  ON template.tenant_id = 0
 AND template.code = template_items.template_code
 AND template.deleted_at IS NULL
JOIN iam_resource_column resource_column
  ON resource_column.resource_key = 'tenant'
 AND resource_column.column_key = template_items.column_key
 AND resource_column.deleted_at IS NULL
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_column_permission_template_item existing
    WHERE existing.template_id = template.id
      AND existing.resource_column_id = resource_column.id
      AND existing.deleted_at IS NULL
);
