-- 追加租户可用列权限模板分配表；平台模板仍保存在 iam_column_permission_template，租户通过本表获得可用模板池。
CREATE TABLE IF NOT EXISTS iam_tenant_column_permission_template_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    template_id bigint NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_tenant_column_permission_template_assignment PRIMARY KEY (id)
);

COMMENT ON TABLE iam_tenant_column_permission_template_assignment IS '租户可用列权限模板分配表，定义租户内角色可以绑定哪些平台列权限模板。';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.id IS '主键';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.tenant_id IS '租户 ID，必须是业务租户';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.template_id IS '列权限模板 ID，指向平台列权限模板';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.is_default IS '是否为租户默认列权限模板';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.created_by IS '创建人';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.created_at IS '创建时间';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.updated_by IS '更新人';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.updated_at IS '更新时间';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.deleted_by IS '删除人';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_tenant_column_permission_template_assignment.deleted_at IS '逻辑删除时间';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_tenant_column_template_assignment_active
    ON iam_tenant_column_permission_template_assignment (tenant_id, template_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_tenant_column_template_assignment_default
    ON iam_tenant_column_permission_template_assignment (tenant_id)
    WHERE deleted_at IS NULL
      AND is_default = true;

WITH business_tenant AS (
    SELECT DISTINCT tenant_id
    FROM iam_role
    WHERE tenant_id > 0
      AND deleted_at IS NULL
    UNION
    SELECT DISTINCT tenant_id
    FROM iam_user
    WHERE tenant_id > 0
      AND deleted_at IS NULL
),
platform_template AS (
    SELECT id,
           code
    FROM iam_column_permission_template
    WHERE tenant_id = 0
      AND is_enabled = true
      AND deleted_at IS NULL
),
default_template AS (
    SELECT id
    FROM platform_template
    ORDER BY CASE WHEN code = 'tenant_admin_default' THEN 0 ELSE 1 END,
             code
    LIMIT 1
)
INSERT INTO iam_tenant_column_permission_template_assignment (
    tenant_id, template_id, is_default, created_by, updated_by
)
SELECT business_tenant.tenant_id,
       platform_template.id,
       platform_template.id = default_template.id,
       'system',
       'system'
FROM business_tenant
CROSS JOIN platform_template
LEFT JOIN default_template ON true
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_tenant_column_permission_template_assignment existing
    WHERE existing.tenant_id = business_tenant.tenant_id
      AND existing.template_id = platform_template.id
      AND existing.deleted_at IS NULL
);
