-- 追加角色独立列权限规则和管理页面；租户列权限模板池只作为角色可授权上限。
CREATE TABLE IF NOT EXISTS iam_role_column_permission_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    role_id bigint NOT NULL,
    resource_column_id bigint NOT NULL,
    access_mode varchar(30) NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_role_column_permission_rule PRIMARY KEY (id),
    CONSTRAINT ck_iam_role_column_permission_rule_access
        CHECK (access_mode IN ('VISIBLE', 'MASKED', 'HIDDEN'))
);

COMMENT ON TABLE iam_role_column_permission_rule IS '角色列权限规则表，定义租户内每个角色对资源字段的明文、脱敏或隐藏访问级别。';
COMMENT ON COLUMN iam_role_column_permission_rule.id IS '主键';
COMMENT ON COLUMN iam_role_column_permission_rule.tenant_id IS '租户 ID，必须与角色所属租户一致';
COMMENT ON COLUMN iam_role_column_permission_rule.role_id IS '角色 ID';
COMMENT ON COLUMN iam_role_column_permission_rule.resource_column_id IS '资源字段 ID';
COMMENT ON COLUMN iam_role_column_permission_rule.access_mode IS '访问级别：VISIBLE 明文可见，MASKED 脱敏可见，HIDDEN 隐藏不可见';
COMMENT ON COLUMN iam_role_column_permission_rule.created_by IS '创建人';
COMMENT ON COLUMN iam_role_column_permission_rule.created_at IS '创建时间';
COMMENT ON COLUMN iam_role_column_permission_rule.updated_by IS '更新人';
COMMENT ON COLUMN iam_role_column_permission_rule.updated_at IS '更新时间';
COMMENT ON COLUMN iam_role_column_permission_rule.deleted_by IS '删除人';
COMMENT ON COLUMN iam_role_column_permission_rule.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_role_column_permission_rule.deleted_at IS '逻辑删除时间';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_role_column_permission_rule_active
    ON iam_role_column_permission_rule (tenant_id, role_id, resource_column_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_role_column_permission_rule_role
    ON iam_role_column_permission_rule (tenant_id, role_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_role_column_permission_rule_column
    ON iam_role_column_permission_rule (resource_column_id)
    WHERE deleted_at IS NULL;

INSERT INTO iam_role_column_permission_rule (
    tenant_id, role_id, resource_column_id, access_mode, created_by, updated_by
)
SELECT DISTINCT binding.tenant_id,
       binding.role_id,
       template_item.resource_column_id,
       template_item.access_mode,
       'system-v37',
       'system-v37'
FROM iam_role_column_permission_template_binding binding
JOIN iam_column_permission_template template
  ON template.id = binding.template_id
 AND template.deleted_at IS NULL
 AND template.is_enabled = true
JOIN iam_column_permission_template_item template_item
  ON template_item.template_id = template.id
 AND template_item.deleted_at IS NULL
WHERE binding.deleted_at IS NULL
  AND (
      binding.tenant_id = 0
      OR EXISTS (
          SELECT 1
          FROM iam_tenant_column_permission_template_assignment assignment
          WHERE assignment.tenant_id = binding.tenant_id
            AND assignment.template_id = binding.template_id
            AND assignment.deleted_at IS NULL
      )
  )
  AND NOT EXISTS (
      SELECT 1
      FROM iam_role_column_permission_rule existing
      WHERE existing.tenant_id = binding.tenant_id
        AND existing.role_id = binding.role_id
        AND existing.resource_column_id = template_item.resource_column_id
        AND existing.deleted_at IS NULL
  );

WITH page_permission(code, name, menu_code, description) AS (
    VALUES
        ('iam-role-column-permission:view', '角色列权限查看', 'iam-role-column-permission-management', '查看角色独立列权限页面和字段规则'),
        ('iam-role-column-permission:update', '角色列权限修改', 'iam-role-column-permission-management', '修改角色独立列权限字段规则')
)
INSERT INTO iam_permission (
    code, name, service_name, menu_code, description, is_enabled, created_by, updated_by
)
SELECT code, name, 'xuan-iam', menu_code, description, true, 'system-v37', 'system-v37'
FROM page_permission
ON CONFLICT (code) WHERE deleted_at IS NULL DO UPDATE
SET name = EXCLUDED.name,
    service_name = EXCLUDED.service_name,
    menu_code = EXCLUDED.menu_code,
    description = EXCLUDED.description,
    is_enabled = true,
    deleted_by = NULL,
    delete_reason = NULL,
    deleted_at = NULL,
    updated_by = 'system-v37',
    updated_at = now();

WITH permission_center AS (
    SELECT id
    FROM iam_menu
    WHERE code = 'system-permission-center'
      AND deleted_at IS NULL
),
role_column_permission_menu(code, title, i18n_key, path, icon, permission_code, sort_no) AS (
    VALUES
        ('iam-role-column-permission-management', '角色列权限', 'route.iamRoleColumnPermissions', '/system/iam/role-column-permissions', 'ShieldCheck', 'iam-role-column-permission:view', 36)
)
INSERT INTO iam_menu (
    code, parent_id, title, i18n_key, path, icon, permission_code, sort_no, is_enabled, created_by, updated_by
)
SELECT
    role_column_permission_menu.code,
    permission_center.id,
    role_column_permission_menu.title,
    role_column_permission_menu.i18n_key,
    role_column_permission_menu.path,
    role_column_permission_menu.icon,
    role_column_permission_menu.permission_code,
    role_column_permission_menu.sort_no,
    true,
    'system-v37',
    'system-v37'
FROM role_column_permission_menu
CROSS JOIN permission_center
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_menu existing
    WHERE existing.code = role_column_permission_menu.code
      AND existing.deleted_at IS NULL
);

WITH permission_center AS (
    SELECT id
    FROM iam_menu
    WHERE code = 'system-permission-center'
      AND deleted_at IS NULL
),
role_column_permission_menu(code, title, i18n_key, path, icon, permission_code, sort_no) AS (
    VALUES
        ('iam-role-column-permission-management', '角色列权限', 'route.iamRoleColumnPermissions', '/system/iam/role-column-permissions', 'ShieldCheck', 'iam-role-column-permission:view', 36)
)
UPDATE iam_menu menu
SET parent_id = permission_center.id,
    title = role_column_permission_menu.title,
    i18n_key = role_column_permission_menu.i18n_key,
    path = role_column_permission_menu.path,
    icon = role_column_permission_menu.icon,
    permission_code = role_column_permission_menu.permission_code,
    sort_no = role_column_permission_menu.sort_no,
    is_enabled = true,
    updated_by = 'system-v37',
    updated_at = now()
FROM role_column_permission_menu
CROSS JOIN permission_center
WHERE menu.code = role_column_permission_menu.code
  AND menu.deleted_at IS NULL;

WITH source_grant(old_code, new_code) AS (
    VALUES
        ('iam-column-permission:view', 'iam-role-column-permission:view'),
        ('iam-column-permission:update', 'iam-role-column-permission:update')
),
role_grant AS (
    SELECT DISTINCT role_permission.tenant_id,
           role_permission.role_id,
           new_permission.id AS permission_id,
           COALESCE(role_permission.created_by, 'system-v37') AS created_by
    FROM iam_role_permission role_permission
    JOIN iam_permission old_permission
      ON old_permission.id = role_permission.permission_id
    JOIN source_grant
      ON source_grant.old_code = old_permission.code
    JOIN iam_permission new_permission
      ON new_permission.code = source_grant.new_code
    WHERE role_permission.deleted_at IS NULL
)
INSERT INTO iam_role_permission (
    tenant_id, role_id, permission_id, created_by, updated_by
)
SELECT tenant_id, role_id, permission_id, created_by, 'system-v37'
FROM role_grant
ON CONFLICT (tenant_id, role_id, permission_id) WHERE deleted_at IS NULL DO UPDATE
SET deleted_by = NULL,
    delete_reason = NULL,
    deleted_at = NULL,
    updated_by = 'system-v37',
    updated_at = now();

WITH source_entitlement(old_code, new_code) AS (
    VALUES
        ('iam-column-permission:view', 'iam-role-column-permission:view'),
        ('iam-column-permission:update', 'iam-role-column-permission:update')
),
tenant_entitlement AS (
    SELECT DISTINCT entitlement.tenant_id,
           entitlement.init_template_code,
           new_permission.id AS permission_id,
           entitlement.entitlement_version,
           COALESCE(entitlement.created_by, 'system-v37') AS created_by
    FROM iam_tenant_permission_entitlement entitlement
    JOIN iam_permission old_permission
      ON old_permission.id = entitlement.permission_id
    JOIN source_entitlement
      ON source_entitlement.old_code = old_permission.code
    JOIN iam_permission new_permission
      ON new_permission.code = source_entitlement.new_code
    WHERE entitlement.deleted_at IS NULL
)
INSERT INTO iam_tenant_permission_entitlement (
    tenant_id, init_template_code, permission_id, entitlement_version, created_by, updated_by
)
SELECT tenant_id, init_template_code, permission_id, entitlement_version, created_by, 'system-v37'
FROM tenant_entitlement
ON CONFLICT (tenant_id, permission_id) WHERE deleted_at IS NULL DO UPDATE
SET init_template_code = EXCLUDED.init_template_code,
    entitlement_version = EXCLUDED.entitlement_version,
    is_enabled = true,
    deleted_by = NULL,
    delete_reason = NULL,
    deleted_at = NULL,
    updated_by = 'system-v37',
    updated_at = now();

UPDATE iam_tenant_init_permission_template template
SET permission_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(template.permission_codes) AS code
                UNION ALL
                SELECT source_permission.new_code
                FROM jsonb_array_elements_text(template.permission_codes) existing(code)
                JOIN (
                    VALUES
                        ('iam-column-permission:view', 'iam-role-column-permission:view'),
                        ('iam-column-permission:update', 'iam-role-column-permission:update')
                ) AS source_permission(old_code, new_code)
                  ON source_permission.old_code = existing.code
            ) expanded
        ) distinct_code
    ),
    updated_by = 'system-v37',
    updated_at = now()
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(template.permission_codes) existing(code)
    WHERE existing.code IN ('iam-column-permission:view', 'iam-column-permission:update')
);

UPDATE iam_tenant_init_role_template role_template
SET permission_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(role_template.permission_codes) AS code
                UNION ALL
                SELECT source_permission.new_code
                FROM jsonb_array_elements_text(role_template.permission_codes) existing(code)
                JOIN (
                    VALUES
                        ('iam-column-permission:view', 'iam-role-column-permission:view'),
                        ('iam-column-permission:update', 'iam-role-column-permission:update')
                ) AS source_permission(old_code, new_code)
                  ON source_permission.old_code = existing.code
            ) expanded
        ) distinct_code
    ),
    updated_by = 'system-v37',
    updated_at = now()
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(role_template.permission_codes) existing(code)
    WHERE existing.code IN ('iam-column-permission:view', 'iam-column-permission:update')
);

INSERT INTO iam_tenant_menu (tenant_id, menu_id, is_enabled, created_by, updated_by)
SELECT DISTINCT tenant_menu.tenant_id,
       menu.id,
       true,
       'system-v37',
       'system-v37'
FROM iam_tenant_menu tenant_menu
CROSS JOIN iam_menu menu
WHERE tenant_menu.deleted_at IS NULL
  AND menu.code = 'iam-role-column-permission-management'
  AND menu.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM iam_tenant_menu existing
      WHERE existing.tenant_id = tenant_menu.tenant_id
        AND existing.menu_id = menu.id
        AND existing.deleted_at IS NULL
  );

UPDATE iam_authorization_snapshot snapshot
SET permission_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) AS code
                UNION ALL
                SELECT source_permission.new_code
                FROM jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) existing(code)
                JOIN (
                    VALUES
                        ('iam-column-permission:view', 'iam-role-column-permission:view'),
                        ('iam-column-permission:update', 'iam-role-column-permission:update')
                ) AS source_permission(old_code, new_code)
                  ON source_permission.old_code = existing.code
            ) expanded
        ) distinct_code
    ),
    menu_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(COALESCE(snapshot.menu_codes, '[]'::jsonb)) AS code
                UNION ALL
                SELECT 'iam-role-column-permission-management'
                WHERE EXISTS (
                    SELECT 1
                    FROM jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) existing(code)
                    WHERE existing.code = 'iam-column-permission:view'
                )
            ) expanded
        ) distinct_code
    ),
    column_settings = COALESCE((
        SELECT jsonb_object_agg(resource_key, columns_json)
        FROM (
            SELECT resource_key,
                   jsonb_object_agg(column_key, access_mode ORDER BY column_key) AS columns_json
            FROM (
                SELECT DISTINCT ON (resource_column.resource_key, resource_column.column_key)
                       resource_column.resource_key,
                       resource_column.column_key,
                       rule.access_mode
                FROM jsonb_array_elements_text(COALESCE(snapshot.role_ids, '[]'::jsonb)) role_id_text(role_id)
                JOIN iam_role_column_permission_rule rule
                  ON rule.tenant_id = snapshot.tenant_id
                 AND rule.role_id = role_id_text.role_id::bigint
                 AND rule.deleted_at IS NULL
                JOIN iam_resource_column resource_column
                  ON resource_column.id = rule.resource_column_id
                 AND resource_column.deleted_at IS NULL
                 AND resource_column.is_enabled = true
                ORDER BY resource_column.resource_key,
                         resource_column.column_key,
                         CASE rule.access_mode
                             WHEN 'VISIBLE' THEN 3
                             WHEN 'MASKED' THEN 2
                             ELSE 1
                         END DESC
            ) merged_rule
            GROUP BY resource_key
        ) resource_rule
    ), '{}'::jsonb),
    auth_version = snapshot.auth_version + 1,
    snapshot_hash = 'role-column-permissions-v37:' || snapshot.tenant_id || ':' || snapshot.user_id,
    updated_by = 'system-v37',
    updated_at = now()
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) existing(code)
    WHERE existing.code IN ('iam-column-permission:view', 'iam-column-permission:update')
)
OR EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(COALESCE(snapshot.role_ids, '[]'::jsonb)) role_id_text(role_id)
    JOIN iam_role_column_permission_rule rule
      ON rule.tenant_id = snapshot.tenant_id
     AND rule.role_id = role_id_text.role_id::bigint
     AND rule.deleted_at IS NULL
);
