-- 追加状态动作权限规则事实源、管理入口和历史授权回填。
-- 状态动作权限只负责“角色在资源状态下可执行哪些动作”，业务状态机仍由各业务服务 DDD 领域模型兜底。

CREATE TABLE IF NOT EXISTS iam_resource_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint DEFAULT 0 NOT NULL,
    resource_key varchar(120) NOT NULL,
    state_code varchar(120) NOT NULL,
    state_name varchar(120) NOT NULL,
    description varchar(500),
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    metadata_json JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_resource_state PRIMARY KEY (id)
);

COMMENT ON TABLE iam_resource_state IS 'IAM 资源状态定义表，登记业务资源可参与状态动作授权的状态。';
COMMENT ON COLUMN iam_resource_state.id IS '主键';
COMMENT ON COLUMN iam_resource_state.tenant_id IS '租户 ID，0 表示平台通用定义';
COMMENT ON COLUMN iam_resource_state.resource_key IS '业务资源标识，例如 sales-order';
COMMENT ON COLUMN iam_resource_state.state_code IS '状态编码，例如 DRAFT、SUBMITTED、APPROVED';
COMMENT ON COLUMN iam_resource_state.state_name IS '状态名称，例如 草稿、已提交、已审核';
COMMENT ON COLUMN iam_resource_state.description IS '状态说明';
COMMENT ON COLUMN iam_resource_state.sort_no IS '排序号';
COMMENT ON COLUMN iam_resource_state.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_resource_state.metadata_json IS '扩展元数据，例如展示颜色、标签类型等';
COMMENT ON COLUMN iam_resource_state.created_by IS '创建人';
COMMENT ON COLUMN iam_resource_state.created_at IS '创建时间';
COMMENT ON COLUMN iam_resource_state.updated_by IS '更新人';
COMMENT ON COLUMN iam_resource_state.updated_at IS '更新时间';
COMMENT ON COLUMN iam_resource_state.deleted_by IS '删除人';
COMMENT ON COLUMN iam_resource_state.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_resource_state.deleted_at IS '逻辑删除时间';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_resource_state_active
    ON iam_resource_state (tenant_id, resource_key, state_code)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_resource_state_resource
    ON iam_resource_state (resource_key, sort_no)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_resource_action (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint DEFAULT 0 NOT NULL,
    resource_key varchar(120) NOT NULL,
    action_code varchar(120) NOT NULL,
    action_name varchar(120) NOT NULL,
    permission_code varchar(120),
    description varchar(500),
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    metadata_json JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_resource_action PRIMARY KEY (id)
);

COMMENT ON TABLE iam_resource_action IS 'IAM 资源动作定义表，登记业务资源可参与状态动作授权的动作。';
COMMENT ON COLUMN iam_resource_action.id IS '主键';
COMMENT ON COLUMN iam_resource_action.tenant_id IS '租户 ID，0 表示平台通用定义';
COMMENT ON COLUMN iam_resource_action.resource_key IS '业务资源标识，例如 sales-order';
COMMENT ON COLUMN iam_resource_action.action_code IS '动作编码，例如 view、update、delete、submit、audit';
COMMENT ON COLUMN iam_resource_action.action_name IS '动作名称，例如 查看、编辑、删除、提交、审核';
COMMENT ON COLUMN iam_resource_action.permission_code IS '动作对应的基础权限码，例如 sales-order:delete';
COMMENT ON COLUMN iam_resource_action.description IS '动作说明';
COMMENT ON COLUMN iam_resource_action.sort_no IS '排序号';
COMMENT ON COLUMN iam_resource_action.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_resource_action.metadata_json IS '扩展元数据，例如按钮风险级别、二次确认提示等';
COMMENT ON COLUMN iam_resource_action.created_by IS '创建人';
COMMENT ON COLUMN iam_resource_action.created_at IS '创建时间';
COMMENT ON COLUMN iam_resource_action.updated_by IS '更新人';
COMMENT ON COLUMN iam_resource_action.updated_at IS '更新时间';
COMMENT ON COLUMN iam_resource_action.deleted_by IS '删除人';
COMMENT ON COLUMN iam_resource_action.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_resource_action.deleted_at IS '逻辑删除时间';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_resource_action_active
    ON iam_resource_action (tenant_id, resource_key, action_code)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_resource_action_resource
    ON iam_resource_action (resource_key, sort_no)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_resource_action_permission
    ON iam_resource_action (permission_code)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS iam_role_state_action_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    role_id bigint NOT NULL,
    resource_key varchar(120) NOT NULL,
    state_code varchar(120) NOT NULL,
    action_code varchar(120) NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_iam_role_state_action_rule PRIMARY KEY (id)
);

COMMENT ON TABLE iam_role_state_action_rule IS 'IAM 角色状态动作权限规则表，定义租户内角色在资源状态下允许执行的动作。';
COMMENT ON COLUMN iam_role_state_action_rule.id IS '主键';
COMMENT ON COLUMN iam_role_state_action_rule.tenant_id IS '租户 ID，必须与角色所属租户一致';
COMMENT ON COLUMN iam_role_state_action_rule.role_id IS '角色 ID';
COMMENT ON COLUMN iam_role_state_action_rule.resource_key IS '业务资源标识，例如 sales-order';
COMMENT ON COLUMN iam_role_state_action_rule.state_code IS '状态编码，例如 DRAFT、APPROVED';
COMMENT ON COLUMN iam_role_state_action_rule.action_code IS '动作编码，例如 submit、audit、delete';
COMMENT ON COLUMN iam_role_state_action_rule.is_enabled IS '是否启用';
COMMENT ON COLUMN iam_role_state_action_rule.created_by IS '创建人';
COMMENT ON COLUMN iam_role_state_action_rule.created_at IS '创建时间';
COMMENT ON COLUMN iam_role_state_action_rule.updated_by IS '更新人';
COMMENT ON COLUMN iam_role_state_action_rule.updated_at IS '更新时间';
COMMENT ON COLUMN iam_role_state_action_rule.deleted_by IS '删除人';
COMMENT ON COLUMN iam_role_state_action_rule.delete_reason IS '删除原因';
COMMENT ON COLUMN iam_role_state_action_rule.deleted_at IS '逻辑删除时间';

CREATE UNIQUE INDEX IF NOT EXISTS idx_iam_role_state_action_rule_active
    ON iam_role_state_action_rule (tenant_id, role_id, resource_key, state_code, action_code)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_role_state_action_rule_role
    ON iam_role_state_action_rule (tenant_id, role_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_iam_role_state_action_rule_resource_state
    ON iam_role_state_action_rule (tenant_id, resource_key, state_code)
    WHERE deleted_at IS NULL;

WITH page_permission(code, name, menu_code, description) AS (
    VALUES
        ('iam-state-action:view', '状态动作权限查看', 'iam-state-action-management', '查看状态动作权限定义和角色授权矩阵'),
        ('iam-state-action:create', '状态动作权限新增', 'iam-state-action-management', '新增资源状态和资源动作定义'),
        ('iam-state-action:update', '状态动作权限修改', 'iam-state-action-management', '修改资源状态、资源动作和角色状态动作授权')
)
INSERT INTO iam_permission (
    code, name, service_name, menu_code, description, is_enabled, created_by, updated_by
)
SELECT code, name, 'xuan-iam', menu_code, description, true, 'system-v48', 'system-v48'
FROM page_permission
ON CONFLICT (code) WHERE deleted_at IS NULL DO UPDATE
SET name = EXCLUDED.name,
    service_name = EXCLUDED.service_name,
    menu_code = EXCLUDED.menu_code,
    description = EXCLUDED.description,
    is_enabled = true,
    deleted_by = NULL,
    delete_reason = NULL,
    deleted_at = NULL,
    updated_by = 'system-v48',
    updated_at = now();

WITH permission_center AS (
    SELECT id
    FROM iam_menu
    WHERE code = 'system-permission-center'
      AND deleted_at IS NULL
),
state_action_menu(code, title, i18n_key, path, icon, permission_code, sort_no) AS (
    VALUES
        ('iam-state-action-management', '状态动作权限', 'route.iamStateActionPermissions', '/system/iam/state-action-permissions', 'ShieldCheck', 'iam-state-action:view', 38)
)
INSERT INTO iam_menu (
    code, parent_id, title, i18n_key, path, icon, permission_code, sort_no, is_enabled, created_by, updated_by
)
SELECT state_action_menu.code,
       permission_center.id,
       state_action_menu.title,
       state_action_menu.i18n_key,
       state_action_menu.path,
       state_action_menu.icon,
       state_action_menu.permission_code,
       state_action_menu.sort_no,
       true,
       'system-v48',
       'system-v48'
FROM state_action_menu
CROSS JOIN permission_center
WHERE NOT EXISTS (
    SELECT 1
    FROM iam_menu existing
    WHERE existing.code = state_action_menu.code
      AND existing.deleted_at IS NULL
);

WITH permission_center AS (
    SELECT id
    FROM iam_menu
    WHERE code = 'system-permission-center'
      AND deleted_at IS NULL
),
state_action_menu(code, title, i18n_key, path, icon, permission_code, sort_no) AS (
    VALUES
        ('iam-state-action-management', '状态动作权限', 'route.iamStateActionPermissions', '/system/iam/state-action-permissions', 'ShieldCheck', 'iam-state-action:view', 38)
)
UPDATE iam_menu menu
SET parent_id = permission_center.id,
    title = state_action_menu.title,
    i18n_key = state_action_menu.i18n_key,
    path = state_action_menu.path,
    icon = state_action_menu.icon,
    permission_code = state_action_menu.permission_code,
    sort_no = state_action_menu.sort_no,
    is_enabled = true,
    updated_by = 'system-v48',
    updated_at = now()
FROM state_action_menu
CROSS JOIN permission_center
WHERE menu.code = state_action_menu.code
  AND menu.deleted_at IS NULL;

WITH source_grant(old_code, new_code) AS (
    VALUES
        ('iam-role:update', 'iam-state-action:view'),
        ('iam-role:update', 'iam-state-action:update'),
        ('iam-permission:create', 'iam-state-action:create')
),
role_grant AS (
    SELECT DISTINCT role_permission.tenant_id,
           role_permission.role_id,
           new_permission.id AS permission_id,
           COALESCE(role_permission.created_by, 'system-v48') AS created_by
    FROM iam_role_permission role_permission
    JOIN iam_permission old_permission
      ON old_permission.id = role_permission.permission_id
    JOIN source_grant
      ON source_grant.old_code = old_permission.code
    JOIN iam_permission new_permission
      ON new_permission.code = source_grant.new_code
    WHERE role_permission.deleted_at IS NULL
)
INSERT INTO iam_role_permission (
    tenant_id, role_id, permission_id, created_by, updated_by
)
SELECT tenant_id, role_id, permission_id, created_by, 'system-v48'
FROM role_grant
ON CONFLICT (tenant_id, role_id, permission_id) WHERE deleted_at IS NULL DO UPDATE
SET deleted_by = NULL,
    delete_reason = NULL,
    deleted_at = NULL,
    updated_by = 'system-v48',
    updated_at = now();

WITH source_entitlement(old_code, new_code) AS (
    VALUES
        ('iam-role:update', 'iam-state-action:view'),
        ('iam-role:update', 'iam-state-action:update'),
        ('iam-permission:create', 'iam-state-action:create')
),
tenant_entitlement AS (
    SELECT DISTINCT entitlement.tenant_id,
           entitlement.init_template_code,
           new_permission.id AS permission_id,
           entitlement.entitlement_version,
           COALESCE(entitlement.created_by, 'system-v48') AS created_by
    FROM iam_tenant_permission_entitlement entitlement
    JOIN iam_permission old_permission
      ON old_permission.id = entitlement.permission_id
    JOIN source_entitlement
      ON source_entitlement.old_code = old_permission.code
    JOIN iam_permission new_permission
      ON new_permission.code = source_entitlement.new_code
    WHERE entitlement.deleted_at IS NULL
)
INSERT INTO iam_tenant_permission_entitlement (
    tenant_id, init_template_code, permission_id, entitlement_version, created_by, updated_by
)
SELECT tenant_id, init_template_code, permission_id, entitlement_version, created_by, 'system-v48'
FROM tenant_entitlement
ON CONFLICT (tenant_id, permission_id) WHERE deleted_at IS NULL DO UPDATE
SET init_template_code = EXCLUDED.init_template_code,
    entitlement_version = EXCLUDED.entitlement_version,
    is_enabled = true,
    deleted_by = NULL,
    delete_reason = NULL,
    deleted_at = NULL,
    updated_by = 'system-v48',
    updated_at = now();

UPDATE iam_tenant_init_permission_template template
SET permission_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(template.permission_codes) AS code
                UNION ALL
                SELECT source_permission.new_code
                FROM jsonb_array_elements_text(template.permission_codes) existing(code)
                JOIN (
                    VALUES
                        ('iam-role:update', 'iam-state-action:view'),
                        ('iam-role:update', 'iam-state-action:update'),
                        ('iam-permission:create', 'iam-state-action:create')
                ) AS source_permission(old_code, new_code)
                  ON source_permission.old_code = existing.code
            ) expanded
        ) distinct_code
    ),
    updated_by = 'system-v48',
    updated_at = now()
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(template.permission_codes) existing(code)
    WHERE existing.code IN ('iam-role:update', 'iam-permission:create')
);

UPDATE iam_tenant_init_role_template role_template
SET permission_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(role_template.permission_codes) AS code
                UNION ALL
                SELECT source_permission.new_code
                FROM jsonb_array_elements_text(role_template.permission_codes) existing(code)
                JOIN (
                    VALUES
                        ('iam-role:update', 'iam-state-action:view'),
                        ('iam-role:update', 'iam-state-action:update'),
                        ('iam-permission:create', 'iam-state-action:create')
                ) AS source_permission(old_code, new_code)
                  ON source_permission.old_code = existing.code
            ) expanded
        ) distinct_code
    ),
    updated_by = 'system-v48',
    updated_at = now()
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(role_template.permission_codes) existing(code)
    WHERE existing.code IN ('iam-role:update', 'iam-permission:create')
);

INSERT INTO iam_tenant_menu (tenant_id, menu_id, is_enabled, created_by, updated_by)
SELECT DISTINCT tenant_menu.tenant_id,
       menu.id,
       true,
       'system-v48',
       'system-v48'
FROM iam_tenant_menu tenant_menu
CROSS JOIN iam_menu menu
WHERE tenant_menu.deleted_at IS NULL
  AND menu.code = 'iam-state-action-management'
  AND menu.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM iam_tenant_menu existing
      WHERE existing.tenant_id = tenant_menu.tenant_id
        AND existing.menu_id = menu.id
        AND existing.deleted_at IS NULL
  );

UPDATE iam_authorization_snapshot snapshot
SET permission_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) AS code
                UNION ALL
                SELECT source_permission.new_code
                FROM jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) existing(code)
                JOIN (
                    VALUES
                        ('iam-role:update', 'iam-state-action:view'),
                        ('iam-role:update', 'iam-state-action:update'),
                        ('iam-permission:create', 'iam-state-action:create')
                ) AS source_permission(old_code, new_code)
                  ON source_permission.old_code = existing.code
            ) expanded
        ) distinct_code
    ),
    menu_codes = (
        SELECT COALESCE(jsonb_agg(code ORDER BY code), '[]'::jsonb)
        FROM (
            SELECT DISTINCT code
            FROM (
                SELECT jsonb_array_elements_text(COALESCE(snapshot.menu_codes, '[]'::jsonb)) AS code
                UNION ALL
                SELECT 'iam-state-action-management'
                WHERE EXISTS (
                    SELECT 1
                    FROM jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) existing(code)
                    WHERE existing.code = 'iam-role:update'
                )
            ) expanded
        ) distinct_code
    ),
    auth_version = snapshot.auth_version + 1,
    snapshot_hash = 'state-action-v48:' || snapshot.tenant_id || ':' || snapshot.user_id,
    updated_by = 'system-v48',
    updated_at = now()
WHERE EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(COALESCE(snapshot.permission_codes, '[]'::jsonb)) existing(code)
    WHERE existing.code IN ('iam-role:update', 'iam-permission:create')
);
