-- xuan-party initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS customer_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    description varchar(500),
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_customer_category PRIMARY KEY (id)
);
COMMENT ON TABLE customer_category IS '客户类别表。';
COMMENT ON COLUMN customer_category.id IS '主键';
COMMENT ON COLUMN customer_category.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN customer_category.code IS '类别编码';
COMMENT ON COLUMN customer_category.name IS '类别名称';
COMMENT ON COLUMN customer_category.description IS '描述';
COMMENT ON COLUMN customer_category.sort_no IS '排序';
COMMENT ON COLUMN customer_category.is_enabled IS '是否启用';
COMMENT ON COLUMN customer_category.is_default IS '是否默认';
COMMENT ON COLUMN customer_category.remark IS '备注';
COMMENT ON COLUMN customer_category.created_by IS '创建人';
COMMENT ON COLUMN customer_category.created_at IS '创建时间';
COMMENT ON COLUMN customer_category.updated_by IS '更新人';
COMMENT ON COLUMN customer_category.updated_at IS '更新时间';
COMMENT ON COLUMN customer_category.deleted_by IS '删除人';
COMMENT ON COLUMN customer_category.delete_reason IS '删除原因';
COMMENT ON COLUMN customer_category.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_party_customer_category_code_active
    ON customer_category (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_party_customer_category_default
    ON customer_category (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_party_customer_category_tenant_deleted
    ON customer_category (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS counterparty_subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    name varchar(200) NOT NULL,
    region varchar(128),
    unified_credit_code varchar(64),
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_counterparty_subject PRIMARY KEY (id)
);
COMMENT ON TABLE counterparty_subject IS '往来主体表，用于统一客户、供应商和财务往来。';
COMMENT ON COLUMN counterparty_subject.id IS '主键';
COMMENT ON COLUMN counterparty_subject.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN counterparty_subject.name IS '主体名称';
COMMENT ON COLUMN counterparty_subject.region IS '区域';
COMMENT ON COLUMN counterparty_subject.unified_credit_code IS '统一社会信用代码';
COMMENT ON COLUMN counterparty_subject.is_enabled IS '是否启用';
COMMENT ON COLUMN counterparty_subject.remark IS '备注';
COMMENT ON COLUMN counterparty_subject.created_by IS '创建人';
COMMENT ON COLUMN counterparty_subject.created_at IS '创建时间';
COMMENT ON COLUMN counterparty_subject.updated_by IS '更新人';
COMMENT ON COLUMN counterparty_subject.updated_at IS '更新时间';
COMMENT ON COLUMN counterparty_subject.deleted_by IS '删除人';
COMMENT ON COLUMN counterparty_subject.delete_reason IS '删除原因';
COMMENT ON COLUMN counterparty_subject.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_party_subject_name
    ON counterparty_subject (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_party_subject_tenant_deleted
    ON counterparty_subject (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS counterparty_subject_link (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    target_type varchar(32) NOT NULL,
    target_id bigint NOT NULL,
    role_type varchar(32) NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_counterparty_subject_link PRIMARY KEY (id)
);
COMMENT ON TABLE counterparty_subject_link IS '往来主体关联表。';
COMMENT ON COLUMN counterparty_subject_link.id IS '主键';
COMMENT ON COLUMN counterparty_subject_link.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN counterparty_subject_link.subject_id IS '往来主体 ID';
COMMENT ON COLUMN counterparty_subject_link.target_type IS '关联对象类型';
COMMENT ON COLUMN counterparty_subject_link.target_id IS '关联对象 ID';
COMMENT ON COLUMN counterparty_subject_link.role_type IS '业务角色';
COMMENT ON COLUMN counterparty_subject_link.is_primary IS '是否主档案';
COMMENT ON COLUMN counterparty_subject_link.remark IS '备注';
COMMENT ON COLUMN counterparty_subject_link.created_by IS '创建人';
COMMENT ON COLUMN counterparty_subject_link.created_at IS '创建时间';
COMMENT ON COLUMN counterparty_subject_link.updated_by IS '更新人';
COMMENT ON COLUMN counterparty_subject_link.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_party_subject_link_target
    ON counterparty_subject_link (tenant_id, target_type, target_id, role_type);
CREATE INDEX IF NOT EXISTS idx_party_subject_link_subject
    ON counterparty_subject_link (tenant_id, subject_id);

CREATE TABLE IF NOT EXISTS customer (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    short_name varchar(100),
    category_id bigint,
    counterparty_subject_id bigint,
    contact varchar(100),
    phone varchar(50),
    mobile varchar(50),
    email varchar(200),
    address varchar(500),
    tax_no varchar(100),
    bank_name varchar(200),
    bank_account varchar(200),
    invoice_title varchar(200),
    credit_limit numeric(18,2) DEFAULT 0 NOT NULL,
    contacts jsonb,
    delivery_method_code varchar(100),
    default_settlement_method_code varchar(100),
    default_receipt_method_code varchar(100),
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);
COMMENT ON TABLE customer IS '客户表。';
COMMENT ON COLUMN customer.id IS '主键';
COMMENT ON COLUMN customer.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN customer.code IS '客户编码';
COMMENT ON COLUMN customer.name IS '客户名称';
COMMENT ON COLUMN customer.short_name IS '客户简称';
COMMENT ON COLUMN customer.category_id IS '客户类别 ID';
COMMENT ON COLUMN customer.counterparty_subject_id IS '往来主体 ID';
COMMENT ON COLUMN customer.contact IS '联系人';
COMMENT ON COLUMN customer.phone IS '联系电话';
COMMENT ON COLUMN customer.mobile IS '手机';
COMMENT ON COLUMN customer.email IS '邮箱';
COMMENT ON COLUMN customer.address IS '地址';
COMMENT ON COLUMN customer.tax_no IS '税号';
COMMENT ON COLUMN customer.bank_name IS '开户行';
COMMENT ON COLUMN customer.bank_account IS '银行账号';
COMMENT ON COLUMN customer.invoice_title IS '发票抬头';
COMMENT ON COLUMN customer.credit_limit IS '授信额度';
COMMENT ON COLUMN customer.contacts IS '联系人 JSON';
COMMENT ON COLUMN customer.delivery_method_code IS '默认送货方式编码';
COMMENT ON COLUMN customer.default_settlement_method_code IS '默认结算方式编码';
COMMENT ON COLUMN customer.default_receipt_method_code IS '默认收款方式编码';
COMMENT ON COLUMN customer.is_enabled IS '是否启用';
COMMENT ON COLUMN customer.remark IS '备注';
COMMENT ON COLUMN customer.created_by IS '创建人';
COMMENT ON COLUMN customer.created_at IS '创建时间';
COMMENT ON COLUMN customer.updated_by IS '更新人';
COMMENT ON COLUMN customer.updated_at IS '更新时间';
COMMENT ON COLUMN customer.deleted_by IS '删除人';
COMMENT ON COLUMN customer.delete_reason IS '删除原因';
COMMENT ON COLUMN customer.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_party_customer_code_active
    ON customer (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_party_customer_name
    ON customer (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_party_customer_category
    ON customer (tenant_id, category_id);
CREATE INDEX IF NOT EXISTS idx_party_customer_tenant_deleted
    ON customer (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS delivery_method (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_delivery_method PRIMARY KEY (id)
);
COMMENT ON TABLE delivery_method IS '送货方式表。';
COMMENT ON COLUMN delivery_method.id IS '主键';
COMMENT ON COLUMN delivery_method.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN delivery_method.code IS '送货方式编码';
COMMENT ON COLUMN delivery_method.name IS '送货方式名称';
COMMENT ON COLUMN delivery_method.sort_no IS '排序';
COMMENT ON COLUMN delivery_method.is_enabled IS '是否启用';
COMMENT ON COLUMN delivery_method.is_default IS '是否默认';
COMMENT ON COLUMN delivery_method.remark IS '备注';
COMMENT ON COLUMN delivery_method.created_by IS '创建人';
COMMENT ON COLUMN delivery_method.created_at IS '创建时间';
COMMENT ON COLUMN delivery_method.updated_by IS '更新人';
COMMENT ON COLUMN delivery_method.updated_at IS '更新时间';
COMMENT ON COLUMN delivery_method.deleted_by IS '删除人';
COMMENT ON COLUMN delivery_method.delete_reason IS '删除原因';
COMMENT ON COLUMN delivery_method.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_delivery_met_code_active
    ON delivery_method (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_delivery_method_default
    ON delivery_method (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_delivery_met_delivery_method_tenant_deleted
    ON delivery_method (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS supplier_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_supplier_type PRIMARY KEY (id)
);
COMMENT ON TABLE supplier_type IS '供应商类型表。';
COMMENT ON COLUMN supplier_type.id IS '主键';
COMMENT ON COLUMN supplier_type.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN supplier_type.code IS '类型编码';
COMMENT ON COLUMN supplier_type.name IS '类型名称';
COMMENT ON COLUMN supplier_type.is_enabled IS '是否启用';
COMMENT ON COLUMN supplier_type.sort_no IS '排序';
COMMENT ON COLUMN supplier_type.remark IS '备注';
COMMENT ON COLUMN supplier_type.created_by IS '创建人';
COMMENT ON COLUMN supplier_type.created_at IS '创建时间';
COMMENT ON COLUMN supplier_type.updated_by IS '更新人';
COMMENT ON COLUMN supplier_type.updated_at IS '更新时间';
COMMENT ON COLUMN supplier_type.deleted_by IS '删除人';
COMMENT ON COLUMN supplier_type.delete_reason IS '删除原因';
COMMENT ON COLUMN supplier_type.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_party_supplier_type_code_active
    ON supplier_type (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_party_supplier_type_tenant_deleted
    ON supplier_type (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    short_name varchar(100),
    supplier_type_id bigint,
    counterparty_subject_id bigint,
    contact varchar(100),
    phone varchar(50),
    mobile varchar(50),
    email varchar(200),
    address varchar(500),
    tax_no varchar(100),
    bank_name varchar(200),
    bank_account varchar(200),
    contacts jsonb,
    is_enabled boolean DEFAULT true NOT NULL,
    is_blacklisted boolean DEFAULT false NOT NULL,
    default_settlement_method_code varchar(100),
    default_payment_method_code varchar(100),
    region varchar(128),
    wechat varchar(128),
    purchaser varchar(128),
    business_scope varchar(32) DEFAULT 'SUPPLIER' NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_supplier PRIMARY KEY (id)
);
COMMENT ON TABLE supplier IS '供应商表。';
COMMENT ON COLUMN supplier.id IS '主键';
COMMENT ON COLUMN supplier.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN supplier.code IS '供应商编码';
COMMENT ON COLUMN supplier.name IS '供应商名称';
COMMENT ON COLUMN supplier.short_name IS '简称';
COMMENT ON COLUMN supplier.supplier_type_id IS '供应商类型 ID';
COMMENT ON COLUMN supplier.counterparty_subject_id IS '往来主体 ID';
COMMENT ON COLUMN supplier.contact IS '联系人';
COMMENT ON COLUMN supplier.phone IS '联系电话';
COMMENT ON COLUMN supplier.mobile IS '手机';
COMMENT ON COLUMN supplier.email IS '邮箱';
COMMENT ON COLUMN supplier.address IS '地址';
COMMENT ON COLUMN supplier.tax_no IS '税号';
COMMENT ON COLUMN supplier.bank_name IS '开户行';
COMMENT ON COLUMN supplier.bank_account IS '银行账号';
COMMENT ON COLUMN supplier.contacts IS '联系人 JSON';
COMMENT ON COLUMN supplier.is_enabled IS '是否启用';
COMMENT ON COLUMN supplier.is_blacklisted IS '是否黑名单';
COMMENT ON COLUMN supplier.default_settlement_method_code IS '默认结算方式编码';
COMMENT ON COLUMN supplier.default_payment_method_code IS '默认付款方式编码';
COMMENT ON COLUMN supplier.region IS '区域';
COMMENT ON COLUMN supplier.wechat IS '微信客服';
COMMENT ON COLUMN supplier.purchaser IS '采购员';
COMMENT ON COLUMN supplier.business_scope IS '往来类别';
COMMENT ON COLUMN supplier.remark IS '备注';
COMMENT ON COLUMN supplier.created_by IS '创建人';
COMMENT ON COLUMN supplier.created_at IS '创建时间';
COMMENT ON COLUMN supplier.updated_by IS '更新人';
COMMENT ON COLUMN supplier.updated_at IS '更新时间';
COMMENT ON COLUMN supplier.deleted_by IS '删除人';
COMMENT ON COLUMN supplier.delete_reason IS '删除原因';
COMMENT ON COLUMN supplier.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_party_supplier_code_active
    ON supplier (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_party_supplier_name
    ON supplier (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_party_supplier_type
    ON supplier (tenant_id, supplier_type_id);
CREATE INDEX IF NOT EXISTS idx_party_supplier_status
    ON supplier (tenant_id, is_enabled, is_blacklisted, deleted_at);

CREATE TABLE IF NOT EXISTS customer_import_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_no varchar(64) NOT NULL,
    source_name varchar(255),
    import_mode varchar(32) DEFAULT 'EXCEL_UPLOAD' NOT NULL,
    total_count integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    warning_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    summary text,
    raw_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_customer_import_batch PRIMARY KEY (id)
);
COMMENT ON TABLE customer_import_batch IS '客户导入批次。';
COMMENT ON COLUMN customer_import_batch.id IS '主键';
COMMENT ON COLUMN customer_import_batch.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN customer_import_batch.batch_no IS '导入批次号';
COMMENT ON COLUMN customer_import_batch.source_name IS '来源文件名';
COMMENT ON COLUMN customer_import_batch.import_mode IS '导入模式';
COMMENT ON COLUMN customer_import_batch.total_count IS '总数';
COMMENT ON COLUMN customer_import_batch.success_count IS '成功数';
COMMENT ON COLUMN customer_import_batch.failed_count IS '失败数';
COMMENT ON COLUMN customer_import_batch.warning_count IS '警告数';
COMMENT ON COLUMN customer_import_batch.status IS '状态';
COMMENT ON COLUMN customer_import_batch.summary IS '导入摘要';
COMMENT ON COLUMN customer_import_batch.raw_payload IS '原始载荷';
COMMENT ON COLUMN customer_import_batch.created_by IS '创建人';
COMMENT ON COLUMN customer_import_batch.created_at IS '创建时间';
COMMENT ON COLUMN customer_import_batch.updated_by IS '更新人';
COMMENT ON COLUMN customer_import_batch.updated_at IS '更新时间';
COMMENT ON COLUMN customer_import_batch.deleted_by IS '删除人';
COMMENT ON COLUMN customer_import_batch.delete_reason IS '删除原因';
COMMENT ON COLUMN customer_import_batch.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_customer_imp_batch_no_active
    ON customer_import_batch (tenant_id, batch_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customer_import_batch_status
    ON customer_import_batch (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS customer_import_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    row_no integer NOT NULL,
    source_code varchar(128),
    source_name varchar(255),
    matched_target_id bigint,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    error_field varchar(128),
    error_message text,
    warning_message text,
    raw_row jsonb NOT NULL,
    normalized_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_customer_import_item PRIMARY KEY (id)
);
COMMENT ON TABLE customer_import_item IS '客户导入明细。';
COMMENT ON COLUMN customer_import_item.id IS '主键';
COMMENT ON COLUMN customer_import_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN customer_import_item.batch_id IS '导入批次 ID';
COMMENT ON COLUMN customer_import_item.row_no IS '行号';
COMMENT ON COLUMN customer_import_item.source_code IS '来源编码';
COMMENT ON COLUMN customer_import_item.source_name IS '来源名称';
COMMENT ON COLUMN customer_import_item.matched_target_id IS '匹配目标 ID';
COMMENT ON COLUMN customer_import_item.status IS '状态';
COMMENT ON COLUMN customer_import_item.error_field IS '错误字段';
COMMENT ON COLUMN customer_import_item.error_message IS '错误信息';
COMMENT ON COLUMN customer_import_item.warning_message IS '警告信息';
COMMENT ON COLUMN customer_import_item.raw_row IS '原始行';
COMMENT ON COLUMN customer_import_item.normalized_payload IS '规范化数据';
COMMENT ON COLUMN customer_import_item.created_by IS '创建人';
COMMENT ON COLUMN customer_import_item.created_at IS '创建时间';
COMMENT ON COLUMN customer_import_item.updated_by IS '更新人';
COMMENT ON COLUMN customer_import_item.updated_at IS '更新时间';
COMMENT ON COLUMN customer_import_item.deleted_by IS '删除人';
COMMENT ON COLUMN customer_import_item.delete_reason IS '删除原因';
COMMENT ON COLUMN customer_import_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_customer_imp_batch_row_active
    ON customer_import_item (tenant_id, batch_id, row_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customer_import_item_status
    ON customer_import_item (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS supplier_import_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_no varchar(64) NOT NULL,
    source_name varchar(255),
    import_mode varchar(32) DEFAULT 'EXCEL_UPLOAD' NOT NULL,
    total_count integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    warning_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    summary text,
    raw_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_supplier_import_batch PRIMARY KEY (id)
);
COMMENT ON TABLE supplier_import_batch IS '供应商导入批次。';
COMMENT ON COLUMN supplier_import_batch.id IS '主键';
COMMENT ON COLUMN supplier_import_batch.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN supplier_import_batch.batch_no IS '导入批次号';
COMMENT ON COLUMN supplier_import_batch.source_name IS '来源文件名';
COMMENT ON COLUMN supplier_import_batch.import_mode IS '导入模式';
COMMENT ON COLUMN supplier_import_batch.total_count IS '总数';
COMMENT ON COLUMN supplier_import_batch.success_count IS '成功数';
COMMENT ON COLUMN supplier_import_batch.failed_count IS '失败数';
COMMENT ON COLUMN supplier_import_batch.warning_count IS '警告数';
COMMENT ON COLUMN supplier_import_batch.status IS '状态';
COMMENT ON COLUMN supplier_import_batch.summary IS '导入摘要';
COMMENT ON COLUMN supplier_import_batch.raw_payload IS '原始载荷';
COMMENT ON COLUMN supplier_import_batch.created_by IS '创建人';
COMMENT ON COLUMN supplier_import_batch.created_at IS '创建时间';
COMMENT ON COLUMN supplier_import_batch.updated_by IS '更新人';
COMMENT ON COLUMN supplier_import_batch.updated_at IS '更新时间';
COMMENT ON COLUMN supplier_import_batch.deleted_by IS '删除人';
COMMENT ON COLUMN supplier_import_batch.delete_reason IS '删除原因';
COMMENT ON COLUMN supplier_import_batch.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_supplier_imp_batch_no_active
    ON supplier_import_batch (tenant_id, batch_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_supplier_import_batch_status
    ON supplier_import_batch (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS supplier_import_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    row_no integer NOT NULL,
    source_code varchar(128),
    source_name varchar(255),
    matched_target_id bigint,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    error_field varchar(128),
    error_message text,
    warning_message text,
    raw_row jsonb NOT NULL,
    normalized_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_supplier_import_item PRIMARY KEY (id)
);
COMMENT ON TABLE supplier_import_item IS '供应商导入明细。';
COMMENT ON COLUMN supplier_import_item.id IS '主键';
COMMENT ON COLUMN supplier_import_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN supplier_import_item.batch_id IS '导入批次 ID';
COMMENT ON COLUMN supplier_import_item.row_no IS '行号';
COMMENT ON COLUMN supplier_import_item.source_code IS '来源编码';
COMMENT ON COLUMN supplier_import_item.source_name IS '来源名称';
COMMENT ON COLUMN supplier_import_item.matched_target_id IS '匹配目标 ID';
COMMENT ON COLUMN supplier_import_item.status IS '状态';
COMMENT ON COLUMN supplier_import_item.error_field IS '错误字段';
COMMENT ON COLUMN supplier_import_item.error_message IS '错误信息';
COMMENT ON COLUMN supplier_import_item.warning_message IS '警告信息';
COMMENT ON COLUMN supplier_import_item.raw_row IS '原始行';
COMMENT ON COLUMN supplier_import_item.normalized_payload IS '规范化数据';
COMMENT ON COLUMN supplier_import_item.created_by IS '创建人';
COMMENT ON COLUMN supplier_import_item.created_at IS '创建时间';
COMMENT ON COLUMN supplier_import_item.updated_by IS '更新人';
COMMENT ON COLUMN supplier_import_item.updated_at IS '更新时间';
COMMENT ON COLUMN supplier_import_item.deleted_by IS '删除人';
COMMENT ON COLUMN supplier_import_item.delete_reason IS '删除原因';
COMMENT ON COLUMN supplier_import_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_supplier_imp_batch_row_active
    ON supplier_import_item (tenant_id, batch_id, row_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_supplier_import_item_status
    ON supplier_import_item (tenant_id, status)
    WHERE deleted_at IS NULL;

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- customer_category: 默认客户类别。
INSERT INTO customer_category (tenant_id, code, name, description, sort_no, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, 'GENERAL', '普通客户', '默认客户类别。', 0, true, true, 'V1 默认客户类别。', 'system', 'system'
WHERE NOT EXISTS (
    SELECT 1
    FROM customer_category existing
    WHERE existing.tenant_id = 1
      AND existing.code = 'GENERAL'
      AND existing.deleted_at IS NULL
);

-- supplier_type: 默认供应商类型。
INSERT INTO supplier_type (tenant_id, code, name, is_enabled, sort_no, remark, created_by, updated_by)
SELECT 1, 'GENERAL', '普通供应商', true, 0, 'V1 默认供应商类型。', 'system', 'system'
WHERE NOT EXISTS (
    SELECT 1
    FROM supplier_type existing
    WHERE existing.tenant_id = 1
      AND existing.code = 'GENERAL'
      AND existing.deleted_at IS NULL
);

-- delivery_method: 常用送货方式，归属 xuan-party 维护。
INSERT INTO delivery_method (tenant_id, code, name, sort_no, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, seed.code, seed.name, seed.sort_no, seed.is_enabled, seed.is_default, seed.remark, 'system', 'system'
FROM (
    VALUES
        ('PICKUP', '自提', 10, true, true, '客户自提。'),
        ('DOOR_DELIVERY', '送货上门', 20, true, false, '本地配送。'),
        ('LOGISTICS', '物流/快递', 30, true, false, '第三方物流或快递。')
) AS seed(code, name, sort_no, is_enabled, is_default, remark)
WHERE NOT EXISTS (
    SELECT 1
    FROM delivery_method existing
    WHERE existing.tenant_id = 1
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);
