-- xuan-audit initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    actor_username varchar(100),
    actor_user_id bigint,
    action varchar(100) NOT NULL,
    entity_type varchar(100) NOT NULL,
    entity_id varchar(64),
    detail text,
    status varchar(20) DEFAULT 'SUCCESS' NOT NULL,
    request_id varchar(64),
    client_ip varchar(64),
    user_agent varchar(400),
    duration_ms bigint,
    method varchar(16),
    path varchar(500),
    http_status integer,
    error_code varchar(64),
    error_message varchar(500),
    auth_tenant_id bigint,
    auth_tenant_code varchar(100),
    is_cross_tenant boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);
COMMENT ON TABLE audit_log IS '审计日志表，记录用户动作、请求信息和跨租户访问痕迹。';
COMMENT ON COLUMN audit_log.id IS '主键';
COMMENT ON COLUMN audit_log.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN audit_log.actor_username IS '操作者用户名';
COMMENT ON COLUMN audit_log.actor_user_id IS '操作者用户 ID';
COMMENT ON COLUMN audit_log.action IS '动作标识';
COMMENT ON COLUMN audit_log.entity_type IS '实体类型';
COMMENT ON COLUMN audit_log.entity_id IS '实体 ID';
COMMENT ON COLUMN audit_log.detail IS '详情';
COMMENT ON COLUMN audit_log.status IS '结果状态';
COMMENT ON COLUMN audit_log.request_id IS '请求 ID';
COMMENT ON COLUMN audit_log.client_ip IS '客户端 IP';
COMMENT ON COLUMN audit_log.user_agent IS '客户端 UA';
COMMENT ON COLUMN audit_log.duration_ms IS '耗时毫秒';
COMMENT ON COLUMN audit_log.method IS '请求方法';
COMMENT ON COLUMN audit_log.path IS '请求路径';
COMMENT ON COLUMN audit_log.http_status IS 'HTTP 状态';
COMMENT ON COLUMN audit_log.error_code IS '错误码';
COMMENT ON COLUMN audit_log.error_message IS '错误信息';
COMMENT ON COLUMN audit_log.auth_tenant_id IS '认证租户 ID';
COMMENT ON COLUMN audit_log.auth_tenant_code IS '认证租户编码';
COMMENT ON COLUMN audit_log.is_cross_tenant IS '是否跨租户';
COMMENT ON COLUMN audit_log.created_at IS '创建时间';
CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_actor
    ON audit_log (tenant_id, actor_username, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_request
    ON audit_log (request_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_path
    ON audit_log (path);

CREATE TABLE IF NOT EXISTS sql_request_trace (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    request_id varchar(64) NOT NULL,
    request_path varchar(500) NOT NULL,
    request_method varchar(16) NOT NULL,
    response_status integer,
    request_cost_ms bigint DEFAULT 0 NOT NULL,
    sql_total_cost_ms bigint DEFAULT 0 NOT NULL,
    sql_count integer DEFAULT 0 NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NOT NULL,
    username varchar(100),
    user_id bigint,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_sql_request_trace PRIMARY KEY (id)
);
COMMENT ON TABLE sql_request_trace IS '一次请求级 SQL 汇总。';
COMMENT ON COLUMN sql_request_trace.id IS '主键';
COMMENT ON COLUMN sql_request_trace.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN sql_request_trace.request_id IS '请求 ID';
COMMENT ON COLUMN sql_request_trace.request_path IS '请求路径';
COMMENT ON COLUMN sql_request_trace.request_method IS '请求方法';
COMMENT ON COLUMN sql_request_trace.response_status IS '响应状态';
COMMENT ON COLUMN sql_request_trace.request_cost_ms IS '请求耗时';
COMMENT ON COLUMN sql_request_trace.sql_total_cost_ms IS 'SQL 总耗时';
COMMENT ON COLUMN sql_request_trace.sql_count IS 'SQL 数量';
COMMENT ON COLUMN sql_request_trace.started_at IS '开始时间';
COMMENT ON COLUMN sql_request_trace.finished_at IS '结束时间';
COMMENT ON COLUMN sql_request_trace.username IS '用户名';
COMMENT ON COLUMN sql_request_trace.user_id IS '用户 ID';
COMMENT ON COLUMN sql_request_trace.created_at IS '创建时间';
CREATE INDEX IF NOT EXISTS idx_audit_sql_request
    ON sql_request_trace (tenant_id, request_id);
CREATE INDEX IF NOT EXISTS idx_audit_sql_request_cost
    ON sql_request_trace (tenant_id, sql_total_cost_ms DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS sql_trace_entry (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    request_trace_id bigint NOT NULL,
    request_id varchar(64) NOT NULL,
    sequence_no integer NOT NULL,
    mapper_id varchar(300) NOT NULL,
    sql_type varchar(20) NOT NULL,
    cost_ms bigint DEFAULT 0 NOT NULL,
    sql_text text NOT NULL,
    params_summary text DEFAULT '[disabled]' NOT NULL,
    executed_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_sql_trace_entry PRIMARY KEY (id)
);
COMMENT ON TABLE sql_trace_entry IS '单条 SQL trace 明细。';
COMMENT ON COLUMN sql_trace_entry.id IS '主键';
COMMENT ON COLUMN sql_trace_entry.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN sql_trace_entry.request_trace_id IS '请求 trace ID';
COMMENT ON COLUMN sql_trace_entry.request_id IS '请求 ID';
COMMENT ON COLUMN sql_trace_entry.sequence_no IS 'SQL 顺序号';
COMMENT ON COLUMN sql_trace_entry.mapper_id IS 'Mapper ID';
COMMENT ON COLUMN sql_trace_entry.sql_type IS 'SQL 类型';
COMMENT ON COLUMN sql_trace_entry.cost_ms IS '耗时毫秒';
COMMENT ON COLUMN sql_trace_entry.sql_text IS 'SQL 文本';
COMMENT ON COLUMN sql_trace_entry.params_summary IS '参数摘要';
COMMENT ON COLUMN sql_trace_entry.executed_at IS '执行时间';
COMMENT ON COLUMN sql_trace_entry.created_at IS '创建时间';
CREATE INDEX IF NOT EXISTS idx_audit_sql_entry_sequence
    ON sql_trace_entry (request_trace_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_audit_sql_entry_cost
    ON sql_trace_entry (tenant_id, cost_ms DESC, executed_at DESC);

CREATE TABLE IF NOT EXISTS idempotency_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    method varchar(16) NOT NULL,
    path varchar(300) NOT NULL,
    username varchar(100),
    expires_at timestamptz NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_idempotency_record PRIMARY KEY (id)
);
COMMENT ON TABLE idempotency_record IS '接口幂等记录，第一版集中承接旧库 app_idempotency 能力。';
COMMENT ON COLUMN idempotency_record.id IS '主键';
COMMENT ON COLUMN idempotency_record.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN idempotency_record.idempotency_key IS '幂等键';
COMMENT ON COLUMN idempotency_record.method IS '请求方法';
COMMENT ON COLUMN idempotency_record.path IS '请求路径';
COMMENT ON COLUMN idempotency_record.username IS '用户名';
COMMENT ON COLUMN idempotency_record.expires_at IS '过期时间';
COMMENT ON COLUMN idempotency_record.created_by IS '创建人';
COMMENT ON COLUMN idempotency_record.created_at IS '创建时间';
COMMENT ON COLUMN idempotency_record.updated_by IS '更新人';
COMMENT ON COLUMN idempotency_record.updated_at IS '更新时间';
COMMENT ON COLUMN idempotency_record.deleted_by IS '删除人';
COMMENT ON COLUMN idempotency_record.delete_reason IS '删除原因';
COMMENT ON COLUMN idempotency_record.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_audit_idempotency_key_active
    ON idempotency_record (tenant_id, idempotency_key)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_audit_idempotency_expire
    ON idempotency_record (expires_at, deleted_at);

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);
