-- xuan-finance initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS settlement_method (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    fund_input_mode varchar(20) DEFAULT 'OPTIONAL' NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_settlement_method PRIMARY KEY (id)
);
COMMENT ON TABLE settlement_method IS '结算方式表。';
COMMENT ON COLUMN settlement_method.id IS '主键';
COMMENT ON COLUMN settlement_method.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN settlement_method.code IS '结算方式编码';
COMMENT ON COLUMN settlement_method.name IS '结算方式名称';
COMMENT ON COLUMN settlement_method.sort_no IS '排序';
COMMENT ON COLUMN settlement_method.is_enabled IS '是否启用';
COMMENT ON COLUMN settlement_method.is_default IS '是否默认';
COMMENT ON COLUMN settlement_method.fund_input_mode IS '即时收付款录入模式';
COMMENT ON COLUMN settlement_method.remark IS '备注';
COMMENT ON COLUMN settlement_method.created_by IS '创建人';
COMMENT ON COLUMN settlement_method.created_at IS '创建时间';
COMMENT ON COLUMN settlement_method.updated_by IS '更新人';
COMMENT ON COLUMN settlement_method.updated_at IS '更新时间';
COMMENT ON COLUMN settlement_method.deleted_by IS '删除人';
COMMENT ON COLUMN settlement_method.delete_reason IS '删除原因';
COMMENT ON COLUMN settlement_method.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_settlement_m_code_active
    ON settlement_method (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_settlement_method_default
    ON settlement_method (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_settlement_m_settlement_method_tenant_deleted
    ON settlement_method (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS receipt_method (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_receipt_method PRIMARY KEY (id)
);
COMMENT ON TABLE receipt_method IS '收款方式表。';
COMMENT ON COLUMN receipt_method.id IS '主键';
COMMENT ON COLUMN receipt_method.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN receipt_method.code IS '收款方式编码';
COMMENT ON COLUMN receipt_method.name IS '收款方式名称';
COMMENT ON COLUMN receipt_method.sort_no IS '排序';
COMMENT ON COLUMN receipt_method.is_enabled IS '是否启用';
COMMENT ON COLUMN receipt_method.is_default IS '是否默认';
COMMENT ON COLUMN receipt_method.remark IS '备注';
COMMENT ON COLUMN receipt_method.created_by IS '创建人';
COMMENT ON COLUMN receipt_method.created_at IS '创建时间';
COMMENT ON COLUMN receipt_method.updated_by IS '更新人';
COMMENT ON COLUMN receipt_method.updated_at IS '更新时间';
COMMENT ON COLUMN receipt_method.deleted_by IS '删除人';
COMMENT ON COLUMN receipt_method.delete_reason IS '删除原因';
COMMENT ON COLUMN receipt_method.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_receipt_meth_code_active
    ON receipt_method (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_receipt_method_default
    ON receipt_method (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_receipt_meth_receipt_method_tenant_deleted
    ON receipt_method (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS payment_method (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_payment_method PRIMARY KEY (id)
);
COMMENT ON TABLE payment_method IS '付款方式表。';
COMMENT ON COLUMN payment_method.id IS '主键';
COMMENT ON COLUMN payment_method.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN payment_method.code IS '付款方式编码';
COMMENT ON COLUMN payment_method.name IS '付款方式名称';
COMMENT ON COLUMN payment_method.sort_no IS '排序';
COMMENT ON COLUMN payment_method.is_enabled IS '是否启用';
COMMENT ON COLUMN payment_method.is_default IS '是否默认';
COMMENT ON COLUMN payment_method.remark IS '备注';
COMMENT ON COLUMN payment_method.created_by IS '创建人';
COMMENT ON COLUMN payment_method.created_at IS '创建时间';
COMMENT ON COLUMN payment_method.updated_by IS '更新人';
COMMENT ON COLUMN payment_method.updated_at IS '更新时间';
COMMENT ON COLUMN payment_method.deleted_by IS '删除人';
COMMENT ON COLUMN payment_method.delete_reason IS '删除原因';
COMMENT ON COLUMN payment_method.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_payment_meth_code_active
    ON payment_method (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payment_method_default
    ON payment_method (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payment_meth_payment_method_tenant_deleted
    ON payment_method (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS accounts_receivable (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    sale_order_id bigint,
    order_no varchar(64) NOT NULL,
    customer_id bigint NOT NULL,
    party_name_snapshot varchar(200),
    total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    paid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    unpaid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    status varchar(20) DEFAULT 'OPEN' NOT NULL,
    settlement_method_code varchar(100),
    source_document_type varchar(50),
    source_document_id bigint,
    source_business_flow varchar(50),
    auto_flow_generated boolean DEFAULT false NOT NULL,
    auto_flow_mode varchar(50),
    auto_flow_managed_state varchar(50),
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_accounts_receivable PRIMARY KEY (id)
);
COMMENT ON TABLE accounts_receivable IS 'ERP 应收单。';
COMMENT ON COLUMN accounts_receivable.id IS '主键';
COMMENT ON COLUMN accounts_receivable.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN accounts_receivable.sale_order_id IS '来源单据 ID';
COMMENT ON COLUMN accounts_receivable.order_no IS '来源单据号';
COMMENT ON COLUMN accounts_receivable.customer_id IS '客户 ID';
COMMENT ON COLUMN accounts_receivable.party_name_snapshot IS '往来方名称快照';
COMMENT ON COLUMN accounts_receivable.total_amount IS '总金额';
COMMENT ON COLUMN accounts_receivable.paid_amount IS '已结算金额';
COMMENT ON COLUMN accounts_receivable.unpaid_amount IS '未结算金额';
COMMENT ON COLUMN accounts_receivable.discount_amount IS '优惠金额';
COMMENT ON COLUMN accounts_receivable.status IS '状态';
COMMENT ON COLUMN accounts_receivable.settlement_method_code IS '结算方式编码';
COMMENT ON COLUMN accounts_receivable.source_document_type IS '自动联动来源单据类型';
COMMENT ON COLUMN accounts_receivable.source_document_id IS '自动联动来源单据 ID';
COMMENT ON COLUMN accounts_receivable.source_business_flow IS '自动联动业务流';
COMMENT ON COLUMN accounts_receivable.auto_flow_generated IS '是否自动生成';
COMMENT ON COLUMN accounts_receivable.auto_flow_mode IS '自动生成模式';
COMMENT ON COLUMN accounts_receivable.auto_flow_managed_state IS '自动托管状态';
COMMENT ON COLUMN accounts_receivable.print_count IS '打印次数';
COMMENT ON COLUMN accounts_receivable.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN accounts_receivable.remark IS '备注';
COMMENT ON COLUMN accounts_receivable.created_by IS '创建人';
COMMENT ON COLUMN accounts_receivable.created_at IS '创建时间';
COMMENT ON COLUMN accounts_receivable.updated_by IS '更新人';
COMMENT ON COLUMN accounts_receivable.updated_at IS '更新时间';
COMMENT ON COLUMN accounts_receivable.deleted_by IS '删除人';
COMMENT ON COLUMN accounts_receivable.delete_reason IS '删除原因';
COMMENT ON COLUMN accounts_receivable.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_finance_ar_order_no_active
    ON accounts_receivable (tenant_id, order_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_ar_party
    ON accounts_receivable (tenant_id, customer_id, status, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_ar_auto_flow
    ON accounts_receivable (tenant_id, source_document_type, source_document_id, source_business_flow)
    WHERE auto_flow_generated = true AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS accounts_payable (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    purchase_order_id bigint,
    order_no varchar(64) NOT NULL,
    supplier_id bigint NOT NULL,
    party_name_snapshot varchar(200),
    total_amount numeric(18,2) DEFAULT 0 NOT NULL,
    paid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    unpaid_amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    status varchar(20) DEFAULT 'OPEN' NOT NULL,
    settlement_method_code varchar(100),
    source_document_type varchar(50),
    source_document_id bigint,
    source_business_flow varchar(50),
    auto_flow_generated boolean DEFAULT false NOT NULL,
    auto_flow_mode varchar(50),
    auto_flow_managed_state varchar(50),
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_accounts_payable PRIMARY KEY (id)
);
COMMENT ON TABLE accounts_payable IS 'ERP 应付单。';
COMMENT ON COLUMN accounts_payable.id IS '主键';
COMMENT ON COLUMN accounts_payable.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN accounts_payable.purchase_order_id IS '来源单据 ID';
COMMENT ON COLUMN accounts_payable.order_no IS '来源单据号';
COMMENT ON COLUMN accounts_payable.supplier_id IS '供应商 ID';
COMMENT ON COLUMN accounts_payable.party_name_snapshot IS '往来方名称快照';
COMMENT ON COLUMN accounts_payable.total_amount IS '总金额';
COMMENT ON COLUMN accounts_payable.paid_amount IS '已结算金额';
COMMENT ON COLUMN accounts_payable.unpaid_amount IS '未结算金额';
COMMENT ON COLUMN accounts_payable.discount_amount IS '优惠金额';
COMMENT ON COLUMN accounts_payable.status IS '状态';
COMMENT ON COLUMN accounts_payable.settlement_method_code IS '结算方式编码';
COMMENT ON COLUMN accounts_payable.source_document_type IS '自动联动来源单据类型';
COMMENT ON COLUMN accounts_payable.source_document_id IS '自动联动来源单据 ID';
COMMENT ON COLUMN accounts_payable.source_business_flow IS '自动联动业务流';
COMMENT ON COLUMN accounts_payable.auto_flow_generated IS '是否自动生成';
COMMENT ON COLUMN accounts_payable.auto_flow_mode IS '自动生成模式';
COMMENT ON COLUMN accounts_payable.auto_flow_managed_state IS '自动托管状态';
COMMENT ON COLUMN accounts_payable.print_count IS '打印次数';
COMMENT ON COLUMN accounts_payable.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN accounts_payable.remark IS '备注';
COMMENT ON COLUMN accounts_payable.created_by IS '创建人';
COMMENT ON COLUMN accounts_payable.created_at IS '创建时间';
COMMENT ON COLUMN accounts_payable.updated_by IS '更新人';
COMMENT ON COLUMN accounts_payable.updated_at IS '更新时间';
COMMENT ON COLUMN accounts_payable.deleted_by IS '删除人';
COMMENT ON COLUMN accounts_payable.delete_reason IS '删除原因';
COMMENT ON COLUMN accounts_payable.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_finance_ap_order_no_active
    ON accounts_payable (tenant_id, order_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_ap_party
    ON accounts_payable (tenant_id, supplier_id, status, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_ap_auto_flow
    ON accounts_payable (tenant_id, source_document_type, source_document_id, source_business_flow)
    WHERE auto_flow_generated = true AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS receipt (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    receipt_no varchar(64) NOT NULL,
    customer_id bigint NOT NULL,
    party_name_snapshot varchar(200),
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    settlement_method_code varchar(100),
    receipt_method_code varchar(100),
    status varchar(20) DEFAULT 'APPROVED' NOT NULL,
    occurred_at timestamptz,
    source_document_type varchar(50),
    source_document_id bigint,
    source_business_flow varchar(50),
    auto_flow_generated boolean DEFAULT false NOT NULL,
    auto_flow_mode varchar(50),
    auto_flow_managed_state varchar(50),
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_receipt PRIMARY KEY (id)
);
COMMENT ON TABLE receipt IS '收款单。';
COMMENT ON COLUMN receipt.id IS '主键';
COMMENT ON COLUMN receipt.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN receipt.receipt_no IS '单号';
COMMENT ON COLUMN receipt.customer_id IS '客户 ID';
COMMENT ON COLUMN receipt.party_name_snapshot IS '往来方名称快照';
COMMENT ON COLUMN receipt.amount IS '收付款金额';
COMMENT ON COLUMN receipt.discount_amount IS '优惠金额';
COMMENT ON COLUMN receipt.settlement_method_code IS '结算方式编码';
COMMENT ON COLUMN receipt.receipt_method_code IS '收付款方式编码';
COMMENT ON COLUMN receipt.status IS '状态';
COMMENT ON COLUMN receipt.occurred_at IS '收付款时间';
COMMENT ON COLUMN receipt.source_document_type IS '自动联动来源单据类型';
COMMENT ON COLUMN receipt.source_document_id IS '自动联动来源单据 ID';
COMMENT ON COLUMN receipt.source_business_flow IS '自动联动业务流';
COMMENT ON COLUMN receipt.auto_flow_generated IS '是否自动生成';
COMMENT ON COLUMN receipt.auto_flow_mode IS '自动生成模式';
COMMENT ON COLUMN receipt.auto_flow_managed_state IS '自动托管状态';
COMMENT ON COLUMN receipt.print_count IS '打印次数';
COMMENT ON COLUMN receipt.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN receipt.remark IS '备注';
COMMENT ON COLUMN receipt.created_by IS '创建人';
COMMENT ON COLUMN receipt.created_at IS '创建时间';
COMMENT ON COLUMN receipt.updated_by IS '更新人';
COMMENT ON COLUMN receipt.updated_at IS '更新时间';
COMMENT ON COLUMN receipt.deleted_by IS '删除人';
COMMENT ON COLUMN receipt.delete_reason IS '删除原因';
COMMENT ON COLUMN receipt.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_finance_receipt_no_active
    ON receipt (tenant_id, receipt_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_receipt_party
    ON receipt (tenant_id, customer_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS receipt_receivable (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    receipt_id bigint NOT NULL,
    receivable_id bigint NOT NULL,
    allocated_amount numeric(18,2) DEFAULT 0 NOT NULL,
    allocated_discount numeric(18,2) DEFAULT 0 NOT NULL,
    allocated_total numeric(18,2) DEFAULT 0 NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_receipt_receivable PRIMARY KEY (id)
);
COMMENT ON TABLE receipt_receivable IS '收款单-应收分摊。';
COMMENT ON COLUMN receipt_receivable.id IS '主键';
COMMENT ON COLUMN receipt_receivable.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN receipt_receivable.receipt_id IS '收付款单 ID';
COMMENT ON COLUMN receipt_receivable.receivable_id IS '账款单 ID';
COMMENT ON COLUMN receipt_receivable.allocated_amount IS '分摊金额';
COMMENT ON COLUMN receipt_receivable.allocated_discount IS '分摊优惠';
COMMENT ON COLUMN receipt_receivable.allocated_total IS '分摊合计';
COMMENT ON COLUMN receipt_receivable.created_by IS '创建人';
COMMENT ON COLUMN receipt_receivable.created_at IS '创建时间';
COMMENT ON COLUMN receipt_receivable.updated_by IS '更新人';
COMMENT ON COLUMN receipt_receivable.updated_at IS '更新时间';
COMMENT ON COLUMN receipt_receivable.deleted_by IS '删除人';
COMMENT ON COLUMN receipt_receivable.delete_reason IS '删除原因';
COMMENT ON COLUMN receipt_receivable.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_finance_receipt_receivable_active
    ON receipt_receivable (tenant_id, receipt_id, receivable_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_receipt_receivable_target
    ON receipt_receivable (tenant_id, receivable_id);

CREATE TABLE IF NOT EXISTS payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    payment_no varchar(64) NOT NULL,
    supplier_id bigint NOT NULL,
    party_name_snapshot varchar(200),
    amount numeric(18,2) DEFAULT 0 NOT NULL,
    discount_amount numeric(18,2) DEFAULT 0 NOT NULL,
    settlement_method_code varchar(100),
    payment_method_code varchar(100),
    status varchar(20) DEFAULT 'APPROVED' NOT NULL,
    occurred_at timestamptz,
    source_document_type varchar(50),
    source_document_id bigint,
    source_business_flow varchar(50),
    auto_flow_generated boolean DEFAULT false NOT NULL,
    auto_flow_mode varchar(50),
    auto_flow_managed_state varchar(50),
    print_count integer DEFAULT 0 NOT NULL,
    last_printed_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);
COMMENT ON TABLE payment IS '付款单。';
COMMENT ON COLUMN payment.id IS '主键';
COMMENT ON COLUMN payment.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN payment.payment_no IS '单号';
COMMENT ON COLUMN payment.supplier_id IS '供应商 ID';
COMMENT ON COLUMN payment.party_name_snapshot IS '往来方名称快照';
COMMENT ON COLUMN payment.amount IS '收付款金额';
COMMENT ON COLUMN payment.discount_amount IS '优惠金额';
COMMENT ON COLUMN payment.settlement_method_code IS '结算方式编码';
COMMENT ON COLUMN payment.payment_method_code IS '收付款方式编码';
COMMENT ON COLUMN payment.status IS '状态';
COMMENT ON COLUMN payment.occurred_at IS '收付款时间';
COMMENT ON COLUMN payment.source_document_type IS '自动联动来源单据类型';
COMMENT ON COLUMN payment.source_document_id IS '自动联动来源单据 ID';
COMMENT ON COLUMN payment.source_business_flow IS '自动联动业务流';
COMMENT ON COLUMN payment.auto_flow_generated IS '是否自动生成';
COMMENT ON COLUMN payment.auto_flow_mode IS '自动生成模式';
COMMENT ON COLUMN payment.auto_flow_managed_state IS '自动托管状态';
COMMENT ON COLUMN payment.print_count IS '打印次数';
COMMENT ON COLUMN payment.last_printed_at IS '最后打印时间';
COMMENT ON COLUMN payment.remark IS '备注';
COMMENT ON COLUMN payment.created_by IS '创建人';
COMMENT ON COLUMN payment.created_at IS '创建时间';
COMMENT ON COLUMN payment.updated_by IS '更新人';
COMMENT ON COLUMN payment.updated_at IS '更新时间';
COMMENT ON COLUMN payment.deleted_by IS '删除人';
COMMENT ON COLUMN payment.delete_reason IS '删除原因';
COMMENT ON COLUMN payment.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_finance_payment_no_active
    ON payment (tenant_id, payment_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_payment_party
    ON payment (tenant_id, supplier_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS payment_payable (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    payment_id bigint NOT NULL,
    payable_id bigint NOT NULL,
    allocated_amount numeric(18,2) DEFAULT 0 NOT NULL,
    allocated_discount numeric(18,2) DEFAULT 0 NOT NULL,
    allocated_total numeric(18,2) DEFAULT 0 NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_payment_payable PRIMARY KEY (id)
);
COMMENT ON TABLE payment_payable IS '付款单-应付分摊。';
COMMENT ON COLUMN payment_payable.id IS '主键';
COMMENT ON COLUMN payment_payable.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN payment_payable.payment_id IS '收付款单 ID';
COMMENT ON COLUMN payment_payable.payable_id IS '账款单 ID';
COMMENT ON COLUMN payment_payable.allocated_amount IS '分摊金额';
COMMENT ON COLUMN payment_payable.allocated_discount IS '分摊优惠';
COMMENT ON COLUMN payment_payable.allocated_total IS '分摊合计';
COMMENT ON COLUMN payment_payable.created_by IS '创建人';
COMMENT ON COLUMN payment_payable.created_at IS '创建时间';
COMMENT ON COLUMN payment_payable.updated_by IS '更新人';
COMMENT ON COLUMN payment_payable.updated_at IS '更新时间';
COMMENT ON COLUMN payment_payable.deleted_by IS '删除人';
COMMENT ON COLUMN payment_payable.delete_reason IS '删除原因';
COMMENT ON COLUMN payment_payable.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_finance_payment_payable_active
    ON payment_payable (tenant_id, payment_id, payable_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_finance_payment_payable_target
    ON payment_payable (tenant_id, payable_id);

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- settlement_method: 常用结算方式；`fund_input_mode` 不加枚举约束，由业务解释。
INSERT INTO settlement_method (tenant_id, code, name, sort_no, is_enabled, is_default, fund_input_mode, remark, created_by, updated_by)
SELECT 1, seed.code, seed.name, seed.sort_no, seed.is_enabled, seed.is_default, seed.fund_input_mode, seed.remark, 'system', 'system'
FROM (
    VALUES
        ('CASH', '现结', 10, true, true, 'OPTIONAL', '即时结算。'),
        ('MONTHLY', '月结', 20, true, false, 'OPTIONAL', '按月结算。'),
        ('CREDIT', '赊账', 30, true, false, 'OPTIONAL', '先挂账后结算。')
) AS seed(code, name, sort_no, is_enabled, is_default, fund_input_mode, remark)
WHERE NOT EXISTS (
    SELECT 1
    FROM settlement_method existing
    WHERE existing.tenant_id = 1
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);

-- receipt_method: 常用收款方式。
INSERT INTO receipt_method (tenant_id, code, name, sort_no, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, seed.code, seed.name, seed.sort_no, seed.is_enabled, seed.is_default, seed.remark, 'system', 'system'
FROM (
    VALUES
        ('CASH', '现金', 10, true, true, '现金收款。'),
        ('WECHAT', '微信', 20, true, false, '微信收款。'),
        ('ALIPAY', '支付宝', 30, true, false, '支付宝收款。'),
        ('BANK_TRANSFER', '银行转账', 40, true, false, '银行转账收款。')
) AS seed(code, name, sort_no, is_enabled, is_default, remark)
WHERE NOT EXISTS (
    SELECT 1
    FROM receipt_method existing
    WHERE existing.tenant_id = 1
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);

-- payment_method: 常用付款方式。
INSERT INTO payment_method (tenant_id, code, name, sort_no, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, seed.code, seed.name, seed.sort_no, seed.is_enabled, seed.is_default, seed.remark, 'system', 'system'
FROM (
    VALUES
        ('CASH', '现金', 10, true, true, '现金付款。'),
        ('WECHAT', '微信', 20, true, false, '微信付款。'),
        ('ALIPAY', '支付宝', 30, true, false, '支付宝付款。'),
        ('BANK_TRANSFER', '银行转账', 40, true, false, '银行转账付款。')
) AS seed(code, name, sort_no, is_enabled, is_default, remark)
WHERE NOT EXISTS (
    SELECT 1
    FROM payment_method existing
    WHERE existing.tenant_id = 1
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);
