-- xuan-tenant initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS tenant (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(100) NOT NULL,
    normalized_code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    status varchar(20) DEFAULT 'PROVISIONING' NOT NULL,
    contact_name varchar(100),
    contact_phone varchar(50),
    provisioned_at timestamptz,
    enabled_at timestamptz,
    disabled_at timestamptz,
    disabled_reason varchar(500),
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);
COMMENT ON TABLE tenant IS '租户主档，管理租户编码、名称和启停状态。';
COMMENT ON COLUMN tenant.id IS '主键';
COMMENT ON COLUMN tenant.code IS '租户编码';
COMMENT ON COLUMN tenant.normalized_code IS '规范化租户编码，应用层统一小写并校验活动态唯一';
COMMENT ON COLUMN tenant.name IS '租户名称';
COMMENT ON COLUMN tenant.status IS '租户状态：PROVISIONING/ENABLED/SUSPENDED/DISABLED';
COMMENT ON COLUMN tenant.contact_name IS '联系人';
COMMENT ON COLUMN tenant.contact_phone IS '联系电话';
COMMENT ON COLUMN tenant.provisioned_at IS '开通完成时间';
COMMENT ON COLUMN tenant.enabled_at IS '启用时间';
COMMENT ON COLUMN tenant.disabled_at IS '停用时间';
COMMENT ON COLUMN tenant.disabled_reason IS '停用原因';
COMMENT ON COLUMN tenant.remark IS '备注';
COMMENT ON COLUMN tenant.created_by IS '创建人';
COMMENT ON COLUMN tenant.created_at IS '创建时间';
COMMENT ON COLUMN tenant.updated_by IS '更新人';
COMMENT ON COLUMN tenant.updated_at IS '更新时间';
COMMENT ON COLUMN tenant.deleted_by IS '删除人';
COMMENT ON COLUMN tenant.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_code_active
    ON tenant (normalized_code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_status
    ON tenant (status, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    status varchar(20) DEFAULT 'ENABLED' NOT NULL,
    billing_cycle varchar(20) DEFAULT 'MONTHLY' NOT NULL,
    price_amount numeric(18,2) DEFAULT 0 NOT NULL,
    currency varchar(10) DEFAULT 'CNY' NOT NULL,
    max_user_count integer,
    max_warehouse_count integer,
    max_storage_gb numeric(18,2),
    feature_flags jsonb DEFAULT '{}'::jsonb NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_plan PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_plan IS '租户套餐定义表，管理套餐编码、价格周期、额度和功能开关。';
COMMENT ON COLUMN tenant_plan.id IS '主键';
COMMENT ON COLUMN tenant_plan.code IS '套餐编码';
COMMENT ON COLUMN tenant_plan.name IS '套餐名称';
COMMENT ON COLUMN tenant_plan.status IS '套餐状态';
COMMENT ON COLUMN tenant_plan.billing_cycle IS '计费周期';
COMMENT ON COLUMN tenant_plan.price_amount IS '套餐价格';
COMMENT ON COLUMN tenant_plan.currency IS '币种';
COMMENT ON COLUMN tenant_plan.max_user_count IS '最大用户数，空表示不限';
COMMENT ON COLUMN tenant_plan.max_warehouse_count IS '最大仓库数，空表示不限';
COMMENT ON COLUMN tenant_plan.max_storage_gb IS '最大存储 GB，空表示不限';
COMMENT ON COLUMN tenant_plan.feature_flags IS '功能开关 JSON';
COMMENT ON COLUMN tenant_plan.sort_no IS '排序';
COMMENT ON COLUMN tenant_plan.remark IS '备注';
COMMENT ON COLUMN tenant_plan.created_by IS '创建人';
COMMENT ON COLUMN tenant_plan.created_at IS '创建时间';
COMMENT ON COLUMN tenant_plan.updated_by IS '更新人';
COMMENT ON COLUMN tenant_plan.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_plan.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_plan.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_plan.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_plan_code_active
    ON tenant_plan (code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_plan_status
    ON tenant_plan (status, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_plan_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    previous_plan_id bigint,
    plan_id bigint NOT NULL,
    status varchar(20) DEFAULT 'ACTIVE' NOT NULL,
    effective_at timestamptz DEFAULT now() NOT NULL,
    expires_at timestamptz,
    assigned_at timestamptz DEFAULT now() NOT NULL,
    assigned_by varchar(100),
    change_reason varchar(500),
    source varchar(80),
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_plan_assignment PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_plan_assignment IS '租户套餐分配表，记录租户当前套餐、生效时间和变更来源。';
COMMENT ON COLUMN tenant_plan_assignment.id IS '主键';
COMMENT ON COLUMN tenant_plan_assignment.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_plan_assignment.previous_plan_id IS '变更前套餐 ID，应用层校验来源于 tenant_plan';
COMMENT ON COLUMN tenant_plan_assignment.plan_id IS '套餐 ID，应用层校验来源于 tenant_plan';
COMMENT ON COLUMN tenant_plan_assignment.status IS '分配状态';
COMMENT ON COLUMN tenant_plan_assignment.effective_at IS '生效时间';
COMMENT ON COLUMN tenant_plan_assignment.expires_at IS '到期时间';
COMMENT ON COLUMN tenant_plan_assignment.assigned_at IS '分配时间';
COMMENT ON COLUMN tenant_plan_assignment.assigned_by IS '分配操作人';
COMMENT ON COLUMN tenant_plan_assignment.change_reason IS '变更原因';
COMMENT ON COLUMN tenant_plan_assignment.source IS '变更来源';
COMMENT ON COLUMN tenant_plan_assignment.remark IS '备注';
COMMENT ON COLUMN tenant_plan_assignment.created_by IS '创建人';
COMMENT ON COLUMN tenant_plan_assignment.created_at IS '创建时间';
COMMENT ON COLUMN tenant_plan_assignment.updated_by IS '更新人';
COMMENT ON COLUMN tenant_plan_assignment.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_plan_assignment.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_plan_assignment.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_plan_assignment.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_plan_assignment_current
    ON tenant_plan_assignment (tenant_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_plan_assignment_plan
    ON tenant_plan_assignment (plan_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_tenant_plan_assignment_tenant_deleted
    ON tenant_plan_assignment (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_domain (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    domain varchar(255) NOT NULL,
    normalized_domain varchar(255) NOT NULL,
    status varchar(30) DEFAULT 'PENDING' NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    verification_token varchar(160),
    verified_at timestamptz,
    last_checked_at timestamptz,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_domain PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_domain IS '租户域名表，支持租户自定义域名、独立入口和域名验证状态。';
COMMENT ON COLUMN tenant_domain.id IS '主键';
COMMENT ON COLUMN tenant_domain.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_domain.domain IS '域名';
COMMENT ON COLUMN tenant_domain.normalized_domain IS '规范化域名，应用层统一小写并校验活动态唯一';
COMMENT ON COLUMN tenant_domain.status IS '域名状态';
COMMENT ON COLUMN tenant_domain.is_primary IS '是否主域名';
COMMENT ON COLUMN tenant_domain.verification_token IS '域名验证令牌';
COMMENT ON COLUMN tenant_domain.verified_at IS '验证通过时间';
COMMENT ON COLUMN tenant_domain.last_checked_at IS '最近检查时间';
COMMENT ON COLUMN tenant_domain.remark IS '备注';
COMMENT ON COLUMN tenant_domain.created_by IS '创建人';
COMMENT ON COLUMN tenant_domain.created_at IS '创建时间';
COMMENT ON COLUMN tenant_domain.updated_by IS '更新人';
COMMENT ON COLUMN tenant_domain.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_domain.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_domain.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_domain.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_domain_normalized_active
    ON tenant_domain (normalized_domain)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_domain_tenant
    ON tenant_domain (tenant_id, status, deleted_at);
CREATE INDEX IF NOT EXISTS idx_tenant_domain_primary
    ON tenant_domain (tenant_id, is_primary, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_contact (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    contact_type varchar(40) DEFAULT 'ADMIN' NOT NULL,
    name varchar(100) NOT NULL,
    phone varchar(50),
    email varchar(200),
    is_primary boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_contact PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_contact IS '租户联系人表，支持管理员、商务、技术、财务等多类型联系人。';
COMMENT ON COLUMN tenant_contact.id IS '主键';
COMMENT ON COLUMN tenant_contact.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_contact.contact_type IS '联系人类型';
COMMENT ON COLUMN tenant_contact.name IS '联系人姓名';
COMMENT ON COLUMN tenant_contact.phone IS '联系电话';
COMMENT ON COLUMN tenant_contact.email IS '联系邮箱';
COMMENT ON COLUMN tenant_contact.is_primary IS '是否主联系人';
COMMENT ON COLUMN tenant_contact.remark IS '备注';
COMMENT ON COLUMN tenant_contact.created_by IS '创建人';
COMMENT ON COLUMN tenant_contact.created_at IS '创建时间';
COMMENT ON COLUMN tenant_contact.updated_by IS '更新人';
COMMENT ON COLUMN tenant_contact.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_contact.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_contact.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_contact.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_contact_tenant
    ON tenant_contact (tenant_id, contact_type, is_primary, deleted_at);
CREATE INDEX IF NOT EXISTS idx_tenant_contact_phone
    ON tenant_contact (phone);
CREATE INDEX IF NOT EXISTS idx_tenant_contact_tenant_deleted
    ON tenant_contact (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    from_status varchar(20),
    to_status varchar(20) NOT NULL,
    change_type varchar(60) NOT NULL,
    change_reason varchar(500),
    changed_at timestamptz DEFAULT now() NOT NULL,
    changed_by varchar(100),
    trace_id varchar(100),
    request_id varchar(100),
    source varchar(80),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_tenant_status_history PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_status_history IS '租户生命周期历史表，记录租户状态变化、原因、操作者和链路信息。';
COMMENT ON COLUMN tenant_status_history.id IS '主键';
COMMENT ON COLUMN tenant_status_history.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_status_history.from_status IS '变更前状态';
COMMENT ON COLUMN tenant_status_history.to_status IS '变更后状态';
COMMENT ON COLUMN tenant_status_history.change_type IS '变更类型';
COMMENT ON COLUMN tenant_status_history.change_reason IS '变更原因';
COMMENT ON COLUMN tenant_status_history.changed_at IS '变更时间';
COMMENT ON COLUMN tenant_status_history.changed_by IS '变更操作人';
COMMENT ON COLUMN tenant_status_history.trace_id IS '链路追踪 ID';
COMMENT ON COLUMN tenant_status_history.request_id IS '请求 ID';
COMMENT ON COLUMN tenant_status_history.source IS '变更来源';
COMMENT ON COLUMN tenant_status_history.created_by IS '创建人';
COMMENT ON COLUMN tenant_status_history.created_at IS '创建时间';
CREATE INDEX IF NOT EXISTS idx_tenant_status_history_tenant
    ON tenant_status_history (tenant_id, changed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_tenant_status_history_trace
    ON tenant_status_history (trace_id);

CREATE TABLE IF NOT EXISTS tenant_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    config_key varchar(120) NOT NULL,
    config_value text,
    value_type varchar(40) DEFAULT 'string' NOT NULL,
    description varchar(500),
    is_public boolean DEFAULT false NOT NULL,
    is_sensitive boolean DEFAULT false NOT NULL,
    is_encrypted boolean DEFAULT false NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_config PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_config IS '租户级系统配置，承接旧库 app_system_config 的租户隔离配置能力。';
COMMENT ON COLUMN tenant_config.id IS '主键';
COMMENT ON COLUMN tenant_config.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_config.config_key IS '配置键';
COMMENT ON COLUMN tenant_config.config_value IS '配置值';
COMMENT ON COLUMN tenant_config.value_type IS '值类型：string/number/boolean/json';
COMMENT ON COLUMN tenant_config.description IS '配置说明';
COMMENT ON COLUMN tenant_config.is_public IS '是否可被前端公开读取';
COMMENT ON COLUMN tenant_config.is_sensitive IS '是否敏感配置，敏感值返回前端时必须脱敏';
COMMENT ON COLUMN tenant_config.is_encrypted IS '是否已加密存储';
COMMENT ON COLUMN tenant_config.created_by IS '创建人';
COMMENT ON COLUMN tenant_config.created_at IS '创建时间';
COMMENT ON COLUMN tenant_config.updated_by IS '更新人';
COMMENT ON COLUMN tenant_config.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_config.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_config.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_config.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_config_key_active
    ON tenant_config (tenant_id, config_key)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_config_tenant_deleted
    ON tenant_config (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_provision_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    task_key varchar(120) NOT NULL,
    task_type varchar(80) NOT NULL,
    status varchar(30) DEFAULT 'PENDING' NOT NULL,
    idempotency_key varchar(160) NOT NULL,
    step_name varchar(120),
    request_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    result_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retry_count integer DEFAULT 5 NOT NULL,
    last_error_code varchar(120),
    last_error_message text,
    started_at timestamptz,
    finished_at timestamptz,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_provision_task PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_provision_task IS '租户初始化任务表，记录租户开通时跨服务初始化步骤、幂等键、重试和失败原因。';
COMMENT ON COLUMN tenant_provision_task.id IS '主键';
COMMENT ON COLUMN tenant_provision_task.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_provision_task.task_key IS '任务键';
COMMENT ON COLUMN tenant_provision_task.task_type IS '任务类型';
COMMENT ON COLUMN tenant_provision_task.status IS '任务状态';
COMMENT ON COLUMN tenant_provision_task.idempotency_key IS '幂等键';
COMMENT ON COLUMN tenant_provision_task.step_name IS '当前步骤';
COMMENT ON COLUMN tenant_provision_task.request_payload IS '请求载荷';
COMMENT ON COLUMN tenant_provision_task.result_payload IS '结果载荷';
COMMENT ON COLUMN tenant_provision_task.retry_count IS '已重试次数';
COMMENT ON COLUMN tenant_provision_task.max_retry_count IS '最大重试次数';
COMMENT ON COLUMN tenant_provision_task.last_error_code IS '最近错误码';
COMMENT ON COLUMN tenant_provision_task.last_error_message IS '最近错误信息';
COMMENT ON COLUMN tenant_provision_task.started_at IS '开始时间';
COMMENT ON COLUMN tenant_provision_task.finished_at IS '完成时间';
COMMENT ON COLUMN tenant_provision_task.created_by IS '创建人';
COMMENT ON COLUMN tenant_provision_task.created_at IS '创建时间';
COMMENT ON COLUMN tenant_provision_task.updated_by IS '更新人';
COMMENT ON COLUMN tenant_provision_task.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_provision_task.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_provision_task.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_provision_task.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_provision_task_key_active
    ON tenant_provision_task (tenant_id, task_key)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_provision_status
    ON tenant_provision_task (status, updated_at);
CREATE INDEX IF NOT EXISTS idx_tenant_provision_idempotency
    ON tenant_provision_task (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_tenant_provision_task_tenant_deleted
    ON tenant_provision_task (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_provision_task_step (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    provision_task_id bigint NOT NULL,
    step_key varchar(120) NOT NULL,
    step_name varchar(120) NOT NULL,
    status varchar(30) DEFAULT 'PENDING' NOT NULL,
    sequence_no integer DEFAULT 0 NOT NULL,
    idempotency_key varchar(180) NOT NULL,
    request_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    result_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retry_count integer DEFAULT 5 NOT NULL,
    last_error_code varchar(120),
    last_error_message text,
    started_at timestamptz,
    finished_at timestamptz,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_tenant_provision_task_step PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_provision_task_step IS '租户初始化任务步骤表，记录初始化任务下每个服务或业务步骤的状态、重试和结果。';
COMMENT ON COLUMN tenant_provision_task_step.id IS '主键';
COMMENT ON COLUMN tenant_provision_task_step.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_provision_task_step.provision_task_id IS '初始化任务 ID，应用层校验来源于 tenant_provision_task';
COMMENT ON COLUMN tenant_provision_task_step.step_key IS '步骤键';
COMMENT ON COLUMN tenant_provision_task_step.step_name IS '步骤名称';
COMMENT ON COLUMN tenant_provision_task_step.status IS '步骤状态';
COMMENT ON COLUMN tenant_provision_task_step.sequence_no IS '步骤顺序';
COMMENT ON COLUMN tenant_provision_task_step.idempotency_key IS '步骤幂等键';
COMMENT ON COLUMN tenant_provision_task_step.request_payload IS '请求载荷';
COMMENT ON COLUMN tenant_provision_task_step.result_payload IS '结果载荷';
COMMENT ON COLUMN tenant_provision_task_step.retry_count IS '已重试次数';
COMMENT ON COLUMN tenant_provision_task_step.max_retry_count IS '最大重试次数';
COMMENT ON COLUMN tenant_provision_task_step.last_error_code IS '最近错误码';
COMMENT ON COLUMN tenant_provision_task_step.last_error_message IS '最近错误信息';
COMMENT ON COLUMN tenant_provision_task_step.started_at IS '开始时间';
COMMENT ON COLUMN tenant_provision_task_step.finished_at IS '完成时间';
COMMENT ON COLUMN tenant_provision_task_step.created_by IS '创建人';
COMMENT ON COLUMN tenant_provision_task_step.created_at IS '创建时间';
COMMENT ON COLUMN tenant_provision_task_step.updated_by IS '更新人';
COMMENT ON COLUMN tenant_provision_task_step.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_provision_task_step.deleted_by IS '删除人';
COMMENT ON COLUMN tenant_provision_task_step.delete_reason IS '删除原因';
COMMENT ON COLUMN tenant_provision_task_step.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_tenant_provision_step_key_active
    ON tenant_provision_task_step (provision_task_id, step_key)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_provision_step_task
    ON tenant_provision_task_step (provision_task_id, sequence_no, id);
CREATE INDEX IF NOT EXISTS idx_tenant_provision_step_status
    ON tenant_provision_task_step (tenant_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_tenant_provision_step_tenant_deleted
    ON tenant_provision_task_step (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS tenant_outbox_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    event_id varchar(128) NOT NULL,
    aggregate_type varchar(80) DEFAULT 'TENANT' NOT NULL,
    aggregate_id bigint NOT NULL,
    event_type varchar(120) NOT NULL,
    topic varchar(120) DEFAULT 'xuan-tenant-event' NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    headers jsonb DEFAULT '{}'::jsonb NOT NULL,
    status varchar(30) DEFAULT 'PENDING' NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retry_count integer DEFAULT 10 NOT NULL,
    locked_by varchar(100),
    locked_at timestamptz,
    lock_expires_at timestamptz,
    next_retry_at timestamptz,
    published_at timestamptz,
    last_error_code varchar(120),
    last_error_message text,
    first_failed_at timestamptz,
    dead_letter_at timestamptz,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_tenant_outbox_event PRIMARY KEY (id)
);
COMMENT ON TABLE tenant_outbox_event IS '租户服务 Outbox 事件表，在本地事务内记录待发布领域事件，避免业务写入成功但事件丢失。';
COMMENT ON COLUMN tenant_outbox_event.id IS '主键';
COMMENT ON COLUMN tenant_outbox_event.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN tenant_outbox_event.event_id IS '事件 ID';
COMMENT ON COLUMN tenant_outbox_event.aggregate_type IS '聚合类型';
COMMENT ON COLUMN tenant_outbox_event.aggregate_id IS '聚合 ID';
COMMENT ON COLUMN tenant_outbox_event.event_type IS '事件类型';
COMMENT ON COLUMN tenant_outbox_event.topic IS '事件主题';
COMMENT ON COLUMN tenant_outbox_event.payload IS '事件载荷';
COMMENT ON COLUMN tenant_outbox_event.headers IS '事件头';
COMMENT ON COLUMN tenant_outbox_event.status IS '发布状态';
COMMENT ON COLUMN tenant_outbox_event.retry_count IS '已重试次数';
COMMENT ON COLUMN tenant_outbox_event.max_retry_count IS '最大重试次数';
COMMENT ON COLUMN tenant_outbox_event.locked_by IS '当前发布锁持有者';
COMMENT ON COLUMN tenant_outbox_event.locked_at IS '锁定时间';
COMMENT ON COLUMN tenant_outbox_event.lock_expires_at IS '锁过期时间';
COMMENT ON COLUMN tenant_outbox_event.next_retry_at IS '下次重试时间';
COMMENT ON COLUMN tenant_outbox_event.published_at IS '发布时间';
COMMENT ON COLUMN tenant_outbox_event.last_error_code IS '最近错误码';
COMMENT ON COLUMN tenant_outbox_event.last_error_message IS '最近错误信息';
COMMENT ON COLUMN tenant_outbox_event.first_failed_at IS '首次失败时间';
COMMENT ON COLUMN tenant_outbox_event.dead_letter_at IS '进入死信时间';
COMMENT ON COLUMN tenant_outbox_event.created_by IS '创建人';
COMMENT ON COLUMN tenant_outbox_event.created_at IS '创建时间';
COMMENT ON COLUMN tenant_outbox_event.updated_by IS '更新人';
COMMENT ON COLUMN tenant_outbox_event.updated_at IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_tenant_outbox_status
    ON tenant_outbox_event (status, next_retry_at, id);
CREATE INDEX IF NOT EXISTS idx_tenant_outbox_lock
    ON tenant_outbox_event (status, lock_expires_at, id);
CREATE INDEX IF NOT EXISTS idx_tenant_outbox_dead_letter
    ON tenant_outbox_event (status, dead_letter_at, id);
CREATE INDEX IF NOT EXISTS idx_tenant_outbox_event
    ON tenant_outbox_event (event_id);
CREATE INDEX IF NOT EXISTS idx_tenant_outbox_aggregate
    ON tenant_outbox_event (aggregate_type, aggregate_id, id);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- tenant: 默认租户，供本地联调和首个租户初始化使用。
INSERT INTO tenant (code, normalized_code, name, status, contact_name, provisioned_at, enabled_at, remark, created_by, updated_by)
SELECT 'default', 'default', '默认租户', 'ENABLED', '系统管理员', now(), now(), 'V1 默认租户，由 xuan-tenant 管理租户生命周期。', 'system', 'system'
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant existing
    WHERE existing.normalized_code = 'default'
      AND existing.deleted_at IS NULL
);

-- tenant_status_history: 默认租户启用生命周期记录。
WITH default_tenant AS (
    SELECT id AS tenant_id
    FROM tenant
    WHERE normalized_code = 'default' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
)
INSERT INTO tenant_status_history (tenant_id, from_status, to_status, change_type, change_reason, changed_at, changed_by, trace_id, request_id, source, created_by)
SELECT default_tenant.tenant_id, 'PROVISIONING', 'ENABLED', 'V1_SEED', 'V1 默认租户初始化为启用状态。', now(), 'system', 'v1-default-tenant', 'v1-default-tenant', 'V1_SEED', 'system'
FROM default_tenant
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_status_history existing
    WHERE existing.tenant_id = default_tenant.tenant_id
      AND existing.to_status = 'ENABLED'
      AND existing.source = 'V1_SEED'
);

-- tenant_contact: 默认租户管理员联系人，供本地联调和首个租户初始化使用。
WITH default_tenant AS (
    SELECT id AS tenant_id
    FROM tenant
    WHERE normalized_code = 'default' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
)
INSERT INTO tenant_contact (tenant_id, contact_type, name, phone, email, is_primary, remark, created_by, updated_by)
SELECT default_tenant.tenant_id, 'ADMIN', '系统管理员', '13800000000', 'admin@default.local', true, 'V1 默认租户管理员联系人。', 'system', 'system'
FROM default_tenant
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_contact existing
    WHERE existing.tenant_id = default_tenant.tenant_id
      AND existing.contact_type = 'ADMIN'
      AND existing.is_primary = true
      AND existing.deleted_at IS NULL
);

-- tenant_plan: 默认基础套餐，供默认租户和本地联调使用。
INSERT INTO tenant_plan (code, name, status, billing_cycle, price_amount, currency, max_user_count, max_warehouse_count, max_storage_gb, feature_flags, sort_no, remark, created_by, updated_by)
SELECT 'FREE', '基础版', 'ENABLED', 'MONTHLY', 0, 'CNY', 10, 3, 10, '{"modules":["product","party","warehouse","inventory","sales","procurement","finance"]}'::jsonb, 10, 'V1 默认基础套餐。', 'system', 'system'
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_plan existing
    WHERE existing.code = 'FREE'
      AND existing.deleted_at IS NULL
);

-- tenant_domain: 默认租户本地域名占位，后续自定义域名流程可替换或新增。
WITH default_tenant AS (
    SELECT id AS tenant_id
    FROM tenant
    WHERE normalized_code = 'default' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
)
INSERT INTO tenant_domain (tenant_id, domain, normalized_domain, status, is_primary, verified_at, remark, created_by, updated_by)
SELECT default_tenant.tenant_id, 'default.local', 'default.local', 'VERIFIED', true, now(), 'V1 默认租户本地域名占位。', 'system', 'system'
FROM default_tenant
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_domain existing
    WHERE existing.normalized_domain = 'default.local'
      AND existing.deleted_at IS NULL
);

-- tenant_plan_assignment: 默认租户绑定基础套餐。
WITH default_tenant AS (
    SELECT id AS tenant_id
    FROM tenant
    WHERE normalized_code = 'default' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
),
default_plan AS (
    SELECT id AS plan_id
    FROM tenant_plan
    WHERE code = 'FREE' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
)
INSERT INTO tenant_plan_assignment (tenant_id, previous_plan_id, plan_id, status, effective_at, assigned_at, assigned_by, change_reason, source, created_by, updated_by)
SELECT default_tenant.tenant_id, NULL, default_plan.plan_id, 'ACTIVE', now(), now(), 'system', 'V1 默认租户绑定基础版套餐。', 'V1_SEED', 'system', 'system'
FROM default_tenant
CROSS JOIN default_plan
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_plan_assignment existing
    WHERE existing.tenant_id = default_tenant.tenant_id
      AND existing.status = 'ACTIVE'
      AND existing.deleted_at IS NULL
);

-- tenant_provision_task: 默认租户 V1 基线初始化记录。
WITH default_tenant AS (
    SELECT id AS tenant_id
    FROM tenant
    WHERE normalized_code = 'default' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
)
INSERT INTO tenant_provision_task (tenant_id, task_key, task_type, status, idempotency_key, step_name, request_payload, result_payload, retry_count, max_retry_count, started_at, finished_at, created_by, updated_by)
SELECT default_tenant.tenant_id, 'DEFAULT_BOOTSTRAP', 'TENANT_BOOTSTRAP', 'SUCCEEDED', 'tenant:default:bootstrap:v1', 'V1_BASELINE', '{}'::jsonb, '{"message":"V1 default tenant baseline initialized"}'::jsonb, 0, 5, now(), now(), 'system', 'system'
FROM default_tenant
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_provision_task existing
    WHERE existing.tenant_id = default_tenant.tenant_id
      AND existing.task_key = 'DEFAULT_BOOTSTRAP'
      AND existing.deleted_at IS NULL
);

-- tenant_provision_task_step: 默认租户 V1 基线初始化步骤记录。
WITH default_task AS (
    SELECT id AS provision_task_id, tenant_id
    FROM tenant_provision_task
    WHERE task_key = 'DEFAULT_BOOTSTRAP' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
)
INSERT INTO tenant_provision_task_step (tenant_id, provision_task_id, step_key, step_name, status, sequence_no, idempotency_key, request_payload, result_payload, retry_count, max_retry_count, started_at, finished_at, created_by, updated_by)
SELECT default_task.tenant_id, default_task.provision_task_id, 'V1_BASELINE', 'V1 基线初始化', 'SUCCEEDED', 1, 'tenant:default:bootstrap:v1:baseline', '{}'::jsonb, '{"message":"V1 baseline step completed"}'::jsonb, 0, 5, now(), now(), 'system', 'system'
FROM default_task
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_provision_task_step existing
    WHERE existing.provision_task_id = default_task.provision_task_id
      AND existing.step_key = 'V1_BASELINE'
      AND existing.deleted_at IS NULL
);

-- tenant_config: 默认租户的系统名称、语言和时区基础配置。
WITH default_tenant AS (
    SELECT id AS tenant_id
    FROM tenant
    WHERE normalized_code = 'default' AND deleted_at IS NULL
    ORDER BY id
    LIMIT 1
),
seed(config_key, config_value, value_type, description, is_public) AS (
    VALUES
        ('system.name', 'Xuan ERP', 'string', '系统显示名称', true),
        ('locale', 'zh-CN', 'string', '默认语言区域', true),
        ('timezone', 'Asia/Shanghai', 'string', '默认时区', true)
)
INSERT INTO tenant_config (tenant_id, config_key, config_value, value_type, description, is_public, created_by, updated_by)
SELECT default_tenant.tenant_id, seed.config_key, seed.config_value, seed.value_type, seed.description, seed.is_public, 'system', 'system'
FROM default_tenant
CROSS JOIN seed
WHERE NOT EXISTS (
    SELECT 1
    FROM tenant_config existing
    WHERE existing.tenant_id = default_tenant.tenant_id
      AND existing.config_key = seed.config_key
      AND existing.deleted_at IS NULL
);
