spring:
  config:
    import:
      - optional:nacos:xuan-common.yaml
      - optional:nacos:xuan-manufacturing.yaml
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: duaoyunxuan.synology.me:8848
        namespace: dev
        group: XUAN_ERP_GROUP
      config:
        server-addr: duaoyunxuan.synology.me:8848
        namespace: dev
        group: XUAN_ERP_GROUP
        file-extension: yaml
