-- xuan-product initial database objects
-- Generated from the legacy wms_backend structure and current Xuan ERP service boundaries.
-- Run this migration after connecting Flyway to this service's own database.

CREATE TABLE IF NOT EXISTS product_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    parent_id bigint,
    level_no integer DEFAULT 1 NOT NULL,
    sort_no integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_category PRIMARY KEY (id)
);
COMMENT ON TABLE product_category IS '商品分类表。';
COMMENT ON COLUMN product_category.id IS '主键';
COMMENT ON COLUMN product_category.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_category.code IS '分类编码';
COMMENT ON COLUMN product_category.name IS '分类名称';
COMMENT ON COLUMN product_category.parent_id IS '父级分类 ID';
COMMENT ON COLUMN product_category.level_no IS '层级';
COMMENT ON COLUMN product_category.sort_no IS '排序';
COMMENT ON COLUMN product_category.is_enabled IS '是否启用';
COMMENT ON COLUMN product_category.is_default IS '是否默认分类';
COMMENT ON COLUMN product_category.remark IS '备注';
COMMENT ON COLUMN product_category.created_by IS '创建人';
COMMENT ON COLUMN product_category.created_at IS '创建时间';
COMMENT ON COLUMN product_category.updated_by IS '更新人';
COMMENT ON COLUMN product_category.updated_at IS '更新时间';
COMMENT ON COLUMN product_category.deleted_by IS '删除人';
COMMENT ON COLUMN product_category.delete_reason IS '删除原因';
COMMENT ON COLUMN product_category.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_category_code_active
    ON product_category (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_category_default
    ON product_category (tenant_id)
    WHERE is_default = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_category_parent
    ON product_category (tenant_id, parent_id);
CREATE INDEX IF NOT EXISTS idx_product_category_tenant_deleted
    ON product_category (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS product_unit (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    symbol varchar(50),
    decimal_precision integer DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_unit PRIMARY KEY (id)
);
COMMENT ON TABLE product_unit IS '计量单位表。';
COMMENT ON COLUMN product_unit.id IS '主键';
COMMENT ON COLUMN product_unit.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_unit.code IS '单位编码';
COMMENT ON COLUMN product_unit.name IS '单位名称';
COMMENT ON COLUMN product_unit.symbol IS '单位符号';
COMMENT ON COLUMN product_unit.decimal_precision IS '数量小数位';
COMMENT ON COLUMN product_unit.is_enabled IS '是否启用';
COMMENT ON COLUMN product_unit.remark IS '备注';
COMMENT ON COLUMN product_unit.created_by IS '创建人';
COMMENT ON COLUMN product_unit.created_at IS '创建时间';
COMMENT ON COLUMN product_unit.updated_by IS '更新人';
COMMENT ON COLUMN product_unit.updated_at IS '更新时间';
COMMENT ON COLUMN product_unit.deleted_by IS '删除人';
COMMENT ON COLUMN product_unit.delete_reason IS '删除原因';
COMMENT ON COLUMN product_unit.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_unit_code_active
    ON product_unit (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_unit_tenant_deleted
    ON product_unit (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS vehicle_brand (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_vehicle_brand PRIMARY KEY (id)
);
COMMENT ON TABLE vehicle_brand IS '车型品牌表。';
COMMENT ON COLUMN vehicle_brand.id IS '主键';
COMMENT ON COLUMN vehicle_brand.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN vehicle_brand.code IS '品牌编码';
COMMENT ON COLUMN vehicle_brand.name IS '品牌名称';
COMMENT ON COLUMN vehicle_brand.is_enabled IS '是否启用';
COMMENT ON COLUMN vehicle_brand.remark IS '备注';
COMMENT ON COLUMN vehicle_brand.created_by IS '创建人';
COMMENT ON COLUMN vehicle_brand.created_at IS '创建时间';
COMMENT ON COLUMN vehicle_brand.updated_by IS '更新人';
COMMENT ON COLUMN vehicle_brand.updated_at IS '更新时间';
COMMENT ON COLUMN vehicle_brand.deleted_by IS '删除人';
COMMENT ON COLUMN vehicle_brand.delete_reason IS '删除原因';
COMMENT ON COLUMN vehicle_brand.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_vehicle_brand_code_active
    ON vehicle_brand (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_vehicle_brand_name
    ON vehicle_brand (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_product_vehicle_brand_tenant_deleted
    ON vehicle_brand (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS vehicle_series (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_vehicle_series PRIMARY KEY (id)
);
COMMENT ON TABLE vehicle_series IS '车型车系表。';
COMMENT ON COLUMN vehicle_series.id IS '主键';
COMMENT ON COLUMN vehicle_series.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN vehicle_series.brand_id IS '品牌 ID';
COMMENT ON COLUMN vehicle_series.code IS '车系编码';
COMMENT ON COLUMN vehicle_series.name IS '车系名称';
COMMENT ON COLUMN vehicle_series.is_enabled IS '是否启用';
COMMENT ON COLUMN vehicle_series.remark IS '备注';
COMMENT ON COLUMN vehicle_series.created_by IS '创建人';
COMMENT ON COLUMN vehicle_series.created_at IS '创建时间';
COMMENT ON COLUMN vehicle_series.updated_by IS '更新人';
COMMENT ON COLUMN vehicle_series.updated_at IS '更新时间';
COMMENT ON COLUMN vehicle_series.deleted_by IS '删除人';
COMMENT ON COLUMN vehicle_series.delete_reason IS '删除原因';
COMMENT ON COLUMN vehicle_series.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_vehicle_series_code_active
    ON vehicle_series (tenant_id, brand_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_vehicle_series_brand
    ON vehicle_series (tenant_id, brand_id);
CREATE INDEX IF NOT EXISTS idx_product_vehicle_series_tenant_deleted
    ON vehicle_series (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS vehicle_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    series_id bigint NOT NULL,
    code varchar(50) NOT NULL,
    name varchar(120) NOT NULL,
    year_from integer,
    year_to integer,
    displacement varchar(50),
    engine varchar(100),
    is_enabled boolean DEFAULT true NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_vehicle_model PRIMARY KEY (id)
);
COMMENT ON TABLE vehicle_model IS '车型表。';
COMMENT ON COLUMN vehicle_model.id IS '主键';
COMMENT ON COLUMN vehicle_model.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN vehicle_model.series_id IS '车系 ID';
COMMENT ON COLUMN vehicle_model.code IS '车型编码';
COMMENT ON COLUMN vehicle_model.name IS '车型名称';
COMMENT ON COLUMN vehicle_model.year_from IS '起始年款';
COMMENT ON COLUMN vehicle_model.year_to IS '结束年款';
COMMENT ON COLUMN vehicle_model.displacement IS '排量';
COMMENT ON COLUMN vehicle_model.engine IS '发动机型号';
COMMENT ON COLUMN vehicle_model.is_enabled IS '是否启用';
COMMENT ON COLUMN vehicle_model.remark IS '备注';
COMMENT ON COLUMN vehicle_model.created_by IS '创建人';
COMMENT ON COLUMN vehicle_model.created_at IS '创建时间';
COMMENT ON COLUMN vehicle_model.updated_by IS '更新人';
COMMENT ON COLUMN vehicle_model.updated_at IS '更新时间';
COMMENT ON COLUMN vehicle_model.deleted_by IS '删除人';
COMMENT ON COLUMN vehicle_model.delete_reason IS '删除原因';
COMMENT ON COLUMN vehicle_model.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_vehicle_model_code_active
    ON vehicle_model (tenant_id, series_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_vehicle_model_series
    ON vehicle_model (tenant_id, series_id);
CREATE INDEX IF NOT EXISTS idx_product_vehicle_model_tenant_deleted
    ON vehicle_model (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS product (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    code varchar(100) NOT NULL,
    name varchar(200) NOT NULL,
    short_name varchar(100),
    spec varchar(200),
    model varchar(200),
    category_id bigint,
    unit_id bigint,
    barcode varchar(100),
    sku varchar(100),
    brand varchar(100),
    origin varchar(200),
    weight numeric(18,4),
    volume numeric(18,4),
    cost_price numeric(18,4) DEFAULT 0 NOT NULL,
    sale_price numeric(18,4) DEFAULT 0 NOT NULL,
    tax_rate numeric(10,4) DEFAULT 0 NOT NULL,
    safety_stock numeric(18,4) DEFAULT 0 NOT NULL,
    min_stock numeric(18,4) DEFAULT 0 NOT NULL,
    max_stock numeric(18,4) DEFAULT 0 NOT NULL,
    is_batch boolean DEFAULT false NOT NULL,
    shelf_life_days integer,
    product_type varchar(20) DEFAULT 'NORMAL' NOT NULL,
    manufacturer_code varchar(100),
    manufacturer_model varchar(200),
    manufacturer_name varchar(200),
    default_warehouse_id bigint,
    default_warehouse_name_snapshot varchar(200),
    default_location_id bigint,
    default_location_name_snapshot varchar(200),
    source_supplier_id bigint,
    source_supplier_name_snapshot varchar(200),
    is_enabled boolean DEFAULT true NOT NULL,
    ext_attrs jsonb,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product PRIMARY KEY (id)
);
COMMENT ON TABLE product IS '商品主档表。';
COMMENT ON COLUMN product.id IS '主键';
COMMENT ON COLUMN product.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product.code IS '商品编码';
COMMENT ON COLUMN product.name IS '商品名称';
COMMENT ON COLUMN product.short_name IS '商品简称';
COMMENT ON COLUMN product.spec IS '规格';
COMMENT ON COLUMN product.model IS '型号';
COMMENT ON COLUMN product.category_id IS '分类 ID';
COMMENT ON COLUMN product.unit_id IS '单位 ID';
COMMENT ON COLUMN product.barcode IS '条码';
COMMENT ON COLUMN product.sku IS 'SKU';
COMMENT ON COLUMN product.brand IS '品牌';
COMMENT ON COLUMN product.origin IS '产地';
COMMENT ON COLUMN product.weight IS '重量';
COMMENT ON COLUMN product.volume IS '体积';
COMMENT ON COLUMN product.cost_price IS '成本价';
COMMENT ON COLUMN product.sale_price IS '销售价';
COMMENT ON COLUMN product.tax_rate IS '默认税率';
COMMENT ON COLUMN product.safety_stock IS '默认安全库存';
COMMENT ON COLUMN product.min_stock IS '默认最低库存';
COMMENT ON COLUMN product.max_stock IS '默认最高库存';
COMMENT ON COLUMN product.is_batch IS '是否批次管理';
COMMENT ON COLUMN product.shelf_life_days IS '保质期天数';
COMMENT ON COLUMN product.product_type IS '商品类型';
COMMENT ON COLUMN product.manufacturer_code IS '厂家编码';
COMMENT ON COLUMN product.manufacturer_model IS '厂家型号';
COMMENT ON COLUMN product.manufacturer_name IS '厂家名称';
COMMENT ON COLUMN product.default_warehouse_id IS '默认仓库 ID';
COMMENT ON COLUMN product.default_warehouse_name_snapshot IS '默认仓库名称快照';
COMMENT ON COLUMN product.default_location_id IS '默认库位 ID';
COMMENT ON COLUMN product.default_location_name_snapshot IS '默认库位名称快照';
COMMENT ON COLUMN product.source_supplier_id IS '来源供应商 ID';
COMMENT ON COLUMN product.source_supplier_name_snapshot IS '来源供应商名称快照';
COMMENT ON COLUMN product.is_enabled IS '是否启用';
COMMENT ON COLUMN product.ext_attrs IS '扩展属性';
COMMENT ON COLUMN product.remark IS '备注';
COMMENT ON COLUMN product.created_by IS '创建人';
COMMENT ON COLUMN product.created_at IS '创建时间';
COMMENT ON COLUMN product.updated_by IS '更新人';
COMMENT ON COLUMN product.updated_at IS '更新时间';
COMMENT ON COLUMN product.deleted_by IS '删除人';
COMMENT ON COLUMN product.delete_reason IS '删除原因';
COMMENT ON COLUMN product.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_product_code_active
    ON product (tenant_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_name
    ON product (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_product_manufacturer_code
    ON product (tenant_id, manufacturer_code)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_product_tenant_deleted
    ON product (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS product_price (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    product_id bigint NOT NULL,
    customer_category_id bigint NOT NULL,
    customer_category_name_snapshot varchar(200),
    sale_price numeric(18,4) DEFAULT 0 NOT NULL,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_price PRIMARY KEY (id)
);
COMMENT ON TABLE product_price IS '商品按客户类别的售价表。';
COMMENT ON COLUMN product_price.id IS '主键';
COMMENT ON COLUMN product_price.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_price.product_id IS '商品 ID';
COMMENT ON COLUMN product_price.customer_category_id IS '客户类别 ID';
COMMENT ON COLUMN product_price.customer_category_name_snapshot IS '客户类别名称快照';
COMMENT ON COLUMN product_price.sale_price IS '售价';
COMMENT ON COLUMN product_price.created_by IS '创建人';
COMMENT ON COLUMN product_price.created_at IS '创建时间';
COMMENT ON COLUMN product_price.updated_by IS '更新人';
COMMENT ON COLUMN product_price.updated_at IS '更新时间';
COMMENT ON COLUMN product_price.deleted_by IS '删除人';
COMMENT ON COLUMN product_price.delete_reason IS '删除原因';
COMMENT ON COLUMN product_price.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_product_price_key_active
    ON product_price (tenant_id, product_id, customer_category_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_price_product
    ON product_price (tenant_id, product_id, deleted_at);

CREATE TABLE IF NOT EXISTS product_fitment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    product_id bigint NOT NULL,
    model_id bigint NOT NULL,
    remark varchar(500),
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_fitment PRIMARY KEY (id)
);
COMMENT ON TABLE product_fitment IS '商品适配车型关系表。';
COMMENT ON COLUMN product_fitment.id IS '主键';
COMMENT ON COLUMN product_fitment.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_fitment.product_id IS '商品 ID';
COMMENT ON COLUMN product_fitment.model_id IS '车型 ID';
COMMENT ON COLUMN product_fitment.remark IS '备注';
COMMENT ON COLUMN product_fitment.created_by IS '创建人';
COMMENT ON COLUMN product_fitment.created_at IS '创建时间';
COMMENT ON COLUMN product_fitment.updated_by IS '更新人';
COMMENT ON COLUMN product_fitment.updated_at IS '更新时间';
COMMENT ON COLUMN product_fitment.deleted_by IS '删除人';
COMMENT ON COLUMN product_fitment.delete_reason IS '删除原因';
COMMENT ON COLUMN product_fitment.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_fitment_key_active
    ON product_fitment (tenant_id, product_id, model_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_fitment_model
    ON product_fitment (tenant_id, model_id);
CREATE INDEX IF NOT EXISTS idx_product_fitment_tenant_deleted
    ON product_fitment (tenant_id, deleted_at);

CREATE TABLE IF NOT EXISTS product_import_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_no varchar(64) NOT NULL,
    source_name varchar(255),
    import_mode varchar(32) DEFAULT 'EXCEL_UPLOAD' NOT NULL,
    total_count integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    warning_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    summary text,
    raw_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_import_batch PRIMARY KEY (id)
);
COMMENT ON TABLE product_import_batch IS '商品导入批次。';
COMMENT ON COLUMN product_import_batch.id IS '主键';
COMMENT ON COLUMN product_import_batch.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_import_batch.batch_no IS '导入批次号';
COMMENT ON COLUMN product_import_batch.source_name IS '来源文件名';
COMMENT ON COLUMN product_import_batch.import_mode IS '导入模式';
COMMENT ON COLUMN product_import_batch.total_count IS '总数';
COMMENT ON COLUMN product_import_batch.success_count IS '成功数';
COMMENT ON COLUMN product_import_batch.failed_count IS '失败数';
COMMENT ON COLUMN product_import_batch.warning_count IS '警告数';
COMMENT ON COLUMN product_import_batch.status IS '状态';
COMMENT ON COLUMN product_import_batch.summary IS '导入摘要';
COMMENT ON COLUMN product_import_batch.raw_payload IS '原始载荷';
COMMENT ON COLUMN product_import_batch.created_by IS '创建人';
COMMENT ON COLUMN product_import_batch.created_at IS '创建时间';
COMMENT ON COLUMN product_import_batch.updated_by IS '更新人';
COMMENT ON COLUMN product_import_batch.updated_at IS '更新时间';
COMMENT ON COLUMN product_import_batch.deleted_by IS '删除人';
COMMENT ON COLUMN product_import_batch.delete_reason IS '删除原因';
COMMENT ON COLUMN product_import_batch.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_impo_batch_no_active
    ON product_import_batch (tenant_id, batch_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_import_batch_status
    ON product_import_batch (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS product_import_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    row_no integer NOT NULL,
    source_code varchar(128),
    source_name varchar(255),
    matched_target_id bigint,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    error_field varchar(128),
    error_message text,
    warning_message text,
    raw_row jsonb NOT NULL,
    normalized_payload jsonb,
    created_by varchar(100),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by varchar(100),
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_by varchar(100),
    delete_reason varchar(500),
    deleted_at timestamptz,
    CONSTRAINT pk_product_import_item PRIMARY KEY (id)
);
COMMENT ON TABLE product_import_item IS '商品导入明细。';
COMMENT ON COLUMN product_import_item.id IS '主键';
COMMENT ON COLUMN product_import_item.tenant_id IS '租户 ID，来源于 xuan-tenant';
COMMENT ON COLUMN product_import_item.batch_id IS '导入批次 ID';
COMMENT ON COLUMN product_import_item.row_no IS '行号';
COMMENT ON COLUMN product_import_item.source_code IS '来源编码';
COMMENT ON COLUMN product_import_item.source_name IS '来源名称';
COMMENT ON COLUMN product_import_item.matched_target_id IS '匹配目标 ID';
COMMENT ON COLUMN product_import_item.status IS '状态';
COMMENT ON COLUMN product_import_item.error_field IS '错误字段';
COMMENT ON COLUMN product_import_item.error_message IS '错误信息';
COMMENT ON COLUMN product_import_item.warning_message IS '警告信息';
COMMENT ON COLUMN product_import_item.raw_row IS '原始行';
COMMENT ON COLUMN product_import_item.normalized_payload IS '规范化数据';
COMMENT ON COLUMN product_import_item.created_by IS '创建人';
COMMENT ON COLUMN product_import_item.created_at IS '创建时间';
COMMENT ON COLUMN product_import_item.updated_by IS '更新人';
COMMENT ON COLUMN product_import_item.updated_at IS '更新时间';
COMMENT ON COLUMN product_import_item.deleted_by IS '删除人';
COMMENT ON COLUMN product_import_item.delete_reason IS '删除原因';
COMMENT ON COLUMN product_import_item.deleted_at IS '逻辑删除时间';
CREATE INDEX IF NOT EXISTS idx_product_impo_batch_row_active
    ON product_import_item (tenant_id, batch_id, row_no)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_product_import_item_status
    ON product_import_item (tenant_id, status)
    WHERE deleted_at IS NULL;

-- Seata AT undo log table
CREATE TABLE IF NOT EXISTS undo_log (
    branch_id bigint NOT NULL,
    xid varchar(128) NOT NULL,
    context varchar(128) NOT NULL,
    rollback_info bytea NOT NULL,
    log_status integer NOT NULL,
    log_created timestamp(6) NOT NULL,
    log_modified timestamp(6) NOT NULL,
    CONSTRAINT pk_undo_log PRIMARY KEY (branch_id, xid)
);
COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志表。';
COMMENT ON COLUMN undo_log.branch_id IS 'Seata 分支事务 ID';
COMMENT ON COLUMN undo_log.xid IS 'Seata 全局事务 ID';
COMMENT ON COLUMN undo_log.context IS '上下文';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息';
COMMENT ON COLUMN undo_log.log_status IS '日志状态';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_undo_log_log_created ON undo_log (log_created);

-- V1 initialization data
-- These rows are idempotent and only provide default dictionaries/configuration.

-- product_category: 默认商品分类，便于首批商品档案落位。
INSERT INTO product_category (tenant_id, code, name, level_no, sort_no, is_enabled, is_default, remark, created_by, updated_by)
SELECT 1, 'DEFAULT', '默认分类', 1, 0, true, true, 'V1 默认商品分类。', 'system', 'system'
WHERE NOT EXISTS (
    SELECT 1
    FROM product_category existing
    WHERE existing.tenant_id = 1
      AND existing.code = 'DEFAULT'
      AND existing.deleted_at IS NULL
);

-- product_unit: 常用计量单位，后续可按租户继续维护。
INSERT INTO product_unit (tenant_id, code, name, symbol, decimal_precision, is_enabled, remark, created_by, updated_by)
SELECT 1, seed.code, seed.name, seed.symbol, seed.decimal_precision, seed.is_enabled, seed.remark, 'system', 'system'
FROM (
    VALUES
        ('PCS', '个', '个', 0, true, '默认单位。'),
        ('SET', '套', '套', 0, true, '常用单位。'),
        ('BOX', '箱', '箱', 0, true, '常用单位。'),
        ('BOTTLE', '瓶', '瓶', 0, true, '常用单位。'),
        ('LITER', '升', 'L', 4, true, '可带小数的容量单位。')
) AS seed(code, name, symbol, decimal_precision, is_enabled, remark)
WHERE NOT EXISTS (
    SELECT 1
    FROM product_unit existing
    WHERE existing.tenant_id = 1
      AND existing.code = seed.code
      AND existing.deleted_at IS NULL
);
